# Nội dung 3 — Thực nghiệm ACRF-RNN

**Mục tiêu:** Chạy mô hình ACRF-RNN với dữ liệu sau khi thực hiện Spark pipeline, so sánh **paper với hai phiên bản**.

| Phiên bản | Tiêu chí early stopping | Gradient update | Fix áp dụng |
|---|---|---|---|
| **VerA** — Code-faithful | `train_loss < loss_min` | 1 lần sau toàn bộ epoch | Fix 4-9 |
| **VerB** — Paper-faithful | `eval_ks > best_ks` | Mỗi `batch_train=4` bước | Fix 1–9 |

**Ý nghĩa:** So sánh VerA vs VerB định lượng tác động của mâu thuẫn M1 (early stopping) và M3 (gradient accumulation).

**Tiêu chí:** KS >= 35% trên ít nhất một năm kiểm thử; Recallm và G-mean trong khoảng +-5% so với bài báo.

## Giai đoạn 1 - Kiểm tra môi trường

### 1.1 Kiểm tra Python & GPU

In [80]:
!python --version
import torch
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory/1024**3,1), "GB")
else:
    print("Không có GPU - vào Runtime > Change runtime type > GPU")

Python 3.12.13
Torch: 2.11.0+cu128
CUDA: True
GPU: Tesla T4
VRAM: 14.6 GB

### 1.2 Tải thư viện

In [81]:
!pip install -q numpy pandas scipy scikit-learn tqdm

## Giai đoạn 2 - Clone repo và tạo thư mục

### 2.1 Clone repo tác giả

In [82]:
import os
os.chdir("/content")
print(os.getcwd())

/content

In [83]:
!rm -rf /content/ACRF-RNN
!git clone https://github.com/XNetLab/ACRF-RNN.git
!ls /content/ACRF-RNN/Code/

Cloning into 'ACRF-RNN'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 32 (delta 4), reused 32 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (32/32), 3.45 MiB | 22.05 MiB/s, done.
Resolving deltas: 100% (4/4), done.
layer.py  main.py  model.py  util4.py

### 2.2 Tạo thư mục làm việc

In [84]:
import os
os.makedirs("/content/project_data", exist_ok=True)
os.makedirs("/content/project_outputs", exist_ok=True)
os.makedirs("/content/ACRF-RNN/Code/savemodel", exist_ok=True)
print("Thư mục sẵn sàng")
!ls /content/

Thư mục sẵn sàng
ACRF-RNN  drive  project_data  project_outputs	sample_data

## Giai đoạn 3 - Tải dữ liệu từ Google Drive

File `processed_flat.json` (output của Spark pipeline - Nội dung 2) đặt tại:
`/content/drive/MyDrive/ACRF-RNN/processed_flat.json`

### 3.1 Mount Google Drive

In [85]:
from google.colab import drive
drive.mount('/content/drive')

drive_path = '/content/drive/MyDrive/ACRF-RNN'
print("Files trong Drive path:")
print(os.listdir(drive_path) if os.path.exists(drive_path) else "Không tìm thấy thư mục")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Files trong Drive path:
['Nộp', 'fraud_project.zip', 'processed_flat.json', 'processed.zip', 'Spark_Pipeline.ipynb', 'acrf-rnn.zip', 'feature_analysis.zip', 'Spark_Temporal_Feature_Analysis.ipynb', 'ACRF_RNN.ipynb']

### 3.2 Copy và kiểm tra file JSON

In [86]:
JSON_SRC  = '/content/drive/MyDrive/ACRF-RNN/processed_flat.json'
JSON_DEST = '/content/project_data/processed_flat.json'

!cp "{JSON_SRC}" "{JSON_DEST}"

import json, os
size_mb = os.path.getsize(JSON_DEST) / 1024**2
with open(JSON_DEST) as f:
    meta = json.load(f)

print(f"File: {JSON_DEST} ({size_mb:.1f} MB)")
print(f"  format           : {meta['format']}")
print(f"  num_years        : {meta['num_years']}")
print(f"  num_companies    : {meta['num_companies_per_year']}")
print(f"  num_cols_per_row : {meta['num_columns_per_row']}")
print(f"  years            : {[d['year'] for d in meta['data']]}")
print(f"  last 3 cols      : {meta['columns'][-3:]}")

assert meta["num_columns_per_row"] == 209, "Số cột sai, kiểm tra lại pipeline"
assert meta["columns"][-1] == "label",    "Cột cuối phải là label"
print("\nFile JSON hợp lệ")

File: /content/project_data/processed_flat.json (20.5 MB)
  format           : main_py_compatible_year_major
  num_years        : 10
  num_companies    : 491
  num_cols_per_row : 209
  years            : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
  last 3 cols      : ['D000200000', 'sj_label', 'label']

File JSON hợp lệ

## Giai đoạn 4 - Import thư viện

In [87]:
import os, sys, json, random, re
import numpy as np
import pandas as pd
import torch
from torch import optim
from scipy.stats import ks_2samp
from sklearn.metrics import recall_score

## Giai đoạn 5 — Vá code

### Phân loại fix theo phiên bản

**Dùng chung (VerA và VerB)** — Fix lỗi CUDA crash:

| # | File | Dòng | Vấn đề | Fix |
|---|---|---|---|---|
| Fix 7 | `model.py` | 15 | `self.attentions=[...]` Python list → không chuyển lên GPU | `nn.ModuleList(...)` |
| Fix 8 | `layer.py` | 105 | `logits=torch.zeros(...)` tạo ở CPU; cộng với GPU tensor | Thêm `device=input_r.device` |
| Fix 9 | `layer.py` | 113–114 | `self.coef_revise` tạo ở CPU; nhân với GPU tensor | Thêm `.to(device)` |

**VerA only** — Fix crash Python 3.9+, giữ nguyên logic:

| # | File | Dòng | Vấn đề | Fix |
|---|---|---|---|---|
| Fix 4 | `main.py` | đầu file | Thiếu `import random`, `import os` | Thêm vào |
| Fix 5 | `main.py` | 54 | `args.dropout` chưa khai báo | Thêm `--dropout` |
| Fix 6 | `main.py` | 108 | `random.shuffle(seq, random=r)` lỗi Python ≥ 3.9 | Bỏ `random=` |

**VerB thêm** — Fix logic + đọc JSON:

| # | File | Dòng | Vấn đề | Fix |
|---|---|---|---|---|
| Fix 1 | `main.py` | 81 | `np.squeeze(axis=2)` lỗi khi JSON đã là `[T,N,209]` | Bỏ squeeze |
| Fix 2 | `main.py` | 89 | `test_line=test_year-2021-1` hardcode | `years.index(test_year)` |
| Fix 3 | `main.py` | 133,167 | `plt_output` chưa định nghĩa | Xóa các dòng tham chiếu |

### 5.1 Vá `layer.py` — Fix 8, 9

**Fix 8** (`Attention.forward()`, dòng 105):
```python
# TRƯỚC (lỗi): logits tạo ở CPU, cộng với f_1/f_2 ở GPU → crash
logits = torch.zeros(num_stock, num_stock, dtype=input_r.dtype)

# SAU: thêm device=device
logits = torch.zeros(num_stock, num_stock, dtype=input_r.dtype, device=device)
```

**Fix 9** (`Attention.forward()`, dòng 113-114):
```python
# TRƯỚC (lỗi): coef_revise tạo ở CPU, nhân với coefs ở GPU → crash
self.coef_revise = torch.zeros(...) + 1.0 - torch.eye(...)

# SAU: thêm .to(device)
self.coef_revise = (torch.zeros(...) + 1.0 - torch.eye(...)).to(device)
```

In [88]:
# layer.py — Fix 8 (logits device) + Fix 9 (coef_revise device)
fixed_layer = r'''
import torch.nn.functional as F
from torch import nn
import torch
from util4 import *


class CRF_Att(nn.Module):

    def __init__(self, input_dim, output_dim, num_iters):
        super(CRF_Att, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.num_iters = num_iters
        self.al   = nn.Parameter(torch.zeros(1).type(torch.FloatTensor))
        self.beta = nn.Parameter(torch.zeros(1).type(torch.FloatTensor))

    def forward(self, inputs, similarity):
        support   = similarity
        normalize = torch.sum(support, dim=1)
        normalize = torch.Tensor.repeat(torch.unsqueeze(normalize, -1), [1, self.input_dim])
        al   = torch.exp(self.al)
        beta = torch.exp(self.beta)
        output = inputs
        iters  = torch.tensor(0)
        cond   = lambda iters, num_iters: torch.le(iters, self.num_iters)
        while cond(iters, output):
            output = (inputs * beta + (dot(support, output) + output) * al) \
                     / (beta + normalize * al + al)
            iters = torch.add(iters, 1)
        return output


class Linear(nn.Module):
    def __init__(self, num_nodes, input_size, hidden_size, bias=True):
        super(Linear, self).__init__()
        self.bias = bias
        self.W = nn.Parameter(torch.zeros(num_nodes, input_size, hidden_size))
        self.b = nn.Parameter(torch.zeros(num_nodes, hidden_size))
        self.reset_parameters()

    def reset_parameters(self):
        reset_parameters(self.named_parameters)

    def forward(self, x):
        output = torch.bmm(x.unsqueeze(1), self.W)
        output = output.squeeze(1)
        if self.bias:
            output = output + self.b
        return output


class GRUModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, bias=True):
        super(GRUModel, self).__init__()
        self.GRU_layer1 = nn.GRU(input_size=input_dim,    hidden_size=2 * hidden_dim)
        self.GRU_layer2 = nn.GRU(input_size=2 * hidden_dim, hidden_size=hidden_dim)
        self.hidden_dim = hidden_dim
        self.hidden = None
        self.reset_parameters()

    def reset_parameters(self):
        reset_parameters(self.named_parameters)

    def forward(self, x):
        x, hidden1 = self.GRU_layer1(x)
        x, hidden2 = self.GRU_layer2(x)
        hidden = hidden2.squeeze(0)
        return hidden


class Attention(nn.Module):
    def __init__(self, in_features, out_features, alpha, num_company, residual=False):
        super(Attention, self).__init__()
        self.in_features  = in_features
        self.out_features = out_features
        self.alpha        = alpha
        self.num_company  = num_company
        self.seq_transformation_r = nn.Conv1d(in_features, out_features, kernel_size=1, stride=1, bias=False)
        self.f_1 = nn.Conv1d(out_features, 1, kernel_size=1, stride=1)
        self.f_2 = nn.Conv1d(out_features, 1, kernel_size=1, stride=1)
        self.W_static    = nn.Parameter(torch.zeros(self.num_company, self.num_company).type(torch.FloatTensor), requires_grad=True)
        self.w_1         = nn.Conv1d(in_features, out_features, kernel_size=1, stride=1)
        self.w_2         = nn.Conv1d(in_features, out_features, kernel_size=1, stride=1)
        self.coef_revise = False
        self.leakyrelu   = nn.LeakyReLU(self.alpha)

    def forward(self, input_r, relation_static=None):
        device    = input_r.device                                    # lấy device từ input
        num_stock = input_r.shape[0]
        seq_r     = torch.transpose(input_r, 0, 1).unsqueeze(0)
        # Fix 8: thêm device=device để logits cùng device với f_1, f_2
        logits    = torch.zeros(num_stock, num_stock, dtype=input_r.dtype, device=device)
        seq_fts_r = self.seq_transformation_r(seq_r)
        f_1 = self.f_1(seq_fts_r)
        f_2 = self.f_2(seq_fts_r)
        logits += (torch.transpose(f_1, 2, 1) + f_2).squeeze(0)
        if relation_static is not None:
            logits += torch.mul(relation_static, self.W_static)
        coefs = self.leakyrelu(logits)
        # Fix 9: thêm .to(device) để coef_revise cùng device với coefs
        if not isinstance(self.coef_revise, torch.Tensor):
            self.coef_revise = (
                torch.zeros(self.num_company, self.num_company)
                + 1.0
                - torch.eye(self.num_company, self.num_company)
            ).to(device)
        else:
            self.coef_revise = self.coef_revise.to(device)
        coefs_eye = coefs.mul(self.coef_revise)
        return coefs_eye


def myPool(type, crf_embeddings):
    head = len(crf_embeddings)
    company_num, feature_num = crf_embeddings[0].size()
    stacked_tensor = torch.stack(crf_embeddings, dim=1)
    pool_embedding = stacked_tensor.view(-1, feature_num)
    pool_embedding = pool_embedding.t()
    if type == "MAX":
        pool = nn.MaxPool1d(kernel_size=head, stride=head)
        pooled_embedding = pool(pool_embedding).t()
    elif type == "AVG":
        pool = nn.AvgPool1d(kernel_size=head, stride=head)
        pooled_embedding = pool(pool_embedding).t()
    elif type == "SUM":
        stacked_tensor2  = torch.stack(crf_embeddings, dim=0)
        pooled_embedding = torch.sum(stacked_tensor2, dim=0)
    return pooled_embedding
'''

with open("/content/ACRF-RNN/Code/layer.py", "w", encoding="utf-8") as f:
    f.write(fixed_layer)
print("Đã ghi /content/ACRF-RNN/Code/layer.py")
!wc -l /content/ACRF-RNN/Code/layer.py

Đã ghi /content/ACRF-RNN/Code/layer.py
129 /content/ACRF-RNN/Code/layer.py

### 5.2 Vá `model.py` — Fix 7

**Fix 7** (`AC_RNN.__init__()`, dòng 15):
```python
# TRƯỚC (lỗi): Python list — model.to(DEVICE) không chuyển Attention lên GPU
self.attentions = [Attention(...) for _ in range(heads_att)]

# SAU: nn.ModuleList — model.to(DEVICE) chuyển toàn bộ module lên GPU
self.attentions = nn.ModuleList([Attention(...) for _ in range(heads_att)])
```

In [89]:
# model.py —Fix 7 (nn.ModuleList)
fixed_model = r'''
from layer import *
from torch import nn


class AC_RNN(nn.Module):
    def __init__(self, num_company, d_feature, d_hidden, hidn_rnn,
                 heads_att, hidn_att, crf_iters, alpha, pool_type):
        super(AC_RNN, self).__init__()
        self.heads_att   = heads_att
        self.alpha       = alpha
        self.num_company = num_company
        self.d_feature   = d_feature
        self.d_hidden    = d_hidden
        self.hidden_rnn  = hidn_rnn
        self.hidn_att    = hidn_att
        self.GRUs        = GRUModel(d_feature, hidn_rnn)
        # Fix 7: đổi từ Python list sang nn.ModuleList
        # nn.ModuleList đảm bảo model.to(DEVICE) sẽ chuyển tất cả
        # Attention modules (và Conv1d bên trong) lên dùng device
        self.attentions  = nn.ModuleList([
            Attention(hidn_rnn, hidn_att, num_company=self.num_company, alpha=self.alpha)
            for _ in range(heads_att)
        ])
        self.crf         = CRF_Att(hidn_rnn, hidn_rnn, crf_iters)
        self.pool_type   = pool_type
        self.linear      = Linear(num_company, hidn_rnn, 2, bias=True)
        self.reset_parameters()

    def reset_parameters(self):
        reset_parameters(self.named_parameters)

    def forward(self, x):
        x            = self.GRUs(x)
        x            = F.dropout(x, self.drop_out)
        ss           = [att(x) for att in self.attentions]
        crf_embeddings = []
        for i in ss:
            crf_x_attention = self.crf(x, i)
            crf_embeddings.append(crf_x_attention)
        crf_x      = myPool(self.pool_type, crf_embeddings)
        crf_output = F.elu(self.linear(crf_x))
        crf_output = F.softmax(crf_output, dim=1)
        return crf_output


class FocalLoss(nn.Module):
    def __init__(self, weight=None, reduction="mean", gamma=0, eps=1e-7):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.eps   = eps
        self.ce    = torch.nn.CrossEntropyLoss(weight=weight, reduction=reduction)

    def forward(self, input, target):
        logp = self.ce(input, target)
        p    = torch.exp(-logp)
        loss = (1 - p) ** self.gamma * logp
        return loss.mean()
'''

with open("/content/ACRF-RNN/Code/model.py", "w", encoding="utf-8") as f:
    f.write(fixed_model)
print("Đã ghi /content/ACRF-RNN/Code/model.py")
!wc -l /content/ACRF-RNN/Code/model.py

Đã ghi /content/ACRF-RNN/Code/model.py
58 /content/ACRF-RNN/Code/model.py

### 5.2.1 Tạo `model_attention.py` để trích xuất Attention Graph

Không sửa trực tiếp `model.py` cũ để tránh làm hỏng luồng train/test ban đầu.  
Thay vào đó, tạo thêm file `model_attention.py`, giữ nguyên kiến trúc `AC_RNN` nhưng bổ sung tham số `return_attention`.

- Nếu `return_attention=False`: model trả output như cũ.
- Nếu `return_attention=True`: model trả thêm `attention_stack`.

`attention_stack` là tensor chứa các ma trận attention của nhiều head:

```text
attention_stack shape = [heads_att, num_company, num_company]

In [90]:
# model_attention.py

model_attention_code = r'''
from layer import *
from torch import nn
import torch
import torch.nn.functional as F


class AC_RNN(nn.Module):
    def __init__(self, num_company, d_feature, d_hidden, hidn_rnn,
                 heads_att, hidn_att, crf_iters, alpha, pool_type):
        super(AC_RNN, self).__init__()

        self.heads_att   = heads_att
        self.alpha       = alpha
        self.num_company = num_company
        self.d_feature   = d_feature
        self.d_hidden    = d_hidden
        self.hidden_rnn  = hidn_rnn
        self.hidn_att    = hidn_att

        self.GRUs = GRUModel(d_feature, hidn_rnn)

        self.attentions = nn.ModuleList([
            Attention(
                hidn_rnn,
                hidn_att,
                num_company=self.num_company,
                alpha=self.alpha
            )
            for _ in range(heads_att)
        ])

        self.crf       = CRF_Att(hidn_rnn, hidn_rnn, crf_iters)
        self.pool_type = pool_type
        self.linear    = Linear(num_company, hidn_rnn, 2, bias=True)

        # Giữ tương thích với main_vera.py cũ
        # vì main_vera.py sẽ gán model.drop_out = args.dropout sau khi tạo model.
        self.drop_out = 0.0

        self.reset_parameters()

    def reset_parameters(self):
        reset_parameters(self.named_parameters)

    def forward(self, x, return_attention=False):
        """
        x shape dự kiến:
            [rnn_len, num_company, d_feature]

        return_attention=False:
            return crf_output

        return_attention=True:
            return crf_output, attention_stack

        attention_stack shape:
            [heads_att, num_company, num_company]
        """

        # 1. GRU học embedding theo thời gian
        x = self.GRUs(x)

        # 2. Dropout giống model cũ
        x = F.dropout(x, self.drop_out, training=self.training)

        # 3. Tính attention matrix cho từng head
        attention_list = [att(x) for att in self.attentions]

        # 4. Đưa từng attention matrix vào CRF
        crf_embeddings = []
        for att_matrix in attention_list:
            crf_x_attention = self.crf(x, att_matrix)
            crf_embeddings.append(crf_x_attention)

        # 5. Pool các head
        crf_x = myPool(self.pool_type, crf_embeddings)

        # 6. Classifier
        crf_output = F.elu(self.linear(crf_x))
        crf_output = F.softmax(crf_output, dim=1)

        # 7. Nếu cần attention thì trả thêm attention_stack
        if return_attention:
            attention_stack = torch.stack(attention_list, dim=0)
            return crf_output, attention_stack

        return crf_output


class FocalLoss(nn.Module):
    def __init__(self, weight=None, reduction="mean", gamma=0, eps=1e-7):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.eps   = eps
        self.ce    = torch.nn.CrossEntropyLoss(weight=weight, reduction=reduction)

    def forward(self, input, target):
        logp = self.ce(input, target)
        p    = torch.exp(-logp)
        loss = (1 - p) ** self.gamma * logp
        return loss.mean()
'''

with open("/content/ACRF-RNN/Code/model_attention.py", "w", encoding="utf-8") as f:
    f.write(model_attention_code)

print("Đã tạo /content/ACRF-RNN/Code/model_attention.py")
!wc -l /content/ACRF-RNN/Code/model_attention.py
!head -30 /content/ACRF-RNN/Code/model_attention.py

Đã tạo /content/ACRF-RNN/Code/model_attention.py
102 /content/ACRF-RNN/Code/model_attention.py

from layer import *
from torch import nn
import torch
import torch.nn.functional as F


class AC_RNN(nn.Module):
    def __init__(self, num_company, d_feature, d_hidden, hidn_rnn,
                 heads_att, hidn_att, crf_iters, alpha, pool_type):
        super(AC_RNN, self).__init__()

        self.heads_att   = heads_att
        self.alpha       = alpha
        self.num_company = num_company
        self.d_feature   = d_feature
        self.d_hidden    = d_hidden
        self.hidden_rnn  = hidn_rnn
        self.hidn_att    = hidn_att

        self.GRUs = GRUModel(d_feature, hidn_rnn)

        self.attentions = nn.ModuleList([
            Attention(
                hidn_rnn,
                hidn_att,
                num_company=self.num_company,
                alpha=self.alpha
            )
            for _ in range(heads_att)

### 5.2.2 Chuẩn bị export attention weights từ dữ liệu thật

Sau khi `model_attention.py` đã trả được `attention_stack`, tiếp theo là chạy model trên dữ liệu thật `processed_flat.json`.

Mục tiêu của bước này:

1. Đọc dữ liệu thật đã xử lý.
2. Kiểm tra shape của `x`, `y`, `years`.
3. Xác định số công ty, số năm, số feature.
4. Kiểm tra checkpoint model đã train.
5. Sau đó mới export `attention_weights.csv`.

Lưu ý: Attention graph phải được lấy từ model đã train. Nếu chưa load checkpoint, attention chỉ là trọng số ngẫu nhiên và chưa có ý nghĩa phân tích.

In [91]:
# Load processed_flat.json và tách x_np, y_np theo format main_py_compatible_year_major

import os
import json
import numpy as np
import pandas as pd
import torch

PROJECT_DATA_PATH = "/content/project_data/processed_flat.json"
CODE_DIR = "/content/ACRF-RNN/Code"
ATTENTION_OUTPUT_DIR = "/content/project_outputs/attention_graph"

os.makedirs(ATTENTION_OUTPUT_DIR, exist_ok=True)

with open(PROJECT_DATA_PATH, "r", encoding="utf-8") as f:
    flat_data = json.load(f)

assert flat_data["format"] == "main_py_compatible_year_major"

data_items = flat_data["data"]
columns = flat_data["columns"]

years = []
all_rows = []
all_symbols = []

for item in data_items:
    years.append(int(item["year"]))
    all_symbols.append(item["symbols"])
    all_rows.append(np.array(item["rows"], dtype=np.float32))

raw_np = np.stack(all_rows, axis=0)

label_col = "label"
label_idx = columns.index(label_col)

y_np = raw_np[:, :, label_idx].astype(np.int64)

feature_indices = [i for i in range(len(columns)) if i != label_idx]
x_np = raw_np[:, :, feature_indices].astype(np.float32)
feature_columns = [columns[i] for i in feature_indices]

num_years = x_np.shape[0]
num_company = x_np.shape[1]
d_feature = x_np.shape[2]

print("raw_np shape:", raw_np.shape)
print("x_np shape:", x_np.shape)
print("y_np shape:", y_np.shape)
print("years:", years)
print("Label values:", np.unique(y_np))
print("num feature columns:", len(feature_columns))

assert num_years == 10
assert num_company == 491
assert d_feature == 208
assert set(np.unique(y_np)).issubset({0, 1})

print("Dữ liệu thật hợp lệ để chuẩn bị export attention.")

raw_np shape: (10, 491, 209)
x_np shape: (10, 491, 208)
y_np shape: (10, 491)
years: [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Label values: [0 1]
num feature columns: 208
Dữ liệu thật hợp lệ để chuẩn bị export attention.

In [92]:
import glob
import os

checkpoint_candidates = []

search_dirs = [
    "/content/ACRF-RNN",
    "/content/ACRF-RNN/Code",
    "/content/project_outputs",
    "/content/project_outputs/checkpoints",
    "/content/drive/MyDrive",
]

patterns = ["*.pt", "*.pth", "*.ckpt", "*.pkl"]

for d in search_dirs:
    if os.path.exists(d):
        for p in patterns:
            checkpoint_candidates.extend(
                glob.glob(os.path.join(d, "**", p), recursive=True)
            )

checkpoint_candidates = sorted(set(checkpoint_candidates))

print("Found checkpoint candidates:")
for i, ckpt in enumerate(checkpoint_candidates[:50]):
    print(i, ckpt)

print("Total checkpoints found:", len(checkpoint_candidates))

Found checkpoint candidates:
0 /content/project_outputs/checkpoints/vera_best_test_year_2018.pt
Total checkpoints found: 1

### 5.2.3 Tạo `main_vera_ckpt.py` để lưu checkpoint model

Hiện tại `main_vera.py` chỉ train và in log, chưa lưu trọng số model.  
Để trích xuất Attention Graph có ý nghĩa, cần lấy attention từ model đã train, không lấy từ model random.

Ta tạo thêm file `main_vera_ckpt.py` dựa trên `main_vera.py` cũ.  
Logic train/evaluation của VerA được giữ nguyên, chỉ bổ sung thao tác lưu checkpoint tại epoch có `train_loss` tốt nhất.

Checkpoint sau khi train sẽ được lưu vào:

```text
/content/project_outputs/checkpoints/vera_best_test_year_2018.pt
/content/project_outputs/checkpoints/vera_best_test_year_2019.pt
/content/project_outputs/checkpoints/vera_best_test_year_2020.pt
```

In [112]:
# Tạo main_vera_ckpt.py từ main_vera.py và bổ sung lưu checkpoint

import os

MAIN_VERA_PATH = "/content/ACRF-RNN/Code/main_vera.py"
MAIN_VERA_CKPT_PATH = "/content/ACRF-RNN/Code/main_vera_ckpt.py"

assert os.path.exists(MAIN_VERA_PATH), f"Không tìm thấy {MAIN_VERA_PATH}"

with open(MAIN_VERA_PATH, "r", encoding="utf-8") as f:
    code = f.read()

# 1. Thêm argument checkpoint directory nếu chưa có
old_arg = 'parser.add_argument("--dropout",     type=float, default=0.0)'
new_arg = '''parser.add_argument("--dropout",     type=float, default=0.0)
parser.add_argument("--ckpt-dir",    type=str,   default="/content/project_outputs/checkpoints")'''

if '--ckpt-dir' not in code:
    if old_arg not in code:
        raise ValueError("Không tìm thấy vị trí parser.add_argument('--dropout', ...) để chèn --ckpt-dir")
    code = code.replace(old_arg, new_arg)

# 2. Tạo thư mục checkpoint sau khi parse args
old_parse = '''args        = parser.parse_args()
rnn_len     = args.rnn_length'''

new_parse = '''args        = parser.parse_args()
os.makedirs(args.ckpt_dir, exist_ok=True)

rnn_len     = args.rnn_length'''

if 'os.makedirs(args.ckpt_dir, exist_ok=True)' not in code:
    if old_parse not in code:
        raise ValueError("Không tìm thấy vị trí parse_args để chèn os.makedirs(args.ckpt_dir, exist_ok=True)")
    code = code.replace(old_parse, new_parse)

# 3. Thêm đường dẫn checkpoint sau khi tạo optimizer
old_optimizer = '''optimizer = optim.Adam(model.parameters(), lr=args.lr)
    print(f"Model params: {sum(p.numel() for p in model.parameters()):,}\\\\n")'''

new_optimizer = '''optimizer = optim.Adam(model.parameters(), lr=args.lr)
    ckpt_path = os.path.join(args.ckpt_dir, f"vera_best_test_year_{test_year}.pt")
    print(f"Model params: {sum(p.numel() for p in model.parameters()):,}\\\\n")
    print(f"Checkpoint will be saved to: {ckpt_path}\\\\n")'''

if 'ckpt_path = os.path.join(args.ckpt_dir' not in code:
    if old_optimizer not in code:
        raise ValueError("Không tìm thấy vị trí optimizer để chèn ckpt_path")
    code = code.replace(old_optimizer, new_optimizer)

# 4. Khi gặp best train_loss thì lưu checkpoint
old_best_block = '''if tr_loss < loss_min:
            loss_min   = tr_loss
            best_epoch = epoch
            best_m     = ev
            wait_count = 0
            is_best    = "best"'''

new_best_block = '''if tr_loss < loss_min:
            loss_min   = tr_loss
            best_epoch = epoch
            best_m     = ev
            wait_count = 0
            is_best    = "best"

            torch.save({
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "test_year": test_year,
                "best_epoch": best_epoch,
                "best_train_loss": loss_min,
                "best_eval_metrics": best_m,
                "args": vars(args),
                "num_company": num_company,
                "d_feature": d_feature
            }, ckpt_path)'''

if '"model_state_dict": model.state_dict()' not in code:
    if old_best_block not in code:
        raise ValueError("Không tìm thấy block if tr_loss < loss_min để chèn torch.save")
    code = code.replace(old_best_block, new_best_block)

with open(MAIN_VERA_CKPT_PATH, "w", encoding="utf-8") as f:
    f.write(code)

print("Đã tạo:", MAIN_VERA_CKPT_PATH)
print("Kiểm tra các dòng checkpoint:")
!grep -n "ckpt\\|torch.save\\|model_state_dict" /content/ACRF-RNN/Code/main_vera_ckpt.py | head -30

Đã tạo: /content/ACRF-RNN/Code/main_vera_ckpt.py
Kiểm tra các dòng checkpoint:
31:parser.add_argument("--ckpt-dir",    type=str,   default="/content/project_outputs/checkpoints")
35:os.makedirs(args.ckpt_dir, exist_ok=True)
170:    ckpt_path = os.path.join(args.ckpt_dir, f"vera_best_test_year_{test_year}.pt")
172:    print(f"Checkpoint will be saved to: {ckpt_path}\\n")
199:            torch.save({
200:                "model_state_dict": model.state_dict(),
209:            }, ckpt_path)

In [113]:
# Chạy train để tạo checkpoint cho 2018, 2019, 2020

import os
import subprocess
from pathlib import Path

TEST_YEARS = [2018, 2019, 2020]
CKPT_DIR = "/content/project_outputs/checkpoints"
LOG_DIR = "/content/project_outputs"

os.makedirs(CKPT_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

# Nếu muốn train lại từ đầu và ghi đè checkpoint cũ, đổi thành True
FORCE_RETRAIN = True

for year in TEST_YEARS:
    ckpt_path = f"{CKPT_DIR}/vera_best_test_year_{year}.pt"
    log_path = f"{LOG_DIR}/run_vera_ckpt_{year}.log"

    if os.path.exists(ckpt_path) and not FORCE_RETRAIN:
        print(f"[SKIP] Đã có checkpoint {year}: {ckpt_path}")
        continue

    print("=" * 80)
    print(f"TRAIN CHECKPOINT FOR TEST_YEAR = {year}")
    print("=" * 80)

    cmd = [
        "python", "main_vera_ckpt.py",
        "--data-path", "/content/project_data/processed_flat.json",
        "--test-year", str(year),
        "--max-epoch", "800",
        "--wait-epoch", "150",
        "--device", "0",
        "--ckpt-dir", CKPT_DIR
    ]

    with open(log_path, "w", encoding="utf-8") as log_f:
        process = subprocess.Popen(
            cmd,
            cwd="/content/ACRF-RNN/Code",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )

        for line in process.stdout:
            print(line, end="")
            log_f.write(line)

        return_code = process.wait()

    if return_code != 0:
        raise RuntimeError(f"Train checkpoint năm {year} bị lỗi. Xem log: {log_path}")

    print(f"Đã train xong năm {year}. Log: {log_path}")

================================================================================
TRAIN CHECKPOINT FOR TEST_YEAR = 2018
================================================================================
\nACRF-RNN VerA | test_year=2018 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017] (7 years)
Eval  : [2012, 2013, 2014, 2015, 2017, 2018]
Train labels: fraud=860, benign=2577
Model params: 972,937\n
Checkpoint will be saved to: /content/project_outputs/checkpoints/vera_best_test_year_2018.pt\n
  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
   0 |  0.4153 | 0.5580 | 0.4725 | 0.4469 | 0.1063 | 0.4437 | best
  --> [  0.1%] ep 1/800 | elapsed 0s | ETA 368s | best loss 0.4153 @ ep0 | wait 0/150
   1 |  0.4404 | 0.5204 | 0.5214 | 0.4926 | 0.0147 | 0.4890 |
   2 |  0.4085 | 0.4939 | 0.5356 | 0.5048 | 0.0096 | 0.5008 | best
  --> [  0.4%] ep 3/800 | elapsed 1s | ETA 151s | best loss 0.4085 @ ep2 | wait 0/150
   3 |  0.3919 | 0.5458 | 0.5743 | 0.5335 | 0.0670 | 0.5267 | best
  --> [  0.5%] ep 4/800 | elapsed 1s | ETA 125s | best loss 0.3919 @ ep3 | wait 0/150
   4 |  0.2982 | 0.6527 | 0.5927 | 0.5458 | 0.0917 | 0.5371 | best
  --> [  0.6%] ep 5/800 | elapsed 1s | ETA 110s | best loss 0.2982 @ ep4 | wait 0/150
   5 |  0.2488 | 0.7251 | 0.6395 | 0.5902 | 0.1805 | 0.5814 | best
  --> [  0.8%] ep 6/800 | elapsed 1s | ETA 102s | best loss 0.2488 @ ep5 | wait 0/150
   6 |  0.2280 | 0.7648 | 0.6864 | 0.6449 | 0.2898 | 0.6392 | best
  --> [  0.9%] ep 7/800 | elapsed 1s | ETA 94s | best loss 0.2280 @ ep6 | wait 0/150
   7 |  0.4240 | 0.5081 | 0.6904 | 0.6605 | 0.3210 | 0.6576 |
   8 |  0.1798 | 0.8513 | 0.3442 | 0.3603 | 0.2794 | 0.3588 | best
  --> [  1.1%] ep 9/800 | elapsed 1s | ETA 83s | best loss 0.1798 @ ep8 | wait 0/150
   9 |  0.1651 | 0.8554 | 0.6660 | 0.6542 | 0.3085 | 0.6538 | best
  --> [  1.2%] ep 10/800 | elapsed 1s | ETA 79s | best loss 0.1651 @ ep9 | wait 0/150
  10 |  0.1581 | 0.8564 | 0.6782 | 0.6574 | 0.3147 | 0.6559 | best
  --> [  1.4%] ep 11/800 | elapsed 1s | ETA 76s | best loss 0.1581 @ ep10 | wait 0/150
  11 |  0.1521 | 0.8686 | 0.6802 | 0.6510 | 0.3021 | 0.6482 | best
  --> [  1.5%] ep 12/800 | elapsed 1s | ETA 74s | best loss 0.1521 @ ep11 | wait 0/150
  12 |  0.1458 | 0.8778 | 0.7026 | 0.6662 | 0.3323 | 0.6619 | best
  --> [  1.6%] ep 13/800 | elapsed 1s | ETA 71s | best loss 0.1458 @ ep12 | wait 0/150
  13 |  0.1410 | 0.8900 | 0.7291 | 0.6840 | 0.3680 | 0.6776 | best
  --> [  1.8%] ep 14/800 | elapsed 1s | ETA 70s | best loss 0.1410 @ ep13 | wait 0/150
  14 |  0.1367 | 0.9063 | 0.7271 | 0.6826 | 0.3653 | 0.6764 | best
  --> [  1.9%] ep 15/800 | elapsed 1s | ETA 69s | best loss 0.1367 @ ep14 | wait 0/150
  15 |  0.1313 | 0.9104 | 0.7352 | 0.6856 | 0.3711 | 0.6778 | best
  --> [  2.0%] ep 16/800 | elapsed 1s | ETA 68s | best loss 0.1313 @ ep15 | wait 0/150
  16 |  0.1273 | 0.9287 | 0.7393 | 0.6858 | 0.3715 | 0.6767 | best
  --> [  2.1%] ep 17/800 | elapsed 1s | ETA 67s | best loss 0.1273 @ ep16 | wait 0/150
  17 |  0.1221 | 0.9348 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  --> [  2.2%] ep 18/800 | elapsed 2s | ETA 67s | best loss 0.1221 @ ep17 | wait 0/150
  18 |  0.1168 | 0.9409 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  --> [  2.4%] ep 19/800 | elapsed 2s | ETA 66s | best loss 0.1168 @ ep18 | wait 0/150
  19 |  0.1084 | 0.9511 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  --> [  2.5%] ep 20/800 | elapsed 2s | ETA 66s | best loss 0.1084 @ ep19 | wait 0/150
  20 |  0.1020 | 0.9542 | 0.7454 | 0.6899 | 0.3797 | 0.6802 | best
  --> [  2.6%] ep 21/800 | elapsed 2s | ETA 66s | best loss 0.1020 @ ep20 | wait 0/150
  21 |  0.3562 | 0.6415 | 0.7495 | 0.6926 | 0.3852 | 0.6825 |
  22 |  0.0980 | 0.9684 | 0.7536 | 0.6954 | 0.3907 | 0.6848 | best
  --> [  2.9%] ep 23/800 | elapsed 2s | ETA 63s | best loss 0.0980 @ ep22 | wait 0/150
  23 |  0.1016 | 0.9603 | 0.7597 | 0.6969 | 0.3939 | 0.6847 |
  24 |  0.4615 | 0.5295 | 0.7576 | 0.6981 | 0.3962 | 0.6871 |
  25 |  0.3598 | 0.6273 | 0.7719 | 0.7052 | 0.4103 | 0.6915 |
  26 |  0.4181 | 0.5672 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  27 |  0.1793 | 0.8666 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  28 |  0.1804 | 0.8595 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
  29 |  0.1804 | 0.8585 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  --> [  3.8%] ep 30/800 | elapsed 2s | ETA 56s | best loss 0.0980 @ ep22 | wait 7/150
  30 |  0.1800 | 0.8605 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  31 |  0.1794 | 0.8595 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  32 |  0.1792 | 0.8574 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  33 |  0.1788 | 0.8585 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  34 |  0.1788 | 0.8585 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  35 |  0.1786 | 0.8574 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  36 |  0.1785 | 0.8574 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
  37 |  0.1781 | 0.8595 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  38 |  0.1785 | 0.8595 | 0.2933 | 0.3362 | 0.3276 | 0.3242 |
  39 |  0.1782 | 0.8625 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  --> [  5.0%] ep 40/800 | elapsed 3s | ETA 50s | best loss 0.0980 @ ep22 | wait 17/150
  40 |  0.1784 | 0.8625 | 0.7719 | 0.7052 | 0.4103 | 0.6915 |
  41 |  0.1782 | 0.8605 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  42 |  0.1785 | 0.8585 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  43 |  0.1781 | 0.8595 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  44 |  0.1779 | 0.8625 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  45 |  0.1834 | 0.8554 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  46 |  0.1781 | 0.8595 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  47 |  0.1839 | 0.8523 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  48 |  0.1775 | 0.8635 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  49 |  0.1781 | 0.8605 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  --> [  6.2%] ep 50/800 | elapsed 3s | ETA 46s | best loss 0.0980 @ ep22 | wait 27/150
  50 |  0.1799 | 0.8574 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  51 |  0.1782 | 0.8635 | 0.2933 | 0.3516 | 0.2968 | 0.3302 |
  52 |  0.1773 | 0.8625 | 0.7699 | 0.7038 | 0.4076 | 0.6904 |
  53 |  0.1769 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  54 |  0.1833 | 0.8523 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  55 |  0.1798 | 0.8595 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  56 |  0.1770 | 0.8625 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  57 |  0.1767 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  58 |  0.1902 | 0.8462 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  59 |  0.1763 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  --> [  7.5%] ep 60/800 | elapsed 4s | ETA 43s | best loss 0.0980 @ ep22 | wait 37/150
  60 |  0.1758 | 0.8666 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  61 |  0.1753 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  62 |  0.1762 | 0.8697 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  63 |  0.1732 | 0.8758 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  64 |  0.1760 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  65 |  0.1754 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  66 |  0.1751 | 0.8727 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  67 |  0.1749 | 0.8676 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  68 |  0.1742 | 0.8585 | 0.7699 | 0.7038 | 0.4076 | 0.6904 |
  69 |  0.3350 | 0.6670 | 0.7637 | 0.6971 | 0.3942 | 0.6833 |
  --> [  8.8%] ep 70/800 | elapsed 4s | ETA 41s | best loss 0.0980 @ ep22 | wait 47/150
  70 |  0.3149 | 0.6955 | 0.7515 | 0.6889 | 0.3777 | 0.6765 |
  71 |  0.4204 | 0.5367 | 0.7760 | 0.7130 | 0.4261 | 0.7010 |
  72 |  0.1769 | 0.8666 | 0.7739 | 0.7065 | 0.4131 | 0.6926 |
  73 |  0.1824 | 0.8534 | 0.7739 | 0.7065 | 0.4131 | 0.6926 |
  74 |  0.1730 | 0.8727 | 0.7800 | 0.7132 | 0.4265 | 0.6997 |
  75 |  0.1719 | 0.8717 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  76 |  0.1714 | 0.8697 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  77 |  0.1722 | 0.8717 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  78 |  0.1735 | 0.8686 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  79 |  0.2454 | 0.7811 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  --> [ 10.0%] ep 80/800 | elapsed 4s | ETA 40s | best loss 0.0980 @ ep22 | wait 57/150
  80 |  0.2966 | 0.7138 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  81 |  0.2083 | 0.8177 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  82 |  0.2160 | 0.8096 | 0.6334 | 0.6169 | 0.2338 | 0.6159 |
  83 |  0.2712 | 0.7434 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  84 |  0.3204 | 0.6823 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  85 |  0.3424 | 0.6589 | 0.7800 | 0.7132 | 0.4265 | 0.6997 |
  86 |  0.1935 | 0.8279 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  87 |  0.3677 | 0.6334 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  88 |  0.3827 | 0.6161 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  89 |  0.3852 | 0.6161 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  --> [ 11.2%] ep 90/800 | elapsed 5s | ETA 39s | best loss 0.0980 @ ep22 | wait 67/150
  90 |  0.1887 | 0.8483 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  91 |  0.1809 | 0.8595 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  92 |  0.1807 | 0.8605 | 0.2729 | 0.3276 | 0.3448 | 0.3074 |
  93 |  0.1687 | 0.8737 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  94 |  0.1771 | 0.8615 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  95 |  0.1750 | 0.8635 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  96 |  0.1716 | 0.8646 | 0.7719 | 0.7077 | 0.4155 | 0.6951 |
  97 |  0.1689 | 0.8666 | 0.7658 | 0.7036 | 0.4072 | 0.6917 |
  98 |  0.1672 | 0.8646 | 0.7658 | 0.7010 | 0.4021 | 0.6881 |
  99 |  0.1657 | 0.8666 | 0.7637 | 0.7022 | 0.4045 | 0.6906 |
  --> [ 12.5%] ep 100/800 | elapsed 5s | ETA 37s | best loss 0.0980 @ ep22 | wait 77/150
 100 |  0.1630 | 0.8717 | 0.7556 | 0.6942 | 0.3884 | 0.6824 |
 101 |  0.1616 | 0.8717 | 0.7515 | 0.6914 | 0.3829 | 0.6801 |
 102 |  0.1608 | 0.8768 | 0.7495 | 0.6926 | 0.3852 | 0.6825 |
 103 |  0.1577 | 0.8798 | 0.7475 | 0.6912 | 0.3825 | 0.6814 |
 104 |  0.1567 | 0.8788 | 0.7454 | 0.6950 | 0.3900 | 0.6871 |
 105 |  0.1541 | 0.8768 | 0.7434 | 0.6936 | 0.3873 | 0.6859 |
 106 |  0.1517 | 0.8839 | 0.7413 | 0.6923 | 0.3845 | 0.6847 |
 107 |  0.1484 | 0.8890 | 0.7373 | 0.6869 | 0.3739 | 0.6790 |
 108 |  0.1477 | 0.8880 | 0.7393 | 0.6909 | 0.3818 | 0.6836 |
 109 |  0.1449 | 0.8971 | 0.7454 | 0.7027 | 0.4054 | 0.6971 |
  --> [ 13.8%] ep 110/800 | elapsed 6s | ETA 36s | best loss 0.0980 @ ep22 | wait 87/150
 110 |  0.1427 | 0.8992 | 0.7454 | 0.7027 | 0.4054 | 0.6971 |
 111 |  0.1389 | 0.9053 | 0.7413 | 0.6974 | 0.3948 | 0.6914 |
 112 |  0.1351 | 0.9084 | 0.7454 | 0.7053 | 0.4105 | 0.7003 |
 113 |  0.1333 | 0.9063 | 0.7495 | 0.7106 | 0.4211 | 0.7060 |
 114 |  0.1291 | 0.9124 | 0.7475 | 0.7092 | 0.4184 | 0.7047 |
 115 |  0.1358 | 0.9033 | 0.7475 | 0.7092 | 0.4184 | 0.7047 |
 116 |  0.1276 | 0.9134 | 0.7454 | 0.7053 | 0.4105 | 0.7003 |
 117 |  0.1260 | 0.9206 | 0.7393 | 0.7011 | 0.4023 | 0.6967 |
 118 |  0.1245 | 0.9196 | 0.7352 | 0.6984 | 0.3968 | 0.6942 |
 119 |  0.1212 | 0.9206 | 0.7312 | 0.6931 | 0.3862 | 0.6886 |
  --> [ 15.0%] ep 120/800 | elapsed 6s | ETA 36s | best loss 0.0980 @ ep22 | wait 97/150
 120 |  0.1195 | 0.9246 | 0.7312 | 0.6931 | 0.3862 | 0.6886 |
 121 |  0.1170 | 0.9267 | 0.7291 | 0.6891 | 0.3783 | 0.6841 |
 122 |  0.1132 | 0.9348 | 0.7475 | 0.6861 | 0.3722 | 0.6743 |
 123 |  0.1094 | 0.9409 | 0.7312 | 0.6905 | 0.3810 | 0.6854 |
 124 |  0.1115 | 0.9379 | 0.7332 | 0.6893 | 0.3786 | 0.6833 |
 125 |  0.1060 | 0.9491 | 0.7291 | 0.6866 | 0.3732 | 0.6809 |
 126 |  0.1081 | 0.9460 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
 127 |  0.1081 | 0.9470 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
 128 |  0.1078 | 0.9491 | 0.7434 | 0.6911 | 0.3821 | 0.6825 |
 129 |  0.1068 | 0.9521 | 0.7475 | 0.6938 | 0.3876 | 0.6849 |
  --> [ 16.2%] ep 130/800 | elapsed 7s | ETA 36s | best loss 0.0980 @ ep22 | wait 107/150
 130 |  0.1052 | 0.9582 | 0.7495 | 0.6952 | 0.3904 | 0.6860 |
 131 |  0.1174 | 0.9379 | 0.7576 | 0.7007 | 0.4014 | 0.6907 |
 132 |  0.1019 | 0.9684 | 0.7454 | 0.6924 | 0.3849 | 0.6837 |
 133 |  0.1002 | 0.9715 | 0.7637 | 0.7022 | 0.4045 | 0.6906 |
 134 |  0.0995 | 0.9735 | 0.7556 | 0.6942 | 0.3884 | 0.6824 |
 135 |  0.0988 | 0.9745 | 0.7576 | 0.6981 | 0.3962 | 0.6871 |
 136 |  0.1001 | 0.9745 | 0.2566 | 0.3115 | 0.3770 | 0.2900 |
 137 |  0.3926 | 0.6029 | 0.7699 | 0.7064 | 0.4127 | 0.6940 |
 138 |  0.1029 | 0.9857 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
 139 |  0.1115 | 0.9745 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  --> [ 17.5%] ep 140/800 | elapsed 8s | ETA 36s | best loss 0.0980 @ ep22 | wait 117/150
 140 |  0.1133 | 0.9817 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
 141 |  0.2673 | 0.6670 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
 142 |  0.3024 | 0.7057 | 0.7047 | 0.6752 | 0.3504 | 0.6725 |
 143 |  0.1335 | 0.9532 | 0.7556 | 0.6891 | 0.3781 | 0.6751 |
 144 |  0.1671 | 0.8870 | 0.7332 | 0.6816 | 0.3633 | 0.6732 |
 145 |  0.2240 | 0.7780 | 0.6395 | 0.6287 | 0.2574 | 0.6283 |
 146 |  0.2808 | 0.6436 | 0.4990 | 0.5057 | 0.0114 | 0.5055 |
 147 |  0.4426 | 0.3910 | 0.7088 | 0.6651 | 0.3303 | 0.6590 |
 148 |  0.4054 | 0.4430 | 0.4501 | 0.4369 | 0.1263 | 0.4360 |
 149 |  0.3934 | 0.4766 | 0.4644 | 0.4439 | 0.1122 | 0.4419 |
  --> [ 18.8%] ep 150/800 | elapsed 8s | ETA 36s | best loss 0.0980 @ ep22 | wait 127/150
 150 |  0.3628 | 0.5377 | 0.4766 | 0.4599 | 0.0803 | 0.4585 |
 151 |  0.3525 | 0.5560 | 0.7393 | 0.6858 | 0.3715 | 0.6767 |
 152 |  0.1806 | 0.8585 | 0.7800 | 0.7081 | 0.4162 | 0.6922 |
 153 |  0.4816 | 0.4674 | 0.5234 | 0.5094 | 0.0188 | 0.5086 |
 154 |  0.7534 | 0.1609 | 0.2831 | 0.3319 | 0.3362 | 0.3161 |
 155 |  0.4613 | 0.3666 | 0.4297 | 0.4231 | 0.1537 | 0.4229 |
 156 |  0.3840 | 0.4980 | 0.4684 | 0.4569 | 0.0862 | 0.4563 |
 157 |  0.3233 | 0.5550 | 0.4868 | 0.4693 | 0.0614 | 0.4679 |
 158 |  0.2861 | 0.6100 | 0.5255 | 0.4954 | 0.0092 | 0.4914 |
 159 |  0.2654 | 0.6609 | 0.5540 | 0.5069 | 0.0138 | 0.4975 |
  --> [ 20.0%] ep 160/800 | elapsed 9s | ETA 35s | best loss 0.0980 @ ep22 | wait 137/150
 160 |  0.2503 | 0.7077 | 0.5784 | 0.5337 | 0.0673 | 0.5255 |
 161 |  0.2386 | 0.7485 | 0.6069 | 0.5555 | 0.1109 | 0.5451 |
 162 |  0.2274 | 0.7841 | 0.6273 | 0.5743 | 0.1486 | 0.5637 |
 163 |  0.2176 | 0.8147 | 0.6477 | 0.5932 | 0.1864 | 0.5823 |
 164 |  0.2089 | 0.8371 | 0.6538 | 0.5973 | 0.1946 | 0.5857 |
 165 |  0.2022 | 0.8503 | 0.6680 | 0.6044 | 0.2087 | 0.5898 |
 166 |  0.1954 | 0.8554 | 0.6802 | 0.6152 | 0.2303 | 0.6002 |
 167 |  0.1883 | 0.8717 | 0.6904 | 0.6246 | 0.2492 | 0.6095 |
 168 |  0.1817 | 0.8809 | 0.6986 | 0.6352 | 0.2704 | 0.6215 |
 169 |  0.1779 | 0.8890 | 0.6965 | 0.6313 | 0.2625 | 0.6166 |
  --> [ 21.2%] ep 170/800 | elapsed 9s | ETA 35s | best loss 0.0980 @ ep22 | wait 147/150
 170 |  0.1747 | 0.8900 | 0.6986 | 0.6301 | 0.2602 | 0.6139 |
 171 |  0.1704 | 0.8961 | 0.7067 | 0.6381 | 0.2763 | 0.6221 |
 172 |  0.1657 | 0.9094 | 0.7149 | 0.6462 | 0.2924 | 0.6303 |
\nEarly stop @ epoch 172  (best_epoch=22)
\n============================================================
KET QUA VerA -- test_year=2018
============================================================
Best epoch (by train_loss): 22
Best train_loss           : 0.0980
Metric         Paper    VerA    Diff
----------------------------------------
Accuracy       77.60   75.36  -2.24
Recall_m       70.79   69.54  -1.25
KS             41.58   39.07  -2.51
G-mean         69.37   68.48  -0.89
Đã train xong năm 2018. Log: /content/project_outputs/run_vera_ckpt_2018.log
================================================================================
TRAIN CHECKPOINT FOR TEST_YEAR = 2019
================================================================================
\nACRF-RNN VerA | test_year=2019 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018] (8 years)
Eval  : [2013, 2014, 2015, 2017, 2018, 2019]
Train labels: fraud=987, benign=2941
Model params: 972,937\n
Checkpoint will be saved to: /content/project_outputs/checkpoints/vera_best_test_year_2019.pt\n
  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
   0 |  0.4150 | 0.5553 | 0.5621 | 0.5400 | 0.0801 | 0.5385 | best
  --> [  0.1%] ep 1/800 | elapsed 0s | ETA 396s | best loss 0.4150 @ ep0 | wait 0/150
   1 |  0.3941 | 0.4956 | 0.5153 | 0.5034 | 0.0068 | 0.5029 | best
  --> [  0.2%] ep 2/800 | elapsed 1s | ETA 235s | best loss 0.3941 @ ep1 | wait 0/150
   2 |  0.3786 | 0.5485 | 0.6191 | 0.5929 | 0.1859 | 0.5910 | best
  --> [  0.4%] ep 3/800 | elapsed 1s | ETA 179s | best loss 0.3786 @ ep2 | wait 0/150
   3 |  0.3260 | 0.6144 | 0.5682 | 0.5860 | 0.1720 | 0.5851 | best
  --> [  0.5%] ep 4/800 | elapsed 1s | ETA 155s | best loss 0.3260 @ ep3 | wait 0/150
   4 |  0.2711 | 0.6979 | 0.7128 | 0.6792 | 0.3583 | 0.6764 | best
  --> [  0.6%] ep 5/800 | elapsed 1s | ETA 137s | best loss 0.2711 @ ep4 | wait 0/150
   5 |  0.2395 | 0.7502 | 0.7413 | 0.6975 | 0.3951 | 0.6930 | best
  --> [  0.8%] ep 6/800 | elapsed 1s | ETA 125s | best loss 0.2395 @ ep5 | wait 0/150
   6 |  0.2115 | 0.8018 | 0.7597 | 0.6964 | 0.3928 | 0.6869 | best
  --> [  0.9%] ep 7/800 | elapsed 1s | ETA 116s | best loss 0.2115 @ ep6 | wait 0/150
   7 |  0.1921 | 0.8371 | 0.7475 | 0.6821 | 0.3642 | 0.6717 | best
  --> [  1.0%] ep 8/800 | elapsed 1s | ETA 109s | best loss 0.1921 @ ep7 | wait 0/150
   8 |  0.1820 | 0.8500 | 0.7454 | 0.6808 | 0.3615 | 0.6706 | best
  --> [  1.1%] ep 9/800 | elapsed 1s | ETA 103s | best loss 0.1820 @ ep8 | wait 0/150
   9 |  0.3537 | 0.6402 | 0.7454 | 0.6872 | 0.3745 | 0.6791 |
  --> [  1.2%] ep 10/800 | elapsed 1s | ETA 98s | best loss 0.1820 @ ep8 | wait 1/150
  10 |  0.1972 | 0.8215 | 0.7230 | 0.6599 | 0.3197 | 0.6499 |
  11 |  0.1700 | 0.8527 | 0.6538 | 0.5635 | 0.1270 | 0.5393 | best
  --> [  1.5%] ep 12/800 | elapsed 1s | ETA 91s | best loss 0.1700 @ ep11 | wait 0/150
  12 |  0.1681 | 0.8574 | 0.7189 | 0.6508 | 0.3016 | 0.6389 | best
  --> [  1.6%] ep 13/800 | elapsed 1s | ETA 88s | best loss 0.1681 @ ep12 | wait 0/150
  13 |  0.1648 | 0.8642 | 0.7454 | 0.6808 | 0.3615 | 0.6706 | best
  --> [  1.8%] ep 14/800 | elapsed 2s | ETA 86s | best loss 0.1648 @ ep13 | wait 0/150
  14 |  0.1548 | 0.8866 | 0.7536 | 0.6893 | 0.3785 | 0.6793 | best
  --> [  1.9%] ep 15/800 | elapsed 2s | ETA 85s | best loss 0.1548 @ ep14 | wait 0/150
  15 |  0.1513 | 0.8968 | 0.7658 | 0.7068 | 0.4136 | 0.6987 | best
  --> [  2.0%] ep 16/800 | elapsed 2s | ETA 84s | best loss 0.1513 @ ep15 | wait 0/150
  16 |  0.1462 | 0.9104 | 0.7780 | 0.7212 | 0.4423 | 0.7138 | best
  --> [  2.1%] ep 17/800 | elapsed 2s | ETA 83s | best loss 0.1462 @ ep16 | wait 0/150
  17 |  0.1406 | 0.9280 | 0.7800 | 0.7257 | 0.4514 | 0.7190 | best
  --> [  2.2%] ep 18/800 | elapsed 2s | ETA 82s | best loss 0.1406 @ ep17 | wait 0/150
  18 |  0.1351 | 0.9314 | 0.7780 | 0.7373 | 0.4747 | 0.7336 | best
  --> [  2.4%] ep 19/800 | elapsed 2s | ETA 81s | best loss 0.1351 @ ep18 | wait 0/150
  19 |  0.1389 | 0.9185 | 0.7719 | 0.7205 | 0.4409 | 0.7144 |
  --> [  2.5%] ep 20/800 | elapsed 2s | ETA 79s | best loss 0.1351 @ ep18 | wait 1/150
  20 |  0.3471 | 0.6395 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  21 |  0.1930 | 0.8371 | 0.7760 | 0.7393 | 0.4785 | 0.7363 |
  22 |  0.1694 | 0.8697 | 0.7719 | 0.7399 | 0.4797 | 0.7376 |
  23 |  0.1334 | 0.9179 | 0.7719 | 0.7399 | 0.4797 | 0.7376 | best
  --> [  3.0%] ep 24/800 | elapsed 2s | ETA 74s | best loss 0.1334 @ ep23 | wait 0/150
  24 |  0.2991 | 0.7108 | 0.7678 | 0.7308 | 0.4615 | 0.7277 |
  25 |  0.1500 | 0.8798 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
  26 |  0.1599 | 0.8649 | 0.7678 | 0.7340 | 0.4680 | 0.7314 |
  27 |  0.1744 | 0.8418 | 0.7210 | 0.6489 | 0.2977 | 0.6356 |
  28 |  0.1835 | 0.8242 | 0.7067 | 0.6203 | 0.2405 | 0.6002 |
  29 |  0.1968 | 0.8038 | 0.7026 | 0.6176 | 0.2353 | 0.5981 |
  --> [  3.8%] ep 30/800 | elapsed 3s | ETA 69s | best loss 0.1334 @ ep23 | wait 6/150
  30 |  0.1983 | 0.8038 | 0.7067 | 0.6235 | 0.2470 | 0.6050 |
  31 |  0.1968 | 0.8072 | 0.7108 | 0.6294 | 0.2587 | 0.6118 |

In [114]:
# Kiểm tra checkpoint sau khi train

import os
import glob
import torch

TEST_YEARS = [2018, 2019, 2020]
CKPT_DIR = "/content/project_outputs/checkpoints"

ckpt_files = sorted(glob.glob(f"{CKPT_DIR}/*.pt"))

print("Checkpoint files:")
for f in ckpt_files:
    print(f, round(os.path.getsize(f) / 1024 / 1024, 2), "MB")

print("\nKiểm tra từng checkpoint:")
for year in TEST_YEARS:
    target_ckpt = f"{CKPT_DIR}/vera_best_test_year_{year}.pt"
    print("\n" + "=" * 80)
    print("target:", target_ckpt)
    print("exists:", os.path.exists(target_ckpt))

    if os.path.exists(target_ckpt):
        ckpt = torch.load(target_ckpt, map_location="cpu", weights_only=False)

        print("checkpoint keys:", ckpt.keys())
        print("test_year:", ckpt.get("test_year"))
        print("best_epoch:", ckpt.get("best_epoch"))
        print("best_train_loss:", ckpt.get("best_train_loss"))
        print("num_company:", ckpt.get("num_company"))
        print("d_feature:", ckpt.get("d_feature"))

        if "best_eval_metrics" in ckpt:
            print("best_eval_metrics:", ckpt["best_eval_metrics"])

        if "args" in ckpt:
            print("args keys:", ckpt["args"].keys())

Checkpoint files:
/content/project_outputs/checkpoints/vera_best_test_year_2018.pt 5.56 MB
/content/project_outputs/checkpoints/vera_best_test_year_2019.pt 5.56 MB
/content/project_outputs/checkpoints/vera_best_test_year_2020.pt 5.56 MB

Kiểm tra từng checkpoint:

================================================================================
target: /content/project_outputs/checkpoints/vera_best_test_year_2018.pt
exists: True
checkpoint keys: dict_keys(['model_state_dict', 'optimizer_state_dict', 'test_year', 'best_epoch', 'best_train_loss', 'best_eval_metrics', 'args', 'num_company', 'd_feature'])
test_year: 2018
best_epoch: 22
best_train_loss: 0.09797326475381851
num_company: 491
d_feature: 208
best_eval_metrics: [np.float64(0.7535641547861507), 0.6953686077701826, np.float64(0.39073721554036517), np.float64(0.6848368206879467)]
args keys: dict_keys(['data_path', 'rnn_length', 'heads_att', 'hidn_att', 'hidn_rnn', 'crf_iter', 'max_epoch', 'wait_epoch', 'device', 'alpha', 'batch_train', 'clip', 'seed', 'lr', 'gamma', 'n_weight', 'f_weight', 'pool_type', 'test_year', 'dropout', 'ckpt_dir'])

================================================================================
target: /content/project_outputs/checkpoints/vera_best_test_year_2019.pt
exists: True
checkpoint keys: dict_keys(['model_state_dict', 'optimizer_state_dict', 'test_year', 'best_epoch', 'best_train_loss', 'best_eval_metrics', 'args', 'num_company', 'd_feature'])
test_year: 2019
best_epoch: 109
best_train_loss: 0.09993206212917964
num_company: 491
d_feature: 208
best_eval_metrics: [np.float64(0.7739307535641547), 0.7379384395132427, np.float64(0.47587687902648534), np.float64(0.735051456863839)]
args keys: dict_keys(['data_path', 'rnn_length', 'heads_att', 'hidn_att', 'hidn_rnn', 'crf_iter', 'max_epoch', 'wait_epoch', 'device', 'alpha', 'batch_train', 'clip', 'seed', 'lr', 'gamma', 'n_weight', 'f_weight', 'pool_type', 'test_year', 'dropout', 'ckpt_dir'])

================================================================================
target: /content/project_outputs/checkpoints/vera_best_test_year_2020.pt
exists: True
checkpoint keys: dict_keys(['model_state_dict', 'optimizer_state_dict', 'test_year', 'best_epoch', 'best_train_loss', 'best_eval_metrics', 'args', 'num_company', 'd_feature'])
test_year: 2020
best_epoch: 228
best_train_loss: 0.08628447540104389
num_company: 491
d_feature: 208
best_eval_metrics: [np.float64(0.814663951120163), 0.7319552110249785, np.float64(0.4639104220499569), np.float64(0.7207996325261166)]
args keys: dict_keys(['data_path', 'rnn_length', 'heads_att', 'hidn_att', 'hidn_rnn', 'crf_iter', 'max_epoch', 'wait_epoch', 'device', 'alpha', 'batch_train', 'clip', 'seed', 'lr', 'gamma', 'n_weight', 'f_weight', 'pool_type', 'test_year', 'dropout', 'ckpt_dir'])

### 5.2.4 Load checkpoint vào `model_attention.py` và lấy attention theo từng năm

Sau khi đã có checkpoint cho các năm kiểm thử, bước này khởi tạo lại `AC_RNN` từ `model_attention.py`, nạp `model_state_dict`, rồi chạy model với `return_attention=True`.

Mục tiêu:
- Đảm bảo kiến trúc `model_attention.py` khớp với checkpoint.
- Lấy được `attention_stack` cho từng năm: 2018, 2019, 2020.
- Attention lấy ra là attention của model đã train, không còn là trọng số random.

In [115]:
# Load checkpoint vào model_attention.py và lấy attention_stack cho từng năm

import sys
import os
import torch

sys.path.append("/content/ACRF-RNN/Code")

from model_attention import AC_RNN

TEST_YEARS = [2018, 2019, 2020]
CKPT_DIR = "/content/project_outputs/checkpoints"

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device:", device)

pool_type_map = {
    1: "MAX",
    2: "MEAN",
    3: "SUM",
    "1": "MAX",
    "2": "MEAN",
    "3": "SUM",
    "max": "MAX",
    "mean": "MEAN",
    "avg": "MEAN",
    "sum": "SUM",
    "MAX": "MAX",
    "MEAN": "MEAN",
    "AVG": "MEAN",
    "SUM": "SUM",
}

def load_attention_model_for_year(test_year):
    ckpt_path = f"{CKPT_DIR}/vera_best_test_year_{test_year}.pt"
    assert os.path.exists(ckpt_path), f"Không tìm thấy checkpoint: {ckpt_path}"

    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    args = ckpt["args"]

    pool_type_for_model = pool_type_map.get(args["pool_type"])
    if pool_type_for_model is None:
        raise ValueError(f"pool_type không hợp lệ: {args['pool_type']}")

    model = AC_RNN(
        num_company=ckpt["num_company"],
        d_feature=ckpt["d_feature"],
        d_hidden=ckpt["d_feature"],
        hidn_rnn=args["hidn_rnn"],
        heads_att=args["heads_att"],
        hidn_att=args["hidn_att"],
        crf_iters=args["crf_iter"],
        alpha=args["alpha"],
        pool_type=pool_type_for_model
    )

    model.drop_out = args.get("dropout", 0.0)

    missing_keys, unexpected_keys = model.load_state_dict(
        ckpt["model_state_dict"],
        strict=False
    )

    if len(missing_keys) > 0 or len(unexpected_keys) > 0:
        print("missing_keys:", missing_keys)
        print("unexpected_keys:", unexpected_keys)
        raise RuntimeError(f"Checkpoint năm {test_year} không khớp model_attention.py")

    model.to(device)
    model.eval()

    return model, ckpt, args


def get_attention_for_year(test_year):
    model, ckpt, args = load_attention_model_for_year(test_year)

    test_year_idx = years.index(test_year)
    rnn_len = args["rnn_length"]

    # Giữ đúng cách đang kiểm thử: lấy window kết thúc tại test_year
    start_idx = test_year_idx - rnn_len + 1
    end_idx = test_year_idx + 1

    if start_idx < 0:
        raise ValueError(f"Không đủ dữ liệu trước test_year={test_year} để tạo window.")

    x_window_np = x_np[start_idx:end_idx]
    x_window = torch.tensor(x_window_np, dtype=torch.float32, device=device)

    with torch.no_grad():
        pred, attention_stack = model(x_window, return_attention=True)

    info = {
        "test_year": test_year,
        "test_year_idx": test_year_idx,
        "window_years": years[start_idx:end_idx],
        "rnn_len": rnn_len,
        "checkpoint_best_epoch": ckpt.get("best_epoch"),
        "checkpoint_best_train_loss": ckpt.get("best_train_loss")
    }

    return pred, attention_stack, info

device: cuda:0

In [116]:
# Test lấy attention_stack cho 2018, 2019, 2020

attention_results = {}

for year in TEST_YEARS:
    pred, attention_stack, info = get_attention_for_year(year)
    attention_results[year] = {
        "pred": pred,
        "attention_stack": attention_stack,
        "info": info
    }

    print("\n" + "=" * 80)
    print("year:", year)
    print("window years:", info["window_years"])
    print("best_epoch:", info["checkpoint_best_epoch"])
    print("best_train_loss:", info["checkpoint_best_train_loss"])
    print("pred shape:", pred.shape)
    print("attention_stack shape:", attention_stack.shape)
    print("attention min:", attention_stack.min().item())
    print("attention max:", attention_stack.max().item())
    print("attention has NaN:", torch.isnan(attention_stack).any().item())

================================================================================
year: 2018
window years: [2013, 2014, 2015, 2017, 2018]
best_epoch: 22
best_train_loss: 0.09797326475381851
pred shape: torch.Size([491, 2])
attention_stack shape: torch.Size([3, 491, 491])
attention min: -10.234393119812012
attention max: 31.490766525268555
attention has NaN: False

================================================================================
year: 2019
window years: [2014, 2015, 2017, 2018, 2019]
best_epoch: 109
best_train_loss: 0.09993206212917964
pred shape: torch.Size([491, 2])
attention_stack shape: torch.Size([3, 491, 491])
attention min: -19.91347885131836
attention max: 43.185970306396484
attention has NaN: False

================================================================================
year: 2020
window years: [2015, 2017, 2018, 2019, 2020]
best_epoch: 228
best_train_loss: 0.08628447540104389
pred shape: torch.Size([491, 2])
attention_stack shape: torch.Size([3, 491, 491])
attention min: -30.430313110351562
attention max: 52.783477783203125
attention has NaN: False

### 5.2.5 Export `attention_weights_{year}.csv`

Sau khi lấy được `attention_stack` cho từng năm, bước này chuyển tensor attention thành bảng phẳng.

Mỗi dòng biểu diễn một quan hệ có hướng giữa hai công ty trong một năm và một attention head:

```text
src_company_id → dst_company_id
```

Output theo từng năm:

```text
attention_weights_2018.csv
attention_weights_2019.csv
attention_weights_2020.csv
```

Các file này là dữ liệu trung gian, dùng để tạo cạnh Top-K cho Attention Graph.

In [117]:
# Export attention_weights_2018.csv, attention_weights_2019.csv, attention_weights_2020.csv

import os
import pandas as pd
import numpy as np
import torch

ATTENTION_OUTPUT_DIR = "/content/project_outputs/attention_graph"
os.makedirs(ATTENTION_OUTPUT_DIR, exist_ok=True)

def export_attention_weights_for_year(test_year, attention_stack):
    test_year_idx = years.index(test_year)

    symbols_year = all_symbols[test_year_idx]
    labels_year = y_np[test_year_idx]

    assert len(symbols_year) == attention_stack.shape[1]
    assert len(labels_year) == attention_stack.shape[1]

    attention_np = attention_stack.detach().cpu().numpy()
    num_heads, n_src, n_dst = attention_np.shape

    rows = []

    for h in range(num_heads):
        for i in range(n_src):
            src_company_id = int(symbols_year[i])
            src_label = int(labels_year[i])

            for j in range(n_dst):
                dst_company_id = int(symbols_year[j])
                dst_label = int(labels_year[j])

                rows.append({
                    "year": test_year,
                    "head_id": h,
                    "src_index": i,
                    "dst_index": j,
                    "src_company_id": src_company_id,
                    "dst_company_id": dst_company_id,
                    "src_company_year_id": f"{src_company_id}_{test_year}",
                    "dst_company_year_id": f"{dst_company_id}_{test_year}",
                    "attention_weight": float(attention_np[h, i, j]),
                    "src_label": src_label,
                    "dst_label": dst_label,
                    "is_self_loop": int(i == j)
                })

    df = pd.DataFrame(rows)

    out_path = os.path.join(
        ATTENTION_OUTPUT_DIR,
        f"attention_weights_{test_year}.csv"
    )

    df.to_csv(out_path, index=False)

    print("\nĐã xuất:", out_path)
    print("shape:", df.shape)
    print("self_loop count:", df["is_self_loop"].sum())
    print("attention min:", df["attention_weight"].min())
    print("attention max:", df["attention_weight"].max())

    return out_path, df


attention_weight_files = {}

for year in TEST_YEARS:
    attention_stack = attention_results[year]["attention_stack"]
    out_path, _ = export_attention_weights_for_year(year, attention_stack)
    attention_weight_files[year] = out_path

print("\nAttention weight files:")
for year, path in attention_weight_files.items():
    print(year, "->", path)

Đã xuất: /content/project_outputs/attention_graph/attention_weights_2018.csv
shape: (723243, 12)
self_loop count: 1473
attention min: -10.234393119812012
attention max: 31.490766525268555

Đã xuất: /content/project_outputs/attention_graph/attention_weights_2019.csv
shape: (723243, 12)
self_loop count: 1473
attention min: -19.91347885131836
attention max: 43.185970306396484

Đã xuất: /content/project_outputs/attention_graph/attention_weights_2020.csv
shape: (723243, 12)
self_loop count: 1473
attention min: -30.430313110351562
attention max: 52.783477783203125

Attention weight files:
2018 -> /content/project_outputs/attention_graph/attention_weights_2018.csv
2019 -> /content/project_outputs/attention_graph/attention_weights_2019.csv
2020 -> /content/project_outputs/attention_graph/attention_weights_2020.csv

### 5.2.6 Tạo `attention_relation_edge.csv` bằng Top-K Attention

Từ các file `attention_weights_{year}.csv`, ta tạo cạnh Attention Graph chính thức cho 2018, 2019 và 2020.

Các bước xử lý cho từng năm:

1. Loại self-loop: `src_company_id != dst_company_id`.
2. Gộp nhiều attention heads bằng trung bình.
3. Khử hiệu ứng hub theo node đích bằng cách trừ đi attention trung bình của từng công ty đích.
4. Với mỗi công ty nguồn trong từng năm, chọn Top-K công ty đích có `attention_weight` cao nhất.
5. Sinh cạnh có hướng:

```text
src_company_year_id → dst_company_year_id
```

Output theo từng năm:

```text
attention_relation_edge_2018.csv
attention_relation_edge_2019.csv
attention_relation_edge_2020.csv
```

Output gộp để import NebulaGraph:

```text
attention_relation_edge.csv
```

Method sử dụng:

```text
mean_heads_dst_centered
```

In [118]:
# Tạo attention_relation_edge_{year}.csv và file gộp attention_relation_edge.csv

import os
import pandas as pd
import numpy as np

ATTENTION_OUTPUT_DIR = "/content/project_outputs/attention_graph"

TOP_K = 5
AGG_METHOD = "mean_heads_dst_centered"

def build_attention_edges_for_year(test_year):
    attention_weights_path = os.path.join(
        ATTENTION_OUTPUT_DIR,
        f"attention_weights_{test_year}.csv"
    )

    attention_edge_year_path = os.path.join(
        ATTENTION_OUTPUT_DIR,
        f"attention_relation_edge_{test_year}.csv"
    )

    assert os.path.exists(attention_weights_path), f"Không tìm thấy file: {attention_weights_path}"

    df_att = pd.read_csv(attention_weights_path)

    print("\n" + "=" * 80)
    print(f"BUILD ATTENTION EDGES FOR YEAR {test_year}")
    print("=" * 80)
    print("Loaded attention weights:", attention_weights_path)
    print("df_att shape:", df_att.shape)

    # 1. Loại self-loop
    df_no_self = df_att[df_att["is_self_loop"] == 0].copy()
    print("After removing self-loop:", df_no_self.shape)

    # 2. Gộp nhiều attention heads bằng trung bình
    group_cols = [
        "year",
        "src_index",
        "dst_index",
        "src_company_id",
        "dst_company_id",
        "src_company_year_id",
        "dst_company_year_id",
        "src_label",
        "dst_label"
    ]

    df_mean = (
        df_no_self
        .groupby(group_cols, as_index=False)
        .agg(attention_weight_raw=("attention_weight", "mean"))
    )

    # 3. Khử hub effect theo node đích
    df_mean["dst_mean_attention"] = (
        df_mean
        .groupby(["year", "dst_company_id"])["attention_weight_raw"]
        .transform("mean")
    )

    df_mean["attention_weight"] = (
        df_mean["attention_weight_raw"] - df_mean["dst_mean_attention"]
    )

    df_mean["method"] = AGG_METHOD

    # 4. Chọn Top-K theo từng src trong từng năm
    df_mean = df_mean.sort_values(
        by=["year", "src_company_id", "attention_weight"],
        ascending=[True, True, False]
    )

    df_mean["edge_rank"] = (
        df_mean
        .groupby(["year", "src_company_id"])
        .cumcount() + 1
    )

    df_topk = df_mean[df_mean["edge_rank"] <= TOP_K].copy()

    # 5. Chuẩn hóa schema edge để import NebulaGraph
    df_topk = df_topk.rename(columns={
        "src_company_year_id": "src",
        "dst_company_year_id": "dst"
    })

    df_topk["both_fraud"] = (
        (df_topk["src_label"] == 1) & (df_topk["dst_label"] == 1)
    ).astype(int)

    edge_cols = [
        "src",
        "dst",
        "year",
        "attention_weight",
        "attention_weight_raw",
        "dst_mean_attention",
        "src_company_id",
        "dst_company_id",
        "src_label",
        "dst_label",
        "both_fraud",
        "edge_rank",
        "method"
    ]

    df_edges = df_topk[edge_cols].copy()

    df_edges.to_csv(attention_edge_year_path, index=False)

    print("Đã xuất:", attention_edge_year_path)
    print("df_edges shape:", df_edges.shape)
    print("Expected edge count:", 491 * TOP_K)

    print("edge_count:", len(df_edges))
    print("unique src:", df_edges["src"].nunique())
    print("unique dst:", df_edges["dst"].nunique())
    print("same_label_ratio:", (df_edges["src_label"] == df_edges["dst_label"]).mean())
    print("fraud_fraud_ratio:", df_edges["both_fraud"].mean())
    print("attention_weight min:", df_edges["attention_weight"].min())
    print("attention_weight max:", df_edges["attention_weight"].max())

    return df_edges, attention_edge_year_path


all_edge_dfs = []
attention_edge_files = {}

for year in TEST_YEARS:
    df_edges_year, path_year = build_attention_edges_for_year(year)
    all_edge_dfs.append(df_edges_year)
    attention_edge_files[year] = path_year

df_attention_edges_all = pd.concat(all_edge_dfs, ignore_index=True)

attention_edge_all_path = os.path.join(
    ATTENTION_OUTPUT_DIR,
    "attention_relation_edge.csv"
)

df_attention_edges_all.to_csv(attention_edge_all_path, index=False)

print("\n" + "=" * 80)
print("Đã xuất file attention graph gộp để import NebulaGraph:")
print(attention_edge_all_path)
print("shape:", df_attention_edges_all.shape)
print("expected edge count:", 491 * TOP_K * len(TEST_YEARS))
print("years:", sorted(df_attention_edges_all["year"].unique()))
print("unique src:", df_attention_edges_all["src"].nunique())
print("unique dst:", df_attention_edges_all["dst"].nunique())
print("method:", df_attention_edges_all["method"].unique())

================================================================================
BUILD ATTENTION EDGES FOR YEAR 2018
================================================================================
Loaded attention weights: /content/project_outputs/attention_graph/attention_weights_2018.csv
df_att shape: (723243, 12)
After removing self-loop: (721770, 12)
Đã xuất: /content/project_outputs/attention_graph/attention_relation_edge_2018.csv
df_edges shape: (2455, 13)
Expected edge count: 2455
edge_count: 2455
unique src: 491
unique dst: 20
same_label_ratio: 0.6195519348268839
fraud_fraud_ratio: 0.06517311608961303
attention_weight min: -4.667515888749336
attention_weight max: 8.369004213566683

================================================================================
BUILD ATTENTION EDGES FOR YEAR 2019
================================================================================
Loaded attention weights: /content/project_outputs/attention_graph/attention_weights_2019.csv
df_att shape: (723243, 12)
After removing self-loop: (721770, 12)
Đã xuất: /content/project_outputs/attention_graph/attention_relation_edge_2019.csv
df_edges shape: (2455, 13)
Expected edge count: 2455
edge_count: 2455
unique src: 491
unique dst: 17
same_label_ratio: 0.6619144602851323
fraud_fraud_ratio: 0.04602851323828921
attention_weight min: -5.796822950548054
attention_weight max: 2.302460287298475

================================================================================
BUILD ATTENTION EDGES FOR YEAR 2020
================================================================================
Loaded attention weights: /content/project_outputs/attention_graph/attention_weights_2020.csv
df_att shape: (723243, 12)
After removing self-loop: (721770, 12)
Đã xuất: /content/project_outputs/attention_graph/attention_relation_edge_2020.csv
df_edges shape: (2455, 13)
Expected edge count: 2455
edge_count: 2455
unique src: 491
unique dst: 24
same_label_ratio: 0.8224032586558044
fraud_fraud_ratio: 0.0
attention_weight min: -10.391156648373116
attention_weight max: 14.846493288935447

================================================================================
Đã xuất file attention graph gộp để import NebulaGraph:
/content/project_outputs/attention_graph/attention_relation_edge.csv
shape: (7365, 13)
expected edge count: 7365
years: [np.int64(2018), np.int64(2019), np.int64(2020)]
unique src: 1473
unique dst: 61
method: ['mean_heads_dst_centered']

In [119]:
# Kiểm tra các file attention relation edge cuối cùng

import os
import pandas as pd

ATTENTION_OUTPUT_DIR = "/content/project_outputs/attention_graph"

check_files = [
    "attention_relation_edge_2018.csv",
    "attention_relation_edge_2019.csv",
    "attention_relation_edge_2020.csv",
    "attention_relation_edge.csv",
]

for file_name in check_files:
    path = os.path.join(ATTENTION_OUTPUT_DIR, file_name)

    print("\n" + "=" * 80)
    print("File:", path)
    print("exists:", os.path.exists(path))

    if os.path.exists(path):
        df_check = pd.read_csv(path)
        print("Shape:", df_check.shape)
        print("Columns:", list(df_check.columns))
        print("years:", sorted(df_check["year"].unique()))
        print("unique src:", df_check["src"].nunique())
        print("unique dst:", df_check["dst"].nunique())
        print("edge_count:", len(df_check))
        print("method:", df_check["method"].unique())
        print(df_check.head())

================================================================================
File: /content/project_outputs/attention_graph/attention_relation_edge_2018.csv
exists: True
Shape: (2455, 13)
Columns: ['src', 'dst', 'year', 'attention_weight', 'attention_weight_raw', 'dst_mean_attention', 'src_company_id', 'dst_company_id', 'src_label', 'dst_label', 'both_fraud', 'edge_rank', 'method']
years: [np.int64(2018)]
unique src: 491
unique dst: 20
edge_count: 2455
method: ['mean_heads_dst_centered']
      src       dst  year  attention_weight  attention_weight_raw  \
0  1_2018  475_2018  2018         -4.354150             -7.153042
1  1_2018  423_2018  2018         -4.410671             -6.290456
2  1_2018   55_2018  2018         -4.411725             -6.444544
3  1_2018  360_2018  2018         -4.413507             -6.512888
4  1_2018  393_2018  2018         -4.428149             -6.251772

   dst_mean_attention  src_company_id  dst_company_id  src_label  dst_label  \
0           -2.798892               1             475          0          0
1           -1.879785               1             423          0          1
2           -2.032819               1              55          0          1
3           -2.099382               1             360          0          0
4           -1.823623               1             393          0          0

   both_fraud  edge_rank                   method
0           0          1  mean_heads_dst_centered
1           0          2  mean_heads_dst_centered
2           0          3  mean_heads_dst_centered
3           0          4  mean_heads_dst_centered
4           0          5  mean_heads_dst_centered

================================================================================
File: /content/project_outputs/attention_graph/attention_relation_edge_2019.csv
exists: True
Shape: (2455, 13)
Columns: ['src', 'dst', 'year', 'attention_weight', 'attention_weight_raw', 'dst_mean_attention', 'src_company_id', 'dst_company_id', 'src_label', 'dst_label', 'both_fraud', 'edge_rank', 'method']
years: [np.int64(2019)]
unique src: 491
unique dst: 17
edge_count: 2455
method: ['mean_heads_dst_centered']
      src       dst  year  attention_weight  attention_weight_raw  \
0  1_2019   66_2019  2019          1.565114              4.431067
1  1_2019  353_2019  2019          1.563066              4.370902
2  1_2019   24_2019  2019          1.561776              4.889924
3  1_2019  477_2019  2019          1.560518              4.767886
4  1_2019  182_2019  2019          1.559516              4.301105

   dst_mean_attention  src_company_id  dst_company_id  src_label  dst_label  \
0            2.865954               1              66          0          0
1            2.807836               1             353          0          1
2            3.328148               1              24          0          0
3            3.207368               1             477          0          0
4            2.741589               1             182          0          0

   both_fraud  edge_rank                   method
0           0          1  mean_heads_dst_centered
1           0          2  mean_heads_dst_centered
2           0          3  mean_heads_dst_centered
3           0          4  mean_heads_dst_centered
4           0          5  mean_heads_dst_centered

================================================================================
File: /content/project_outputs/attention_graph/attention_relation_edge_2020.csv
exists: True
Shape: (2455, 13)
Columns: ['src', 'dst', 'year', 'attention_weight', 'attention_weight_raw', 'dst_mean_attention', 'src_company_id', 'dst_company_id', 'src_label', 'dst_label', 'both_fraud', 'edge_rank', 'method']
years: [np.int64(2020)]
unique src: 491
unique dst: 24
edge_count: 2455
method: ['mean_heads_dst_centered']
      src       dst  year  attention_weight  attention_weight_raw  \
0  1_2020   54_2020  2020          9.371977             15.437931
1  1_2020  443_2020  2020          9.324984             15.153514
2  1_2020  220_2020  2020          9.313573             14.878905
3  1_2020  382_2020  2020          9.308804             15.506118
4  1_2020    5_2020  2020          9.302660             15.358431

   dst_mean_attention  src_company_id  dst_company_id  src_label  dst_label  \
0            6.065954               1              54          0          0
1            5.828530               1             443          0          0
2            5.565332               1             220          0          0
3            6.197313               1             382          0          0
4            6.055772               1               5          0          0

   both_fraud  edge_rank                   method
0           0          1  mean_heads_dst_centered
1           0          2  mean_heads_dst_centered
2           0          3  mean_heads_dst_centered
3           0          4  mean_heads_dst_centered
4           0          5  mean_heads_dst_centered

================================================================================
File: /content/project_outputs/attention_graph/attention_relation_edge.csv
exists: True
Shape: (7365, 13)
Columns: ['src', 'dst', 'year', 'attention_weight', 'attention_weight_raw', 'dst_mean_attention', 'src_company_id', 'dst_company_id', 'src_label', 'dst_label', 'both_fraud', 'edge_rank', 'method']
years: [np.int64(2018), np.int64(2019), np.int64(2020)]
unique src: 1473
unique dst: 61
edge_count: 7365
method: ['mean_heads_dst_centered']
      src       dst  year  attention_weight  attention_weight_raw  \
0  1_2018  475_2018  2018         -4.354150             -7.153042
1  1_2018  423_2018  2018         -4.410671             -6.290456
2  1_2018   55_2018  2018         -4.411725             -6.444544
3  1_2018  360_2018  2018         -4.413507             -6.512888
4  1_2018  393_2018  2018         -4.428149             -6.251772

   dst_mean_attention  src_company_id  dst_company_id  src_label  dst_label  \
0           -2.798892               1             475          0          0
1           -1.879785               1             423          0          1
2           -2.032819               1              55          0          1
3           -2.099382               1             360          0          0
4           -1.823623               1             393          0          0

   both_fraud  edge_rank                   method
0           0          1  mean_heads_dst_centered
1           0          2  mean_heads_dst_centered
2           0          3  mean_heads_dst_centered
3           0          4  mean_heads_dst_centered
4           0          5  mean_heads_dst_centered

### 5.3 Ghi `main_vera.py` — VerA (Code-faithful)

**Điểm khác biệt chính so với VerB:**

```python
# VerA — Early stopping: TRAIN LOSS thấp nhất (giữ nguyên tác giả)
if tr_loss < loss_min:
    loss_min = tr_loss
    best_epoch = epoch
    wait_count = 0

# VerA — Gradient: 1 lần sau toàn bộ epoch (giữ nguyên tác giả)
for i in train_seq:
    loss.backward()       # tích lũy gradient
optimizer.step()          # update 1 lần duy nhất
```

In [96]:
fixed_main_vera = r'''
import os, sys, json, random
import numpy as np
import torch
from torch import optim
import argparse
from model import *
from util4 import *

parser = argparse.ArgumentParser()
parser.add_argument("--data-path",   type=str,   default="/content/project_data/processed_flat.json")
parser.add_argument("--rnn-length",  type=int,   default=5)
parser.add_argument("--heads-att",   type=int,   default=3)
parser.add_argument("--hidn-att",    type=int,   default=32)
parser.add_argument("--hidn-rnn",    type=int,   default=64)
parser.add_argument("--crf-iter",    type=int,   default=5)
parser.add_argument("--max-epoch",   type=int,   default=800)
parser.add_argument("--wait-epoch",  type=int,   default=150)
parser.add_argument("--device",      type=str,   default="0")
parser.add_argument("--alpha",       type=float, default=0.5)
parser.add_argument("--batch-train", type=int,   default=4)
parser.add_argument("--clip",        type=float, default=1.0)
parser.add_argument("--seed",        type=int,   default=26541)
parser.add_argument("--lr",          type=float, default=1e-2)
parser.add_argument("--gamma",       type=int,   default=1)
parser.add_argument("--n-weight",    type=float, default=0.1)
parser.add_argument("--f-weight",    type=float, default=0.15)
parser.add_argument("--pool-type",   type=int,   default=3)
parser.add_argument("--test-year",   type=int,   default=2018)
parser.add_argument("--dropout",     type=float, default=0.0)
pool_dic = {1:"MAX", 2:"AVG", 3:"SUM"}

args        = parser.parse_args()
rnn_len     = args.rnn_length
MAX_EPOCH   = args.max_epoch
waits       = args.wait_epoch
test_year   = args.test_year
pool_type   = pool_dic[args.pool_type]
batch_train = args.batch_train
DEVICE = f"cuda:{args.device}" if torch.cuda.is_available() else "cpu"

torch.manual_seed(args.seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(args.seed)
np.random.seed(args.seed)
random.seed(args.seed)


def load_dataset(json_path):
    """Đọc processed_flat.json.
    JSON đã là [T, N, 209] nên KHÔNG dùng squeeze(axis=2).
    """
    with open(json_path, "r", encoding="utf-8") as f:
        payload = json.load(f)

    years = [b["year"] for b in payload["data"]]
    rows  = [b["rows"] for b in payload["data"]]

    data = torch.from_numpy(np.array(rows, dtype=np.float32)).float()
    x = data[:, :, :-1]                         # [T, N, 208]
    y = data[:, :, -1].unsqueeze(-1).long()    # [T, N, 1]  <-- FIX dtype

    print(f"Loaded: {len(years)} years | x={tuple(x.shape)}")
    print(f"Years : {years}")

    if test_year not in years:
        raise ValueError(f"test_year {test_year} not in {years}")

    test_idx = years.index(test_year)

    x_train = x[:test_idx]
    y_train = y[:test_idx]
    x_eval  = x[max(0, test_idx - rnn_len): test_idx + 1]
    y_eval  = y[max(0, test_idx - rnn_len): test_idx + 1]

    print(f"Train : {years[:test_idx]} ({x_train.shape[0]} years)")
    print(f"Eval  : {years[max(0, test_idx-rnn_len):test_idx+1]}")

    n_fraud  = int((y_train == 1).sum())
    n_benign = int((y_train == 0).sum())
    print(f"Train labels: fraud={n_fraud}, benign={n_benign}")

    return x_train, x_eval, y_train, y_eval


def do_train(model, x_train, y_train):
    """Train — giữ nguyên logic gốc tác giả:
    - optimizer.step() 1 lần sau toàn bộ vòng lặp
    - gradient tích lũy qua tất cả timestep trong epoch
    """
    model.train()
    seq_len   = len(x_train)
    train_seq = list(range(seq_len))[rnn_len:]

    if not train_seq:
        return 0., 0., 0., 0., 0.

    random.shuffle(train_seq)
    total_loss, cnt = 0., 0
    preds, trues    = [], []

    optimizer.zero_grad()

    for i in train_seq:
        y_i  = y_train[i].to(DEVICE).view(-1).long()   # <-- FIX dtype + shape
        out  = model(x_train[i - rnn_len + 1: i + 1].to(DEVICE))
        loss = criterion(out, y_i)
        loss.backward()

        total_loss += loss.item()
        cnt        += 1

        preds.append(out.detach().cpu().numpy())
        trues.append(y_train[i].cpu().numpy())

    torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
    optimizer.step()
    optimizer.zero_grad()

    acc, recall, pre, auc = train_metrics(trues, preds)
    return total_loss / max(cnt, 1), acc, recall, pre, auc


def do_eval(model, x_eval, y_eval):
    model.eval()
    seq = list(range(len(x_eval)))[rnn_len:]

    if not seq:
        return [0., 0., 0., 0.]

    preds, trues = [], []
    with torch.no_grad():
        for i in seq:
            out = model(x_eval[i - rnn_len + 1: i + 1].to(DEVICE))
            preds.append(out.detach().cpu().numpy())
            trues.append(y_eval[i].cpu().numpy())

    return metrics(trues, preds)


if __name__ == "__main__":
    SEP = "=" * 60
    print(f"\\nACRF-RNN VerA | test_year={test_year} | device={DEVICE}")
    print(SEP)

    x_train, x_eval, y_train, y_eval = load_dataset(args.data_path)

    num_company  = x_train.size(1)
    d_feature    = x_train.size(2)
    class_weight = torch.tensor([args.n_weight, args.f_weight]).to(DEVICE)
    criterion    = FocalLoss(gamma=args.gamma, weight=class_weight)

    model = AC_RNN(
        num_company=num_company,
        d_feature=d_feature,
        d_hidden=d_feature,
        hidn_rnn=args.hidn_rnn,
        heads_att=args.heads_att,
        hidn_att=args.hidn_att,
        crf_iters=args.crf_iter,
        alpha=args.alpha,
        pool_type=pool_type
    ).to(DEVICE)

    model.drop_out = args.dropout
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    print(f"Model params: {sum(p.numel() for p in model.parameters()):,}\\n")

    loss_min    = float("inf")
    best_epoch  = 0
    best_m      = None
    wait_count  = 0
    epoch       = 0

    HDR = f"{'Ep':>4} | {'Loss':>7} | {'TrAcc':>6} | {'EvAcc':>6} | {'Rcl_m':>6} | {'KS':>6} | {'GM':>6} |"
    print(HDR)
    print("-" * len(HDR))

    import time
    t_start = time.time()

    while epoch < MAX_EPOCH:
        tr_loss, tr_acc, tr_rcl, _, _ = do_train(model, x_train, y_train)
        ev = do_eval(model, x_eval, y_eval)

        is_best = ""
        if tr_loss < loss_min:
            loss_min   = tr_loss
            best_epoch = epoch
            best_m     = ev
            wait_count = 0
            is_best    = "best"
        else:
            wait_count += 1

        print(
            f"{epoch:>4} | {tr_loss:>7.4f} | {tr_acc:>6.4f} | "
            f"{ev[0]:>6.4f} | {ev[1]:>6.4f} | {ev[2]:>6.4f} | {ev[3]:>6.4f} | {is_best}"
        )

        if (epoch + 1) % 10 == 0 or is_best == "best":
            elapsed = time.time() - t_start
            pct = (epoch + 1) / MAX_EPOCH * 100
            eta = elapsed / (epoch + 1) * (MAX_EPOCH - epoch - 1)
            print(
                f"  --> [{pct:5.1f}%] ep {epoch+1}/{MAX_EPOCH} | "
                f"elapsed {elapsed:.0f}s | ETA {eta:.0f}s | "
                f"best loss {loss_min:.4f} @ ep{best_epoch} | "
                f"wait {wait_count}/{waits}"
            )

        if wait_count >= waits:
            print(f"\\nEarly stop @ epoch {epoch}  (best_epoch={best_epoch})")
            break

        epoch += 1

    print(f"\\n{SEP}")
    print(f"KET QUA VerA -- test_year={test_year}")
    print(SEP)

    if best_m:
        paper = {
            2018: (77.60, 70.79, 41.58, 69.37),
            2019: (80.45, 75.44, 50.88, 74.89),
            2020: (79.43, 71.96, 43.92, 71.04),
        }
        p = paper.get(test_year, (0, 0, 0, 0))

        print(f"Best epoch (by train_loss): {best_epoch}")
        print(f"Best train_loss           : {loss_min:.4f}")
        print(f"{'Metric':<12} {'Paper':>7} {'VerA':>7} {'Diff':>7}")
        print("-" * 40)

        for name, pv, ov in zip(
                ["Accuracy", "Recall_m", "KS", "G-mean"],
                p,
                [m * 100 for m in best_m]):
            d = ov - pv
            print(f"{name:<12} {pv:>7.2f} {ov:>7.2f} {'+' if d >= 0 else ''}{d:>6.2f}")
'''

with open("/content/ACRF-RNN/Code/main_vera.py", "w", encoding="utf-8") as f:
    f.write(fixed_main_vera)

print("Đã ghi /content/ACRF-RNN/Code/main_vera.py")
!wc -l /content/ACRF-RNN/Code/main_vera.py

Đã ghi /content/ACRF-RNN/Code/main_vera.py
240 /content/ACRF-RNN/Code/main_vera.py

### 5.4 Ghi `main.py` — VerB (Paper-faithful)

**Điểm khác biệt chính so với VerA:**

```python
# VerB — Early stopping: EVAL KS cao nhất (theo bài báo Section 5.3)
if ev[2] > best_ks:
    best_ks = ev[2]
    best_epoch = epoch
    wait_count = 0

# VerB — Gradient: mỗi batch_train=4 bước (theo bài báo Section 5.4)
for i in train_seq:
    loss.backward()
    if cnt % batch_train == batch_train - 1:
        optimizer.step()  # update mỗi 4 bước
        optimizer.zero_grad()
```

In [97]:
# main.py — Fix 1, 3, 4, 5, 6 + đọc JSON từ Spark pipeline
fixed_main_verb = r'''
import os, sys, json, random
import numpy as np
import torch
from torch import optim
import argparse
from model import *
from util4 import *

parser = argparse.ArgumentParser()
parser.add_argument("--data-path",   type=str,   default="/content/project_data/processed_flat.json")
parser.add_argument("--rnn-length",  type=int,   default=5)
parser.add_argument("--heads-att",   type=int,   default=3)
parser.add_argument("--hidn-att",    type=int,   default=32)
parser.add_argument("--hidn-rnn",    type=int,   default=64)
parser.add_argument("--crf-iter",    type=int,   default=5)
parser.add_argument("--max-epoch",   type=int,   default=800)
parser.add_argument("--wait-epoch",  type=int,   default=150)
parser.add_argument("--device",      type=str,   default="0")
parser.add_argument("--alpha",       type=float, default=0.5)
parser.add_argument("--batch-train", type=int,   default=4)
parser.add_argument("--clip",        type=float, default=1.0)
parser.add_argument("--seed",        type=int,   default=26541)
parser.add_argument("--lr",          type=float, default=1e-2)
parser.add_argument("--gamma",       type=int,   default=1)
parser.add_argument("--n-weight",    type=float, default=0.1)
parser.add_argument("--f-weight",    type=float, default=0.15)
parser.add_argument("--pool-type",   type=int,   default=3)
parser.add_argument("--test-year",   type=int,   default=2018)
parser.add_argument("--dropout",     type=float, default=0.0)
pool_dic = {1:"MAX", 2:"AVG", 3:"SUM"}

args        = parser.parse_args()
rnn_len     = args.rnn_length
MAX_EPOCH   = args.max_epoch
waits       = args.wait_epoch
test_year   = args.test_year
pool_type   = pool_dic[args.pool_type]
batch_train = args.batch_train
DEVICE = f"cuda:{args.device}" if torch.cuda.is_available() else "cpu"

torch.manual_seed(args.seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(args.seed)
np.random.seed(args.seed)
random.seed(args.seed)


def load_dataset(json_path):
    """Doc processed_flat.json tu Spark pipeline.
    FIX 1: bo np.squeeze(axis=2) — JSON da la [T,N,209], khong co chieu thua.
    """
    with open(json_path, "r", encoding="utf-8") as f:
        payload = json.load(f)
    years = [b["year"] for b in payload["data"]]
    rows  = [b["rows"] for b in payload["data"]]
    data  = torch.from_numpy(np.array(rows, dtype=np.float32)).float()
    # data shape: [T, N, 209]
    # (CSV gốc có shape [T,N,1,209] vì groupby tạo thêm 1 chiều thừa;
    #  JSON đã flat nên không cần squeeze(axis=2) nua)
    y = data[:, :, -1].unsqueeze(-1).long()   # [T, N, 1]
    x = data[:, :, :-1]                        # [T, N, 208]
    print(f"Loaded: {len(years)} years | x={tuple(x.shape)} | y={tuple(y.shape)}")
    print(f"Years : {years}")
    if test_year not in years:
        raise ValueError(f"test_year {test_year} not in {years}")
    test_idx   = years.index(test_year)
    x_train    = x[:test_idx]
    y_train    = y[:test_idx]
    eval_start = max(0, test_idx - rnn_len)
    x_eval     = x[eval_start:test_idx + 1]
    y_eval     = y[eval_start:test_idx + 1]
    print(f"Train : {years[:test_idx]}  ({x_train.shape[0]} years)")
    print(f"Eval  : {years[eval_start:test_idx+1]}")
    n_fraud  = int((y_train == 1).sum())
    n_benign = int((y_train == 0).sum())
    print(f"Train labels: fraud={n_fraud}, benign={n_benign}")
    return x_train, x_eval, y_train, y_eval


def do_train(model, x_train, y_train):
    model.train()
    seq_len   = len(x_train)
    train_seq = list(range(seq_len))[rnn_len:]
    if not train_seq:
        return 0., 0., 0., 0., 0.
    random.shuffle(train_seq)   # Fix 6: bỏ tham số random= (Python >= 3.9)
    total_loss, cnt = 0., 0
    preds, trues    = [], []
    optimizer.zero_grad()
    for i in train_seq:
        y_i  = torch.squeeze(y_train[i], 1).to(DEVICE)
        out  = model(x_train[i - rnn_len + 1: i + 1].to(DEVICE))
        loss = criterion(out, y_i)
        loss.backward()
        total_loss += loss.item()
        cnt        += 1
        if cnt % batch_train == batch_train - 1:
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
            optimizer.step()
            optimizer.zero_grad()
        preds.append(out.detach().cpu().numpy())
        trues.append(y_train[i].cpu().numpy())
    if cnt % batch_train != batch_train - 1:
        torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
        optimizer.step()
        optimizer.zero_grad()
    acc, recall, pre, auc = train_metrics(trues, preds)
    return total_loss / max(cnt, 1), acc, recall, pre, auc


def do_eval(model, x_eval, y_eval):
    """Eval — KS dung ks_2samp tu util4.py (dung dinh nghia bai bao).
    FIX 3: bo plt_output chua dinh nghia trong main.py goc.
    """
    model.eval()
    seq = list(range(len(x_eval)))[rnn_len:]
    if not seq:
        return [0., 0., 0., 0.]
    preds, trues = [], []
    with torch.no_grad():
        for i in seq:
            out = model(x_eval[i - rnn_len + 1: i + 1].to(DEVICE))
            preds.append(out.detach().cpu().numpy())
            trues.append(y_eval[i].cpu().numpy())
    return metrics(trues, preds)   # [acc, recall_macro, KS(ks_2samp), G-mean]


if __name__ == "__main__":
    SEP = "=" * 60
    print(f"\nACRF-RNN | test_year={test_year} | device={DEVICE}")
    print(SEP)

    x_train, x_eval, y_train, y_eval = load_dataset(args.data_path)

    num_company  = x_train.size(1)
    d_feature    = x_train.size(2)
    class_weight = torch.tensor([args.n_weight, args.f_weight]).to(DEVICE)
    criterion    = FocalLoss(gamma=args.gamma, weight=class_weight)

    model = AC_RNN(
        num_company=num_company,
        d_feature=d_feature,
        d_hidden=d_feature,
        hidn_rnn=args.hidn_rnn,
        heads_att=args.heads_att,
        hidn_att=args.hidn_att,
        crf_iters=args.crf_iter,
        alpha=args.alpha,
        pool_type=pool_type
    ).to(DEVICE)
    model.drop_out = args.dropout
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    print(f"Model params: {sum(p.numel() for p in model.parameters()):,}\n")

    best_ks, best_epoch, best_m = -1., 0, None
    wait_count, epoch = 0, 0

    HDR = f"{'Ep':>4} | {'Loss':>7} | {'TrAcc':>6} | {'EvAcc':>6} | {'Rcl_m':>6} | {'KS':>6} | {'GM':>6} |"
    print(HDR)
    print("-" * len(HDR))

    from tqdm import tqdm
    pbar = tqdm(total=MAX_EPOCH, desc=f"test_year={test_year}",
                unit="ep", dynamic_ncols=True,
                bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} ep [{elapsed}<{remaining}]")

    while epoch < MAX_EPOCH:
        tr_loss, tr_acc, tr_rcl, _, _ = do_train(model, x_train, y_train)
        ev = do_eval(model, x_eval, y_eval)
        is_best = ""
        if ev[2] > best_ks:
            best_ks, best_epoch, best_m = ev[2], epoch, ev
            wait_count = 0
            is_best    = "best"
        else:
            wait_count += 1
        print(
            f"{epoch:>4} | {tr_loss:>7.4f} | {tr_acc:>6.4f} | "
            f"{ev[0]:>6.4f} | {ev[1]:>6.4f} | {ev[2]:>6.4f} | {ev[3]:>6.4f} | {is_best}"
        )
        # Cap nhat tqdm: hien thi epoch hien tai, KS tot nhat, patience con lai
        pbar.update(1)
        pbar.set_postfix({
            "loss": f"{tr_loss:.4f}",
            "KS": f"{ev[2]*100:.2f}%",
            "best_KS": f"{best_ks*100:.2f}%@ep{best_epoch}",
            "wait": f"{wait_count}/{waits}",
        }, refresh=True)
        if wait_count >= waits:
            pbar.set_description(f"Early stop ep{epoch} | best ep{best_epoch}")
            pbar.close()
            print(f"\nEarly stop @ epoch {epoch}  (best_epoch={best_epoch})")
            break
        epoch += 1
    else:
        pbar.close()

    print(f"\n{SEP}")
    print(f"KET QUA -- test_year={test_year}")
    print(SEP)
    if best_m:
        paper = {
            2018: (77.60, 70.79, 41.58, 69.37),
            2019: (80.45, 75.44, 50.88, 74.89),
            2020: (79.43, 71.96, 43.92, 71.04),
        }
        p = paper.get(test_year, (0, 0, 0, 0))
        print(f"Best epoch : {best_epoch}")
        print(f"{'Metric':<12} {'Paper':>7} {'VerB':>7} {'Diff':>7}")
        print("-" * 40)
        for name, pv, ov in zip(
                ["Accuracy", "Recall_m", "KS", "G-mean"],
                p,
                [m * 100 for m in best_m]):
            d = ov - pv
            print(f"{name:<12} {pv:>7.2f} {ov:>7.2f} {'+' if d >= 0 else ''}{d:>6.2f}")
'''

with open("/content/ACRF-RNN/Code/main.py", "w", encoding="utf-8") as f:
    f.write(fixed_main_verb)
print("Đã ghi /content/ACRF-RNN/Code/main.py")
!wc -l /content/ACRF-RNN/Code/main.py

Đã ghi /content/ACRF-RNN/Code/main.py
217 /content/ACRF-RNN/Code/main.py

## Giai đoạn 6 — Thực nghiệm

### 6.1 Smoke test (5 epoch) — kiểm tra pipeline không lỗi

In [98]:
%cd /content/ACRF-RNN/Code
!python main.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2018 --max-epoch 5 --wait-epoch 3 --device 0 \
    2>&1 | head -30

/content/ACRF-RNN/Code

ACRF-RNN | test_year=2018 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208) | y=(10, 491, 1)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017]  (7 years)
Eval  : [2012, 2013, 2014, 2015, 2017, 2018]
Train labels: fraud=860, benign=2577
Model params: 972,937

  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
Early stop ep3 | best ep0:  80%|████████  | 4/5 ep [00:00<00:00]
   0 |  0.4153 | 0.5580 | 0.4725 | 0.4469 | 0.1063 | 0.4437 | best
   1 |  0.4404 | 0.5204 | 0.5214 | 0.4926 | 0.0147 | 0.4890 |
   2 |  0.4085 | 0.4939 | 0.5356 | 0.5048 | 0.0096 | 0.5008 |
   3 |  0.3919 | 0.5458 | 0.5743 | 0.5335 | 0.0670 | 0.5267 |

Early stop @ epoch 3  (best_epoch=0)

============================================================
KET QUA -- test_year=2018
============================================================
Best epoch : 0
Metric         Paper    VerB    Diff
----------------------------------------
Accuracy       77.60   47.25 -30.35
Recall_m       70.79   44.69 -26.10
KS             41.58   10.63 -30.95
G-mean         69.37   44.37 -25.00

### 6.2–6.4 VerA — Code-faithful

Chạy `main_vera.py` với early stopping theo **train_loss**.

#### 6.2 VerA — Test year 2018

In [99]:
%cd /content/ACRF-RNN/Code
!ls -lah

/content/ACRF-RNN/Code
total 56K
drwxr-xr-x 4 root root 4.0K Jun  2 09:05 .
drwxr-xr-x 5 root root 4.0K Jun  2 09:02 ..
-rw-r--r-- 1 root root 5.2K Jun  2 09:02 layer.py
-rw-r--r-- 1 root root 8.3K Jun  2 09:05 main.py
-rw-r--r-- 1 root root 7.8K Jun  2 09:05 main_vera.py
-rw-r--r-- 1 root root 3.1K Jun  2 09:02 model_attention.py
-rw-r--r-- 1 root root 2.2K Jun  2 09:02 model.py
drwxr-xr-x 2 root root 4.0K Jun  2 09:05 __pycache__
drwxr-xr-x 2 root root 4.0K Jun  2 09:02 savemodel
-rw-r--r-- 1 root root 2.4K Jun  2 09:02 util4.py

In [100]:
%cd /content/ACRF-RNN/Code
!python main_vera.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2018 --max-epoch 800 --wait-epoch 150 --device 0 \
    2>&1 | tee /content/project_outputs/run_vera_2018.log

/content/ACRF-RNN/Code
\nACRF-RNN VerA | test_year=2018 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017] (7 years)
Eval  : [2012, 2013, 2014, 2015, 2017, 2018]
Train labels: fraud=860, benign=2577
Model params: 972,937\n
  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
   0 |  0.4153 | 0.5580 | 0.4725 | 0.4469 | 0.1063 | 0.4437 | best
  --> [  0.1%] ep 1/800 | elapsed 0s | ETA 355s | best loss 0.4153 @ ep0 | wait 0/150
   1 |  0.4404 | 0.5204 | 0.5214 | 0.4926 | 0.0147 | 0.4890 |
   2 |  0.4085 | 0.4939 | 0.5356 | 0.5048 | 0.0096 | 0.5008 | best
  --> [  0.4%] ep 3/800 | elapsed 1s | ETA 145s | best loss 0.4085 @ ep2 | wait 0/150
   3 |  0.3919 | 0.5458 | 0.5743 | 0.5335 | 0.0670 | 0.5267 | best
  --> [  0.5%] ep 4/800 | elapsed 1s | ETA 118s | best loss 0.3919 @ ep3 | wait 0/150
   4 |  0.2982 | 0.6527 | 0.5927 | 0.5458 | 0.0917 | 0.5371 | best
  --> [  0.6%] ep 5/800 | elapsed 1s | ETA 102s | best loss 0.2982 @ ep4 | wait 0/150
   5 |  0.2488 | 0.7251 | 0.6395 | 0.5902 | 0.1805 | 0.5814 | best
  --> [  0.8%] ep 6/800 | elapsed 1s | ETA 91s | best loss 0.2488 @ ep5 | wait 0/150
   6 |  0.2280 | 0.7648 | 0.6864 | 0.6449 | 0.2898 | 0.6392 | best
  --> [  0.9%] ep 7/800 | elapsed 1s | ETA 83s | best loss 0.2280 @ ep6 | wait 0/150
   7 |  0.4240 | 0.5081 | 0.6904 | 0.6605 | 0.3210 | 0.6576 |
   8 |  0.1798 | 0.8513 | 0.3442 | 0.3603 | 0.2794 | 0.3588 | best
  --> [  1.1%] ep 9/800 | elapsed 1s | ETA 74s | best loss 0.1798 @ ep8 | wait 0/150
   9 |  0.1651 | 0.8554 | 0.6660 | 0.6542 | 0.3085 | 0.6538 | best
  --> [  1.2%] ep 10/800 | elapsed 1s | ETA 70s | best loss 0.1651 @ ep9 | wait 0/150
  10 |  0.1581 | 0.8564 | 0.6782 | 0.6574 | 0.3147 | 0.6559 | best
  --> [  1.4%] ep 11/800 | elapsed 1s | ETA 67s | best loss 0.1581 @ ep10 | wait 0/150
  11 |  0.1521 | 0.8686 | 0.6802 | 0.6510 | 0.3021 | 0.6482 | best
  --> [  1.5%] ep 12/800 | elapsed 1s | ETA 64s | best loss 0.1521 @ ep11 | wait 0/150
  12 |  0.1458 | 0.8778 | 0.7026 | 0.6662 | 0.3323 | 0.6619 | best
  --> [  1.6%] ep 13/800 | elapsed 1s | ETA 62s | best loss 0.1458 @ ep12 | wait 0/150
  13 |  0.1410 | 0.8900 | 0.7291 | 0.6840 | 0.3680 | 0.6776 | best
  --> [  1.8%] ep 14/800 | elapsed 1s | ETA 60s | best loss 0.1410 @ ep13 | wait 0/150
  14 |  0.1367 | 0.9063 | 0.7271 | 0.6826 | 0.3653 | 0.6764 | best
  --> [  1.9%] ep 15/800 | elapsed 1s | ETA 58s | best loss 0.1367 @ ep14 | wait 0/150
  15 |  0.1313 | 0.9104 | 0.7352 | 0.6856 | 0.3711 | 0.6778 | best
  --> [  2.0%] ep 16/800 | elapsed 1s | ETA 57s | best loss 0.1313 @ ep15 | wait 0/150
  16 |  0.1273 | 0.9287 | 0.7393 | 0.6858 | 0.3715 | 0.6767 | best
  --> [  2.1%] ep 17/800 | elapsed 1s | ETA 55s | best loss 0.1273 @ ep16 | wait 0/150
  17 |  0.1221 | 0.9348 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  --> [  2.2%] ep 18/800 | elapsed 1s | ETA 54s | best loss 0.1221 @ ep17 | wait 0/150
  18 |  0.1168 | 0.9409 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  --> [  2.4%] ep 19/800 | elapsed 1s | ETA 53s | best loss 0.1168 @ ep18 | wait 0/150
  19 |  0.1084 | 0.9511 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  --> [  2.5%] ep 20/800 | elapsed 1s | ETA 53s | best loss 0.1084 @ ep19 | wait 0/150
  20 |  0.1020 | 0.9542 | 0.7454 | 0.6899 | 0.3797 | 0.6802 | best
  --> [  2.6%] ep 21/800 | elapsed 1s | ETA 52s | best loss 0.1020 @ ep20 | wait 0/150
  21 |  0.3562 | 0.6415 | 0.7495 | 0.6926 | 0.3852 | 0.6825 |
  22 |  0.0980 | 0.9684 | 0.7536 | 0.6954 | 0.3907 | 0.6848 | best
  --> [  2.9%] ep 23/800 | elapsed 1s | ETA 50s | best loss 0.0980 @ ep22 | wait 0/150
  23 |  0.1016 | 0.9603 | 0.7597 | 0.6969 | 0.3939 | 0.6847 |
  24 |  0.4615 | 0.5295 | 0.7576 | 0.6981 | 0.3962 | 0.6871 |
  25 |  0.3598 | 0.6273 | 0.7719 | 0.7052 | 0.4103 | 0.6915 |
  26 |  0.4181 | 0.5672 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  27 |  0.1793 | 0.8666 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  28 |  0.1804 | 0.8595 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
  29 |  0.1804 | 0.8585 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  --> [  3.8%] ep 30/800 | elapsed 2s | ETA 46s | best loss 0.0980 @ ep22 | wait 7/150
  30 |  0.1800 | 0.8605 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  31 |  0.1794 | 0.8595 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  32 |  0.1792 | 0.8574 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  33 |  0.1788 | 0.8585 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  34 |  0.1788 | 0.8585 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  35 |  0.1786 | 0.8574 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  36 |  0.1785 | 0.8574 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
  37 |  0.1781 | 0.8595 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  38 |  0.1785 | 0.8595 | 0.2933 | 0.3362 | 0.3276 | 0.3242 |
  39 |  0.1782 | 0.8625 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  --> [  5.0%] ep 40/800 | elapsed 2s | ETA 43s | best loss 0.0980 @ ep22 | wait 17/150
  40 |  0.1784 | 0.8625 | 0.7719 | 0.7052 | 0.4103 | 0.6915 |
  41 |  0.1782 | 0.8605 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  42 |  0.1785 | 0.8585 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  43 |  0.1781 | 0.8595 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  44 |  0.1779 | 0.8625 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  45 |  0.1834 | 0.8554 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  46 |  0.1781 | 0.8595 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  47 |  0.1839 | 0.8523 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  48 |  0.1775 | 0.8635 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  49 |  0.1781 | 0.8605 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  --> [  6.2%] ep 50/800 | elapsed 3s | ETA 41s | best loss 0.0980 @ ep22 | wait 27/150
  50 |  0.1799 | 0.8574 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  51 |  0.1782 | 0.8635 | 0.2933 | 0.3516 | 0.2968 | 0.3302 |
  52 |  0.1773 | 0.8625 | 0.7699 | 0.7038 | 0.4076 | 0.6904 |
  53 |  0.1769 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  54 |  0.1833 | 0.8523 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  55 |  0.1798 | 0.8595 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  56 |  0.1770 | 0.8625 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  57 |  0.1767 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  58 |  0.1902 | 0.8462 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  59 |  0.1763 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  --> [  7.5%] ep 60/800 | elapsed 3s | ETA 39s | best loss 0.0980 @ ep22 | wait 37/150
  60 |  0.1758 | 0.8666 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  61 |  0.1753 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  62 |  0.1762 | 0.8697 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  63 |  0.1732 | 0.8758 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  64 |  0.1760 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  65 |  0.1754 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  66 |  0.1751 | 0.8727 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  67 |  0.1749 | 0.8676 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  68 |  0.1742 | 0.8585 | 0.7699 | 0.7038 | 0.4076 | 0.6904 |
  69 |  0.3350 | 0.6670 | 0.7637 | 0.6971 | 0.3942 | 0.6833 |
  --> [  8.8%] ep 70/800 | elapsed 4s | ETA 38s | best loss 0.0980 @ ep22 | wait 47/150
  70 |  0.3149 | 0.6955 | 0.7515 | 0.6889 | 0.3777 | 0.6765 |
  71 |  0.4204 | 0.5367 | 0.7760 | 0.7130 | 0.4261 | 0.7010 |
  72 |  0.1769 | 0.8666 | 0.7739 | 0.7065 | 0.4131 | 0.6926 |
  73 |  0.1824 | 0.8534 | 0.7739 | 0.7065 | 0.4131 | 0.6926 |
  74 |  0.1730 | 0.8727 | 0.7800 | 0.7132 | 0.4265 | 0.6997 |
  75 |  0.1719 | 0.8717 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  76 |  0.1714 | 0.8697 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  77 |  0.1722 | 0.8717 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  78 |  0.1735 | 0.8686 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  79 |  0.2454 | 0.7811 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  --> [ 10.0%] ep 80/800 | elapsed 4s | ETA 37s | best loss 0.0980 @ ep22 | wait 57/150
  80 |  0.2966 | 0.7138 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  81 |  0.2083 | 0.8177 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  82 |  0.2160 | 0.8096 | 0.6334 | 0.6169 | 0.2338 | 0.6159 |
  83 |  0.2712 | 0.7434 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  84 |  0.3204 | 0.6823 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  85 |  0.3424 | 0.6589 | 0.7800 | 0.7132 | 0.4265 | 0.6997 |
  86 |  0.1935 | 0.8279 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  87 |  0.3677 | 0.6334 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  88 |  0.3827 | 0.6161 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  89 |  0.3852 | 0.6161 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  --> [ 11.2%] ep 90/800 | elapsed 5s | ETA 36s | best loss 0.0980 @ ep22 | wait 67/150
  90 |  0.1887 | 0.8483 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  91 |  0.1809 | 0.8595 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  92 |  0.1807 | 0.8605 | 0.2729 | 0.3276 | 0.3448 | 0.3074 |
  93 |  0.1687 | 0.8737 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  94 |  0.1771 | 0.8615 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  95 |  0.1750 | 0.8635 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  96 |  0.1716 | 0.8646 | 0.7719 | 0.7077 | 0.4155 | 0.6951 |
  97 |  0.1689 | 0.8666 | 0.7658 | 0.7036 | 0.4072 | 0.6917 |
  98 |  0.1672 | 0.8646 | 0.7658 | 0.7010 | 0.4021 | 0.6881 |
  99 |  0.1657 | 0.8666 | 0.7637 | 0.7022 | 0.4045 | 0.6906 |
  --> [ 12.5%] ep 100/800 | elapsed 5s | ETA 35s | best loss 0.0980 @ ep22 | wait 77/150
 100 |  0.1630 | 0.8717 | 0.7556 | 0.6942 | 0.3884 | 0.6824 |
 101 |  0.1616 | 0.8717 | 0.7515 | 0.6914 | 0.3829 | 0.6801 |
 102 |  0.1608 | 0.8768 | 0.7495 | 0.6926 | 0.3852 | 0.6825 |
 103 |  0.1577 | 0.8798 | 0.7475 | 0.6912 | 0.3825 | 0.6814 |
 104 |  0.1567 | 0.8788 | 0.7454 | 0.6950 | 0.3900 | 0.6871 |
 105 |  0.1541 | 0.8768 | 0.7434 | 0.6936 | 0.3873 | 0.6859 |
 106 |  0.1517 | 0.8839 | 0.7413 | 0.6923 | 0.3845 | 0.6847 |
 107 |  0.1484 | 0.8890 | 0.7373 | 0.6869 | 0.3739 | 0.6790 |
 108 |  0.1477 | 0.8880 | 0.7393 | 0.6909 | 0.3818 | 0.6836 |
 109 |  0.1449 | 0.8971 | 0.7454 | 0.7027 | 0.4054 | 0.6971 |
  --> [ 13.8%] ep 110/800 | elapsed 5s | ETA 34s | best loss 0.0980 @ ep22 | wait 87/150
 110 |  0.1427 | 0.8992 | 0.7454 | 0.7027 | 0.4054 | 0.6971 |
 111 |  0.1389 | 0.9053 | 0.7413 | 0.6974 | 0.3948 | 0.6914 |
 112 |  0.1351 | 0.9084 | 0.7454 | 0.7053 | 0.4105 | 0.7003 |
 113 |  0.1333 | 0.9063 | 0.7495 | 0.7106 | 0.4211 | 0.7060 |
 114 |  0.1291 | 0.9124 | 0.7475 | 0.7092 | 0.4184 | 0.7047 |
 115 |  0.1358 | 0.9033 | 0.7475 | 0.7092 | 0.4184 | 0.7047 |
 116 |  0.1276 | 0.9134 | 0.7454 | 0.7053 | 0.4105 | 0.7003 |
 117 |  0.1260 | 0.9206 | 0.7393 | 0.7011 | 0.4023 | 0.6967 |
 118 |  0.1245 | 0.9196 | 0.7352 | 0.6984 | 0.3968 | 0.6942 |
 119 |  0.1212 | 0.9206 | 0.7312 | 0.6931 | 0.3862 | 0.6886 |
  --> [ 15.0%] ep 120/800 | elapsed 6s | ETA 34s | best loss 0.0980 @ ep22 | wait 97/150
 120 |  0.1195 | 0.9246 | 0.7312 | 0.6931 | 0.3862 | 0.6886 |
 121 |  0.1170 | 0.9267 | 0.7291 | 0.6891 | 0.3783 | 0.6841 |
 122 |  0.1132 | 0.9348 | 0.7475 | 0.6861 | 0.3722 | 0.6743 |
 123 |  0.1094 | 0.9409 | 0.7312 | 0.6905 | 0.3810 | 0.6854 |
 124 |  0.1115 | 0.9379 | 0.7332 | 0.6893 | 0.3786 | 0.6833 |
 125 |  0.1060 | 0.9491 | 0.7291 | 0.6866 | 0.3732 | 0.6809 |
 126 |  0.1081 | 0.9460 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
 127 |  0.1081 | 0.9470 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
 128 |  0.1078 | 0.9491 | 0.7434 | 0.6911 | 0.3821 | 0.6825 |
 129 |  0.1068 | 0.9521 | 0.7475 | 0.6938 | 0.3876 | 0.6849 |
  --> [ 16.2%] ep 130/800 | elapsed 6s | ETA 33s | best loss 0.0980 @ ep22 | wait 107/150
 130 |  0.1052 | 0.9582 | 0.7495 | 0.6952 | 0.3904 | 0.6860 |
 131 |  0.1174 | 0.9379 | 0.7576 | 0.7007 | 0.4014 | 0.6907 |
 132 |  0.1019 | 0.9684 | 0.7454 | 0.6924 | 0.3849 | 0.6837 |
 133 |  0.1002 | 0.9715 | 0.7637 | 0.7022 | 0.4045 | 0.6906 |
 134 |  0.0995 | 0.9735 | 0.7556 | 0.6942 | 0.3884 | 0.6824 |
 135 |  0.0988 | 0.9745 | 0.7576 | 0.6981 | 0.3962 | 0.6871 |
 136 |  0.1001 | 0.9745 | 0.2566 | 0.3115 | 0.3770 | 0.2900 |
 137 |  0.3926 | 0.6029 | 0.7699 | 0.7064 | 0.4127 | 0.6940 |
 138 |  0.1029 | 0.9857 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
 139 |  0.1115 | 0.9745 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  --> [ 17.5%] ep 140/800 | elapsed 7s | ETA 32s | best loss 0.0980 @ ep22 | wait 117/150
 140 |  0.1133 | 0.9817 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
 141 |  0.2673 | 0.6670 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
 142 |  0.3024 | 0.7057 | 0.7047 | 0.6752 | 0.3504 | 0.6725 |
 143 |  0.1335 | 0.9532 | 0.7556 | 0.6891 | 0.3781 | 0.6751 |
 144 |  0.1671 | 0.8870 | 0.7332 | 0.6816 | 0.3633 | 0.6732 |
 145 |  0.2240 | 0.7780 | 0.6395 | 0.6287 | 0.2574 | 0.6283 |
 146 |  0.2808 | 0.6436 | 0.4990 | 0.5057 | 0.0114 | 0.5055 |
 147 |  0.4426 | 0.3910 | 0.7088 | 0.6651 | 0.3303 | 0.6590 |
 148 |  0.4054 | 0.4430 | 0.4501 | 0.4369 | 0.1263 | 0.4360 |
 149 |  0.3934 | 0.4766 | 0.4644 | 0.4439 | 0.1122 | 0.4419 |
  --> [ 18.8%] ep 150/800 | elapsed 7s | ETA 32s | best loss 0.0980 @ ep22 | wait 127/150
 150 |  0.3628 | 0.5377 | 0.4766 | 0.4599 | 0.0803 | 0.4585 |
 151 |  0.3525 | 0.5560 | 0.7393 | 0.6858 | 0.3715 | 0.6767 |
 152 |  0.1806 | 0.8585 | 0.7800 | 0.7081 | 0.4162 | 0.6922 |
 153 |  0.4816 | 0.4674 | 0.5234 | 0.5094 | 0.0188 | 0.5086 |
 154 |  0.7534 | 0.1609 | 0.2831 | 0.3319 | 0.3362 | 0.3161 |
 155 |  0.4613 | 0.3666 | 0.4297 | 0.4231 | 0.1537 | 0.4229 |
 156 |  0.3840 | 0.4980 | 0.4684 | 0.4569 | 0.0862 | 0.4563 |
 157 |  0.3233 | 0.5550 | 0.4868 | 0.4693 | 0.0614 | 0.4679 |
 158 |  0.2861 | 0.6100 | 0.5255 | 0.4954 | 0.0092 | 0.4914 |
 159 |  0.2654 | 0.6609 | 0.5540 | 0.5069 | 0.0138 | 0.4975 |
  --> [ 20.0%] ep 160/800 | elapsed 8s | ETA 31s | best loss 0.0980 @ ep22 | wait 137/150
 160 |  0.2503 | 0.7077 | 0.5784 | 0.5337 | 0.0673 | 0.5255 |
 161 |  0.2386 | 0.7485 | 0.6069 | 0.5555 | 0.1109 | 0.5451 |
 162 |  0.2274 | 0.7841 | 0.6273 | 0.5743 | 0.1486 | 0.5637 |
 163 |  0.2176 | 0.8147 | 0.6477 | 0.5932 | 0.1864 | 0.5823 |
 164 |  0.2089 | 0.8371 | 0.6538 | 0.5973 | 0.1946 | 0.5857 |
 165 |  0.2022 | 0.8503 | 0.6680 | 0.6044 | 0.2087 | 0.5898 |
 166 |  0.1954 | 0.8554 | 0.6802 | 0.6152 | 0.2303 | 0.6002 |
 167 |  0.1883 | 0.8717 | 0.6904 | 0.6246 | 0.2492 | 0.6095 |
 168 |  0.1817 | 0.8809 | 0.6986 | 0.6352 | 0.2704 | 0.6215 |
 169 |  0.1779 | 0.8890 | 0.6965 | 0.6313 | 0.2625 | 0.6166 |
  --> [ 21.2%] ep 170/800 | elapsed 8s | ETA 30s | best loss 0.0980 @ ep22 | wait 147/150
 170 |  0.1747 | 0.8900 | 0.6986 | 0.6301 | 0.2602 | 0.6139 |
 171 |  0.1704 | 0.8961 | 0.7067 | 0.6381 | 0.2763 | 0.6221 |
 172 |  0.1657 | 0.9094 | 0.7149 | 0.6462 | 0.2924 | 0.6303 |
\nEarly stop @ epoch 172  (best_epoch=22)
\n============================================================
KET QUA VerA -- test_year=2018
============================================================
Best epoch (by train_loss): 22
Best train_loss           : 0.0980
Metric         Paper    VerA    Diff
----------------------------------------
Accuracy       77.60   75.36  -2.24
Recall_m       70.79   69.54  -1.25
KS             41.58   39.07  -2.51
G-mean         69.37   68.48  -0.89

#### 6.3 VerA — Test year 2019

In [101]:
%cd /content/ACRF-RNN/Code
!python main_vera.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2019 --max-epoch 800 --wait-epoch 150 --device 0 \
    2>&1 | tee /content/project_outputs/run_vera_2019.log

/content/ACRF-RNN/Code
\nACRF-RNN VerA | test_year=2019 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018] (8 years)
Eval  : [2013, 2014, 2015, 2017, 2018, 2019]
Train labels: fraud=987, benign=2941
Model params: 972,937\n
  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
   0 |  0.4150 | 0.5553 | 0.5621 | 0.5400 | 0.0801 | 0.5385 | best
  --> [  0.1%] ep 1/800 | elapsed 0s | ETA 361s | best loss 0.4150 @ ep0 | wait 0/150
   1 |  0.3941 | 0.4956 | 0.5153 | 0.5034 | 0.0068 | 0.5029 | best
  --> [  0.2%] ep 2/800 | elapsed 1s | ETA 205s | best loss 0.3941 @ ep1 | wait 0/150
   2 |  0.3786 | 0.5485 | 0.6191 | 0.5929 | 0.1859 | 0.5910 | best
  --> [  0.4%] ep 3/800 | elapsed 1s | ETA 152s | best loss 0.3786 @ ep2 | wait 0/150
   3 |  0.3260 | 0.6144 | 0.5682 | 0.5860 | 0.1720 | 0.5851 | best
  --> [  0.5%] ep 4/800 | elapsed 1s | ETA 126s | best loss 0.3260 @ ep3 | wait 0/150
   4 |  0.2711 | 0.6979 | 0.7128 | 0.6792 | 0.3583 | 0.6764 | best
  --> [  0.6%] ep 5/800 | elapsed 1s | ETA 111s | best loss 0.2711 @ ep4 | wait 0/150
   5 |  0.2395 | 0.7502 | 0.7413 | 0.6975 | 0.3951 | 0.6930 | best
  --> [  0.8%] ep 6/800 | elapsed 1s | ETA 101s | best loss 0.2395 @ ep5 | wait 0/150
   6 |  0.2115 | 0.8018 | 0.7597 | 0.6964 | 0.3928 | 0.6869 | best
  --> [  0.9%] ep 7/800 | elapsed 1s | ETA 93s | best loss 0.2115 @ ep6 | wait 0/150
   7 |  0.1921 | 0.8371 | 0.7475 | 0.6821 | 0.3642 | 0.6717 | best
  --> [  1.0%] ep 8/800 | elapsed 1s | ETA 88s | best loss 0.1921 @ ep7 | wait 0/150
   8 |  0.1820 | 0.8500 | 0.7454 | 0.6808 | 0.3615 | 0.6706 | best
  --> [  1.1%] ep 9/800 | elapsed 1s | ETA 84s | best loss 0.1820 @ ep8 | wait 0/150
   9 |  0.3537 | 0.6402 | 0.7454 | 0.6872 | 0.3745 | 0.6791 |
  --> [  1.2%] ep 10/800 | elapsed 1s | ETA 82s | best loss 0.1820 @ ep8 | wait 1/150
  10 |  0.1972 | 0.8215 | 0.7230 | 0.6599 | 0.3197 | 0.6499 |
  11 |  0.1700 | 0.8527 | 0.6538 | 0.5635 | 0.1270 | 0.5393 | best
  --> [  1.5%] ep 12/800 | elapsed 1s | ETA 76s | best loss 0.1700 @ ep11 | wait 0/150
  12 |  0.1681 | 0.8574 | 0.7189 | 0.6508 | 0.3016 | 0.6389 | best
  --> [  1.6%] ep 13/800 | elapsed 1s | ETA 74s | best loss 0.1681 @ ep12 | wait 0/150
  13 |  0.1648 | 0.8642 | 0.7454 | 0.6808 | 0.3615 | 0.6706 | best
  --> [  1.8%] ep 14/800 | elapsed 1s | ETA 72s | best loss 0.1648 @ ep13 | wait 0/150
  14 |  0.1548 | 0.8866 | 0.7536 | 0.6893 | 0.3785 | 0.6793 | best
  --> [  1.9%] ep 15/800 | elapsed 1s | ETA 70s | best loss 0.1548 @ ep14 | wait 0/150
  15 |  0.1513 | 0.8968 | 0.7658 | 0.7068 | 0.4136 | 0.6987 | best
  --> [  2.0%] ep 16/800 | elapsed 1s | ETA 68s | best loss 0.1513 @ ep15 | wait 0/150
  16 |  0.1462 | 0.9104 | 0.7780 | 0.7212 | 0.4423 | 0.7138 | best
  --> [  2.1%] ep 17/800 | elapsed 1s | ETA 67s | best loss 0.1462 @ ep16 | wait 0/150
  17 |  0.1406 | 0.9280 | 0.7800 | 0.7257 | 0.4514 | 0.7190 | best
  --> [  2.2%] ep 18/800 | elapsed 2s | ETA 66s | best loss 0.1406 @ ep17 | wait 0/150
  18 |  0.1351 | 0.9314 | 0.7780 | 0.7373 | 0.4747 | 0.7336 | best
  --> [  2.4%] ep 19/800 | elapsed 2s | ETA 65s | best loss 0.1351 @ ep18 | wait 0/150
  19 |  0.1389 | 0.9185 | 0.7719 | 0.7205 | 0.4409 | 0.7144 |
  --> [  2.5%] ep 20/800 | elapsed 2s | ETA 64s | best loss 0.1351 @ ep18 | wait 1/150
  20 |  0.3471 | 0.6395 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  21 |  0.1930 | 0.8371 | 0.7760 | 0.7393 | 0.4785 | 0.7363 |
  22 |  0.1694 | 0.8697 | 0.7719 | 0.7399 | 0.4797 | 0.7376 |
  23 |  0.1334 | 0.9179 | 0.7719 | 0.7399 | 0.4797 | 0.7376 | best
  --> [  3.0%] ep 24/800 | elapsed 2s | ETA 63s | best loss 0.1334 @ ep23 | wait 0/150
  24 |  0.2991 | 0.7108 | 0.7678 | 0.7308 | 0.4615 | 0.7277 |
  25 |  0.1500 | 0.8798 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
  26 |  0.1599 | 0.8649 | 0.7678 | 0.7340 | 0.4680 | 0.7314 |
  27 |  0.1744 | 0.8418 | 0.7210 | 0.6489 | 0.2977 | 0.6356 |
  28 |  0.1835 | 0.8242 | 0.7067 | 0.6203 | 0.2405 | 0.6002 |
  29 |  0.1968 | 0.8038 | 0.7026 | 0.6176 | 0.2353 | 0.5981 |
  --> [  3.8%] ep 30/800 | elapsed 2s | ETA 59s | best loss 0.1334 @ ep23 | wait 6/150
  30 |  0.1983 | 0.8038 | 0.7067 | 0.6235 | 0.2470 | 0.6050 |
  31 |  0.1968 | 0.8072 | 0.7108 | 0.6294 | 0.2587 | 0.6118 |
  32 |  0.1851 | 0.8282 | 0.7128 | 0.6307 | 0.2613 | 0.6129 |
  33 |  0.1806 | 0.8405 | 0.7210 | 0.6392 | 0.2783 | 0.6217 |
  34 |  0.1721 | 0.8527 | 0.7434 | 0.6730 | 0.3460 | 0.6608 |
  35 |  0.1715 | 0.8500 | 0.3890 | 0.4770 | 0.0461 | 0.4496 |
  36 |  0.1745 | 0.8391 | 0.4033 | 0.4926 | 0.0147 | 0.4653 |
  37 |  0.2383 | 0.7502 | 0.7515 | 0.6847 | 0.3694 | 0.6739 |
  38 |  0.1804 | 0.8316 | 0.7230 | 0.6599 | 0.3197 | 0.6499 |
  39 |  0.1755 | 0.8350 | 0.7515 | 0.6912 | 0.3823 | 0.6825 |
  --> [  5.0%] ep 40/800 | elapsed 3s | ETA 55s | best loss 0.1334 @ ep23 | wait 16/150
  40 |  0.1711 | 0.8445 | 0.7637 | 0.7055 | 0.4110 | 0.6976 |
  41 |  0.1669 | 0.8561 | 0.7597 | 0.6997 | 0.3993 | 0.6912 |
  42 |  0.1648 | 0.8669 | 0.7576 | 0.6822 | 0.3644 | 0.6683 |
  43 |  0.1627 | 0.8703 | 0.7556 | 0.6776 | 0.3553 | 0.6627 |
  44 |  0.1646 | 0.8547 | 0.7556 | 0.6776 | 0.3553 | 0.6627 |
  45 |  0.1616 | 0.8663 | 0.7637 | 0.6893 | 0.3787 | 0.6760 |
  46 |  0.1579 | 0.8778 | 0.7739 | 0.7121 | 0.4241 | 0.7032 |
  47 |  0.1540 | 0.8880 | 0.7800 | 0.7257 | 0.4514 | 0.7190 |
  48 |  0.1507 | 0.8934 | 0.7800 | 0.7289 | 0.4579 | 0.7230 |
  49 |  0.1480 | 0.8975 | 0.7800 | 0.7289 | 0.4579 | 0.7230 |
  --> [  6.2%] ep 50/800 | elapsed 4s | ETA 53s | best loss 0.1334 @ ep23 | wait 26/150
  50 |  0.1445 | 0.9029 | 0.7739 | 0.7218 | 0.4435 | 0.7156 |
  51 |  0.1414 | 0.9022 | 0.7699 | 0.7191 | 0.4383 | 0.7133 |
  52 |  0.1494 | 0.8846 | 0.7699 | 0.7159 | 0.4318 | 0.7092 |
  53 |  0.1417 | 0.8955 | 0.7699 | 0.7159 | 0.4318 | 0.7092 |
  54 |  0.1452 | 0.8893 | 0.7719 | 0.7140 | 0.4280 | 0.7062 |
  55 |  0.1438 | 0.8934 | 0.7658 | 0.7004 | 0.4007 | 0.6903 |
  56 |  0.1425 | 0.8914 | 0.7658 | 0.7036 | 0.4072 | 0.6945 |
  57 |  0.1418 | 0.8961 | 0.7678 | 0.7146 | 0.4292 | 0.7081 |
  58 |  0.1358 | 0.9151 | 0.7699 | 0.7159 | 0.4318 | 0.7092 |
  59 |  0.1332 | 0.9131 | 0.7719 | 0.7172 | 0.4345 | 0.7104 | best
  --> [  7.5%] ep 60/800 | elapsed 4s | ETA 51s | best loss 0.1332 @ ep59 | wait 0/150
  60 |  0.1355 | 0.9050 | 0.7739 | 0.7218 | 0.4435 | 0.7156 |
  61 |  0.1403 | 0.8961 | 0.7821 | 0.7367 | 0.4734 | 0.7321 |
  62 |  0.1276 | 0.9151 | 0.7841 | 0.7380 | 0.4761 | 0.7333 | best
  --> [  7.9%] ep 63/800 | elapsed 4s | ETA 51s | best loss 0.1276 @ ep62 | wait 0/150
  63 |  0.1472 | 0.8839 | 0.7862 | 0.7393 | 0.4787 | 0.7345 |
  64 |  0.1392 | 0.9022 | 0.7800 | 0.7354 | 0.4708 | 0.7309 |
  65 |  0.1302 | 0.9131 | 0.7760 | 0.7263 | 0.4526 | 0.7207 |
  66 |  0.1284 | 0.9185 | 0.7760 | 0.7328 | 0.4656 | 0.7286 |
  67 |  0.1260 | 0.9246 | 0.7699 | 0.7288 | 0.4577 | 0.7251 | best
  --> [  8.5%] ep 68/800 | elapsed 5s | ETA 50s | best loss 0.1260 @ ep67 | wait 0/150
  68 |  0.1236 | 0.9348 | 0.7719 | 0.7302 | 0.4603 | 0.7262 | best
  --> [  8.6%] ep 69/800 | elapsed 5s | ETA 50s | best loss 0.1236 @ ep68 | wait 0/150
  69 |  0.1208 | 0.9375 | 0.7760 | 0.7328 | 0.4656 | 0.7286 | best
  --> [  8.8%] ep 70/800 | elapsed 5s | ETA 50s | best loss 0.1208 @ ep69 | wait 0/150
  70 |  0.1194 | 0.9341 | 0.7800 | 0.7354 | 0.4708 | 0.7309 | best
  --> [  8.9%] ep 71/800 | elapsed 5s | ETA 49s | best loss 0.1194 @ ep70 | wait 0/150
  71 |  0.1189 | 0.9328 | 0.7800 | 0.7354 | 0.4708 | 0.7309 | best
  --> [  9.0%] ep 72/800 | elapsed 5s | ETA 49s | best loss 0.1189 @ ep71 | wait 0/150
  72 |  0.1194 | 0.9321 | 0.7780 | 0.7341 | 0.4682 | 0.7298 |
  73 |  0.1187 | 0.9341 | 0.7760 | 0.7296 | 0.4591 | 0.7247 | best
  --> [  9.2%] ep 74/800 | elapsed 5s | ETA 49s | best loss 0.1187 @ ep73 | wait 0/150
  74 |  0.1168 | 0.9382 | 0.7800 | 0.7354 | 0.4708 | 0.7309 | best
  --> [  9.4%] ep 75/800 | elapsed 5s | ETA 49s | best loss 0.1168 @ ep74 | wait 0/150
  75 |  0.1148 | 0.9423 | 0.7780 | 0.7341 | 0.4682 | 0.7298 | best
  --> [  9.5%] ep 76/800 | elapsed 5s | ETA 49s | best loss 0.1148 @ ep75 | wait 0/150
  76 |  0.1136 | 0.9437 | 0.7760 | 0.7328 | 0.4656 | 0.7286 | best
  --> [  9.6%] ep 77/800 | elapsed 5s | ETA 49s | best loss 0.1136 @ ep76 | wait 0/150
  77 |  0.1126 | 0.9464 | 0.7821 | 0.7400 | 0.4799 | 0.7360 | best
  --> [  9.8%] ep 78/800 | elapsed 5s | ETA 49s | best loss 0.1126 @ ep77 | wait 0/150
  78 |  0.1117 | 0.9457 | 0.7780 | 0.7341 | 0.4682 | 0.7298 | best
  --> [  9.9%] ep 79/800 | elapsed 5s | ETA 48s | best loss 0.1117 @ ep78 | wait 0/150
  79 |  0.1111 | 0.9464 | 0.7821 | 0.7400 | 0.4799 | 0.7360 | best
  --> [ 10.0%] ep 80/800 | elapsed 5s | ETA 48s | best loss 0.1111 @ ep79 | wait 0/150
  80 |  0.1106 | 0.9491 | 0.7821 | 0.7400 | 0.4799 | 0.7360 | best
  --> [ 10.1%] ep 81/800 | elapsed 5s | ETA 48s | best loss 0.1106 @ ep80 | wait 0/150
  81 |  0.1098 | 0.9504 | 0.7800 | 0.7386 | 0.4773 | 0.7348 | best
  --> [ 10.2%] ep 82/800 | elapsed 5s | ETA 48s | best loss 0.1098 @ ep81 | wait 0/150
  82 |  0.1087 | 0.9525 | 0.7800 | 0.7386 | 0.4773 | 0.7348 | best
  --> [ 10.4%] ep 83/800 | elapsed 6s | ETA 48s | best loss 0.1087 @ ep82 | wait 0/150
  83 |  0.1081 | 0.9532 | 0.7760 | 0.7360 | 0.4720 | 0.7324 | best
  --> [ 10.5%] ep 84/800 | elapsed 6s | ETA 48s | best loss 0.1081 @ ep83 | wait 0/150
  84 |  0.1080 | 0.9532 | 0.7760 | 0.7360 | 0.4720 | 0.7324 | best
  --> [ 10.6%] ep 85/800 | elapsed 6s | ETA 48s | best loss 0.1080 @ ep84 | wait 0/150
  85 |  0.1077 | 0.9532 | 0.7760 | 0.7360 | 0.4720 | 0.7324 | best
  --> [ 10.8%] ep 86/800 | elapsed 6s | ETA 47s | best loss 0.1077 @ ep85 | wait 0/150
  86 |  0.1069 | 0.9532 | 0.7780 | 0.7373 | 0.4747 | 0.7336 | best
  --> [ 10.9%] ep 87/800 | elapsed 6s | ETA 47s | best loss 0.1069 @ ep86 | wait 0/150
  87 |  0.1059 | 0.9538 | 0.7760 | 0.7360 | 0.4720 | 0.7324 | best
  --> [ 11.0%] ep 88/800 | elapsed 6s | ETA 47s | best loss 0.1059 @ ep87 | wait 0/150
  88 |  0.1045 | 0.9538 | 0.7719 | 0.7334 | 0.4668 | 0.7301 | best
  --> [ 11.1%] ep 89/800 | elapsed 6s | ETA 47s | best loss 0.1045 @ ep88 | wait 0/150
  89 |  0.1056 | 0.9525 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  --> [ 11.2%] ep 90/800 | elapsed 6s | ETA 47s | best loss 0.1045 @ ep88 | wait 1/150
  90 |  0.1049 | 0.9545 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  91 |  0.1041 | 0.9552 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 11.5%] ep 92/800 | elapsed 6s | ETA 47s | best loss 0.1041 @ ep91 | wait 0/150
  92 |  0.1037 | 0.9566 | 0.7719 | 0.7366 | 0.4733 | 0.7338 | best
  --> [ 11.6%] ep 93/800 | elapsed 6s | ETA 47s | best loss 0.1037 @ ep92 | wait 0/150
  93 |  0.1038 | 0.9538 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
  94 |  0.1037 | 0.9538 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 11.9%] ep 95/800 | elapsed 6s | ETA 47s | best loss 0.1037 @ ep94 | wait 0/150
  95 |  0.1034 | 0.9559 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 12.0%] ep 96/800 | elapsed 6s | ETA 46s | best loss 0.1034 @ ep95 | wait 0/150
  96 |  0.1032 | 0.9572 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 12.1%] ep 97/800 | elapsed 6s | ETA 46s | best loss 0.1032 @ ep96 | wait 0/150
  97 |  0.1027 | 0.9579 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 12.2%] ep 98/800 | elapsed 6s | ETA 46s | best loss 0.1027 @ ep97 | wait 0/150
  98 |  0.1030 | 0.9566 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  99 |  0.1023 | 0.9579 | 0.7719 | 0.7334 | 0.4668 | 0.7301 | best
  --> [ 12.5%] ep 100/800 | elapsed 7s | ETA 46s | best loss 0.1023 @ ep99 | wait 0/150
 100 |  0.1020 | 0.9579 | 0.7719 | 0.7334 | 0.4668 | 0.7301 | best
  --> [ 12.6%] ep 101/800 | elapsed 7s | ETA 46s | best loss 0.1020 @ ep100 | wait 0/150
 101 |  0.1017 | 0.9579 | 0.7699 | 0.7321 | 0.4642 | 0.7289 | best
  --> [ 12.8%] ep 102/800 | elapsed 7s | ETA 46s | best loss 0.1017 @ ep101 | wait 0/150
 102 |  0.1014 | 0.9579 | 0.7719 | 0.7334 | 0.4668 | 0.7301 | best
  --> [ 12.9%] ep 103/800 | elapsed 7s | ETA 46s | best loss 0.1014 @ ep102 | wait 0/150
 103 |  0.1012 | 0.9599 | 0.7739 | 0.7412 | 0.4823 | 0.7388 | best
  --> [ 13.0%] ep 104/800 | elapsed 7s | ETA 46s | best loss 0.1012 @ ep103 | wait 0/150
 104 |  0.2471 | 0.7475 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
 105 |  0.1011 | 0.9599 | 0.7719 | 0.7366 | 0.4733 | 0.7338 | best
  --> [ 13.2%] ep 106/800 | elapsed 7s | ETA 46s | best loss 0.1011 @ ep105 | wait 0/150
 106 |  0.1007 | 0.9599 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 13.4%] ep 107/800 | elapsed 7s | ETA 45s | best loss 0.1007 @ ep106 | wait 0/150
 107 |  0.1002 | 0.9606 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 13.5%] ep 108/800 | elapsed 7s | ETA 45s | best loss 0.1002 @ ep107 | wait 0/150
 108 |  0.1002 | 0.9613 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 13.6%] ep 109/800 | elapsed 7s | ETA 45s | best loss 0.1002 @ ep108 | wait 0/150
 109 |  0.0999 | 0.9627 | 0.7739 | 0.7379 | 0.4759 | 0.7351 | best
  --> [ 13.8%] ep 110/800 | elapsed 7s | ETA 45s | best loss 0.0999 @ ep109 | wait 0/150
 110 |  0.0999 | 0.9627 | 0.7739 | 0.7412 | 0.4823 | 0.7388 |
 111 |  0.1023 | 0.9599 | 0.7739 | 0.7412 | 0.4823 | 0.7388 |
 112 |  0.1004 | 0.9627 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 113 |  0.1008 | 0.9633 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 114 |  0.1013 | 0.9633 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 115 |  0.1016 | 0.9640 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 116 |  0.1019 | 0.9654 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 117 |  0.1103 | 0.9620 | 0.7760 | 0.7393 | 0.4785 | 0.7363 |
 118 |  0.1125 | 0.9627 | 0.7800 | 0.7419 | 0.4838 | 0.7386 |
 119 |  0.1496 | 0.8988 | 0.7800 | 0.7419 | 0.4838 | 0.7386 |
  --> [ 15.0%] ep 120/800 | elapsed 8s | ETA 46s | best loss 0.0999 @ ep109 | wait 10/150
 120 |  0.1601 | 0.8812 | 0.7536 | 0.6569 | 0.3138 | 0.6332 |
 121 |  0.1221 | 0.9226 | 0.7678 | 0.7308 | 0.4615 | 0.7277 |
 122 |  0.2842 | 0.7312 | 0.7800 | 0.7451 | 0.4902 | 0.7424 |
 123 |  0.3665 | 0.6592 | 0.7780 | 0.7438 | 0.4876 | 0.7412 |
 124 |  0.3649 | 0.6463 | 0.7780 | 0.7438 | 0.4876 | 0.7412 |
 125 |  0.3848 | 0.5961 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 126 |  0.3638 | 0.6137 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 127 |  0.3420 | 0.6361 | 0.7739 | 0.7412 | 0.4823 | 0.7388 |
 128 |  0.3591 | 0.6395 | 0.7719 | 0.7399 | 0.4797 | 0.7376 |
 129 |  0.2599 | 0.7400 | 0.7699 | 0.7385 | 0.4771 | 0.7364 |
  --> [ 16.2%] ep 130/800 | elapsed 9s | ETA 46s | best loss 0.0999 @ ep109 | wait 20/150
 130 |  0.2750 | 0.7060 | 0.7699 | 0.7385 | 0.4771 | 0.7364 |
 131 |  0.2650 | 0.7088 | 0.7699 | 0.7418 | 0.4836 | 0.7400 |
 132 |  0.2356 | 0.7413 | 0.7678 | 0.7405 | 0.4809 | 0.7388 |
 133 |  0.2593 | 0.7189 | 0.7699 | 0.7418 | 0.4836 | 0.7400 |
 134 |  0.2679 | 0.7346 | 0.6802 | 0.5935 | 0.1870 | 0.5723 |
 135 |  0.3051 | 0.6959 | 0.5316 | 0.4266 | 0.1468 | 0.3818 |
 136 |  0.2849 | 0.7183 | 0.7393 | 0.6704 | 0.3407 | 0.6586 |
 137 |  0.2846 | 0.6993 | 0.7658 | 0.7359 | 0.4718 | 0.7339 |
 138 |  0.2244 | 0.7733 | 0.7576 | 0.7307 | 0.4613 | 0.7290 |
 139 |  0.2307 | 0.7828 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
  --> [ 17.5%] ep 140/800 | elapsed 10s | ETA 46s | best loss 0.0999 @ ep109 | wait 30/150
 140 |  0.2353 | 0.7834 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 141 |  0.2310 | 0.7868 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 142 |  0.2134 | 0.8018 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 143 |  0.2121 | 0.8024 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 144 |  0.2119 | 0.8024 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 145 |  0.2114 | 0.8038 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 146 |  0.2112 | 0.8038 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 147 |  0.2108 | 0.8045 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 148 |  0.2104 | 0.8052 | 0.7719 | 0.7463 | 0.4927 | 0.7449 |
 149 |  0.2104 | 0.8045 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
  --> [ 18.8%] ep 150/800 | elapsed 11s | ETA 46s | best loss 0.0999 @ ep109 | wait 40/150
 150 |  0.2102 | 0.8038 | 0.7678 | 0.7437 | 0.4874 | 0.7424 |
 151 |  0.2102 | 0.8024 | 0.7678 | 0.7437 | 0.4874 | 0.7424 |
 152 |  0.2098 | 0.8031 | 0.7678 | 0.7437 | 0.4874 | 0.7424 |
 153 |  0.2090 | 0.8038 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 154 |  0.2080 | 0.8072 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 155 |  0.2075 | 0.8065 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 156 |  0.2077 | 0.8058 | 0.7617 | 0.7398 | 0.4795 | 0.7387 |
 157 |  0.2077 | 0.8052 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 158 |  0.2079 | 0.8052 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 159 |  0.2077 | 0.8045 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
  --> [ 20.0%] ep 160/800 | elapsed 12s | ETA 47s | best loss 0.0999 @ ep109 | wait 50/150
 160 |  0.2075 | 0.8052 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 161 |  0.2072 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 162 |  0.2072 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 163 |  0.2071 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 164 |  0.2071 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 165 |  0.2069 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 166 |  0.2068 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 167 |  0.2068 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 168 |  0.2067 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 169 |  0.2067 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
  --> [ 21.2%] ep 170/800 | elapsed 12s | ETA 45s | best loss 0.0999 @ ep109 | wait 60/150
 170 |  0.2067 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 171 |  0.2066 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 172 |  0.2065 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 173 |  0.2064 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 174 |  0.2064 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 175 |  0.2062 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 176 |  0.2060 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 177 |  0.2059 | 0.8086 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 178 |  0.2063 | 0.8065 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 179 |  0.2057 | 0.8086 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
  --> [ 22.5%] ep 180/800 | elapsed 13s | ETA 44s | best loss 0.0999 @ ep109 | wait 70/150
 180 |  0.2055 | 0.8072 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 181 |  0.2054 | 0.8086 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 182 |  0.2051 | 0.8092 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 183 |  0.2049 | 0.8092 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 184 |  0.2047 | 0.8099 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 185 |  0.2046 | 0.8099 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 186 |  0.2047 | 0.8086 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 187 |  0.2046 | 0.8086 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 188 |  0.2045 | 0.8086 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 189 |  0.2046 | 0.8092 | 0.7617 | 0.7365 | 0.4731 | 0.7351 |
  --> [ 23.8%] ep 190/800 | elapsed 13s | ETA 43s | best loss 0.0999 @ ep109 | wait 80/150
 190 |  0.2041 | 0.8092 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 191 |  0.2040 | 0.8099 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 192 |  0.2039 | 0.8099 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 193 |  0.2036 | 0.8119 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 194 |  0.2034 | 0.8106 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 195 |  0.2032 | 0.8119 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 196 |  0.2028 | 0.8119 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 197 |  0.2027 | 0.8119 | 0.7678 | 0.7405 | 0.4809 | 0.7388 |
 198 |  0.2024 | 0.8126 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 199 |  0.2017 | 0.8133 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
  --> [ 25.0%] ep 200/800 | elapsed 14s | ETA 42s | best loss 0.0999 @ ep109 | wait 90/150
 200 |  0.2017 | 0.8133 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 201 |  0.2015 | 0.8153 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 202 |  0.2025 | 0.8126 | 0.7719 | 0.7431 | 0.4862 | 0.7413 |
 203 |  0.2012 | 0.8153 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 204 |  0.2022 | 0.8126 | 0.7617 | 0.7365 | 0.4731 | 0.7351 |
 205 |  0.2072 | 0.8106 | 0.7556 | 0.7294 | 0.4587 | 0.7278 |
 206 |  0.2048 | 0.8086 | 0.7556 | 0.7261 | 0.4523 | 0.7242 |

#### 6.4 VerA — Test year 2020

In [102]:
%cd /content/ACRF-RNN/Code
!python main_vera.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2020 --max-epoch 800 --wait-epoch 150 --device 0 \
    2>&1 | tee /content/project_outputs/run_vera_2020.log

/content/ACRF-RNN/Code
\nACRF-RNN VerA | test_year=2020 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019] (9 years)
Eval  : [2014, 2015, 2017, 2018, 2019, 2020]
Train labels: fraud=1097, benign=3322
Model params: 972,937\n
  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
   0 |  0.4064 | 0.5738 | 0.5764 | 0.4868 | 0.0265 | 0.4668 | best
  --> [  0.1%] ep 1/800 | elapsed 1s | ETA 535s | best loss 0.4064 @ ep0 | wait 0/150
   1 |  0.3938 | 0.4980 | 0.5519 | 0.5406 | 0.0813 | 0.5404 | best
  --> [  0.2%] ep 2/800 | elapsed 1s | ETA 321s | best loss 0.3938 @ ep1 | wait 0/150
   2 |  0.4133 | 0.5346 | 0.5764 | 0.5692 | 0.1384 | 0.5691 |
   3 |  0.3820 | 0.4939 | 0.5621 | 0.5560 | 0.1119 | 0.5559 | best
  --> [  0.5%] ep 4/800 | elapsed 1s | ETA 209s | best loss 0.3820 @ ep3 | wait 0/150
   4 |  0.3734 | 0.5362 | 0.5723 | 0.5759 | 0.1518 | 0.5759 | best
  --> [  0.6%] ep 5/800 | elapsed 1s | ETA 193s | best loss 0.3734 @ ep4 | wait 0/150
   5 |  0.3465 | 0.5789 | 0.5743 | 0.5680 | 0.1359 | 0.5679 | best
  --> [  0.8%] ep 6/800 | elapsed 1s | ETA 181s | best loss 0.3465 @ ep5 | wait 0/150
   6 |  0.3683 | 0.5494 | 0.6253 | 0.6080 | 0.2160 | 0.6074 |
   7 |  0.3503 | 0.5524 | 0.6232 | 0.5884 | 0.1769 | 0.5860 |
   8 |  0.3677 | 0.5713 | 0.6436 | 0.5962 | 0.1924 | 0.5917 |
   9 |  0.3219 | 0.6217 | 0.6599 | 0.6198 | 0.2396 | 0.6167 | best
  --> [  1.2%] ep 10/800 | elapsed 2s | ETA 142s | best loss 0.3219 @ ep9 | wait 0/150
  10 |  0.2872 | 0.6736 | 0.6619 | 0.6119 | 0.2238 | 0.6070 | best
  --> [  1.4%] ep 11/800 | elapsed 2s | ETA 135s | best loss 0.2872 @ ep10 | wait 0/150
  11 |  0.4087 | 0.5290 | 0.6640 | 0.5627 | 0.1255 | 0.5408 |
  12 |  0.2999 | 0.6609 | 0.4358 | 0.4062 | 0.1877 | 0.4036 |
  13 |  0.2716 | 0.6940 | 0.5580 | 0.5031 | 0.0063 | 0.4960 | best
  --> [  1.8%] ep 14/800 | elapsed 2s | ETA 119s | best loss 0.2716 @ ep13 | wait 0/150
  14 |  0.3906 | 0.5672 | 0.5866 | 0.5250 | 0.0500 | 0.5164 |
  15 |  0.3353 | 0.5820 | 0.6741 | 0.6239 | 0.2477 | 0.6191 |
  16 |  0.3087 | 0.6263 | 0.5255 | 0.4513 | 0.0974 | 0.4367 |
  17 |  0.2646 | 0.6976 | 0.6986 | 0.6524 | 0.3049 | 0.6485 | best
  --> [  2.2%] ep 18/800 | elapsed 2s | ETA 105s | best loss 0.2646 @ ep17 | wait 0/150
  18 |  0.3088 | 0.6548 | 0.6436 | 0.5870 | 0.1741 | 0.5805 |
  19 |  0.3620 | 0.5952 | 0.6273 | 0.5405 | 0.0811 | 0.5238 |
  --> [  2.5%] ep 20/800 | elapsed 3s | ETA 101s | best loss 0.2646 @ ep17 | wait 2/150
  20 |  0.3017 | 0.6421 | 0.6273 | 0.5451 | 0.0902 | 0.5302 |
  21 |  0.3105 | 0.6431 | 0.6415 | 0.6545 | 0.3090 | 0.6542 |
  22 |  0.2609 | 0.7189 | 0.6558 | 0.5807 | 0.1614 | 0.5691 | best
  --> [  2.9%] ep 23/800 | elapsed 3s | ETA 95s | best loss 0.2609 @ ep22 | wait 0/150
  23 |  0.2338 | 0.7597 | 0.6640 | 0.6452 | 0.2904 | 0.6445 | best
  --> [  3.0%] ep 24/800 | elapsed 3s | ETA 94s | best loss 0.2338 @ ep23 | wait 0/150
  24 |  0.3517 | 0.5967 | 0.6273 | 0.5222 | 0.0444 | 0.4965 |
  25 |  0.4018 | 0.5489 | 0.6680 | 0.6019 | 0.2037 | 0.5932 |
  26 |  0.3140 | 0.6507 | 0.6864 | 0.6588 | 0.3175 | 0.6574 |
  27 |  0.4734 | 0.4236 | 0.5825 | 0.6141 | 0.2282 | 0.6122 |
  28 |  0.3011 | 0.6431 | 0.6599 | 0.5603 | 0.1206 | 0.5389 |
  29 |  0.2840 | 0.6787 | 0.7189 | 0.6831 | 0.3662 | 0.6809 |
  --> [  3.8%] ep 30/800 | elapsed 3s | ETA 86s | best loss 0.2338 @ ep23 | wait 6/150
  30 |  0.2089 | 0.7979 | 0.7332 | 0.6872 | 0.3743 | 0.6835 | best
  --> [  3.9%] ep 31/800 | elapsed 3s | ETA 85s | best loss 0.2089 @ ep30 | wait 0/150
  31 |  0.2002 | 0.8208 | 0.7617 | 0.6999 | 0.3997 | 0.6934 | best
  --> [  4.0%] ep 32/800 | elapsed 4s | ETA 84s | best loss 0.2002 @ ep31 | wait 0/150
  32 |  0.2063 | 0.8162 | 0.7413 | 0.6692 | 0.3384 | 0.6599 |
  33 |  0.1789 | 0.8605 | 0.7699 | 0.7002 | 0.4004 | 0.6920 | best
  --> [  4.2%] ep 34/800 | elapsed 4s | ETA 83s | best loss 0.1789 @ ep33 | wait 0/150
  34 |  0.1821 | 0.8462 | 0.7739 | 0.7073 | 0.4145 | 0.6998 |
  35 |  0.1862 | 0.8437 | 0.7658 | 0.7023 | 0.4047 | 0.6955 |
  36 |  0.1777 | 0.8513 | 0.7597 | 0.6895 | 0.3789 | 0.6809 | best
  --> [  4.6%] ep 37/800 | elapsed 4s | ETA 81s | best loss 0.1777 @ ep36 | wait 0/150
  37 |  0.2185 | 0.8187 | 0.7719 | 0.7106 | 0.4212 | 0.7043 |
  38 |  0.1759 | 0.8569 | 0.7780 | 0.7143 | 0.4286 | 0.7076 | best
  --> [  4.9%] ep 39/800 | elapsed 4s | ETA 80s | best loss 0.1759 @ ep38 | wait 0/150
  39 |  0.1719 | 0.8630 | 0.6884 | 0.5776 | 0.1551 | 0.5518 | best
  --> [  5.0%] ep 40/800 | elapsed 4s | ETA 79s | best loss 0.1719 @ ep39 | wait 0/150
  40 |  0.1707 | 0.8666 | 0.7780 | 0.7143 | 0.4286 | 0.7076 | best
  --> [  5.1%] ep 41/800 | elapsed 4s | ETA 78s | best loss 0.1707 @ ep40 | wait 0/150
  41 |  0.1684 | 0.8722 | 0.7678 | 0.7036 | 0.4071 | 0.6966 | best
  --> [  5.2%] ep 42/800 | elapsed 4s | ETA 78s | best loss 0.1684 @ ep41 | wait 0/150
  42 |  0.1720 | 0.8564 | 0.7678 | 0.7036 | 0.4071 | 0.6966 |
  43 |  0.1634 | 0.8666 | 0.4644 | 0.5562 | 0.1125 | 0.5380 | best
  --> [  5.5%] ep 44/800 | elapsed 4s | ETA 77s | best loss 0.1634 @ ep43 | wait 0/150
  44 |  0.1660 | 0.8691 | 0.6395 | 0.5296 | 0.0592 | 0.5019 |
  45 |  0.1660 | 0.8610 | 0.7312 | 0.6355 | 0.2711 | 0.6183 |
  46 |  0.1905 | 0.8360 | 0.7536 | 0.6674 | 0.3349 | 0.6541 |
  47 |  0.1539 | 0.8824 | 0.7678 | 0.7081 | 0.4163 | 0.7022 | best
  --> [  6.0%] ep 48/800 | elapsed 5s | ETA 75s | best loss 0.1539 @ ep47 | wait 0/150
  48 |  0.1563 | 0.8880 | 0.7719 | 0.6786 | 0.3571 | 0.6632 |
  49 |  0.1568 | 0.8905 | 0.5723 | 0.6034 | 0.2067 | 0.6015 |
  --> [  6.2%] ep 50/800 | elapsed 5s | ETA 74s | best loss 0.1539 @ ep47 | wait 2/150
  50 |  0.2225 | 0.7775 | 0.7678 | 0.7127 | 0.4254 | 0.7077 |
  51 |  0.1555 | 0.8824 | 0.7658 | 0.7069 | 0.4138 | 0.7011 |
  52 |  0.2912 | 0.7057 | 0.7495 | 0.7062 | 0.4124 | 0.7030 |
  53 |  0.1787 | 0.8483 | 0.7780 | 0.6914 | 0.3828 | 0.6784 |
  54 |  0.1875 | 0.8345 | 0.7678 | 0.7081 | 0.4163 | 0.7022 |
  55 |  0.1856 | 0.8411 | 0.7719 | 0.7152 | 0.4304 | 0.7098 |
  56 |  0.2445 | 0.7602 | 0.7719 | 0.7152 | 0.4304 | 0.7098 |
  57 |  0.2027 | 0.8126 | 0.7780 | 0.7189 | 0.4378 | 0.7131 |
  58 |  0.1848 | 0.8416 | 0.7862 | 0.7284 | 0.4568 | 0.7230 |
  59 |  0.1903 | 0.8335 | 0.7902 | 0.7309 | 0.4618 | 0.7251 |
  --> [  7.5%] ep 60/800 | elapsed 6s | ETA 71s | best loss 0.1539 @ ep47 | wait 12/150
  60 |  0.1622 | 0.8742 | 0.7862 | 0.7284 | 0.4568 | 0.7230 |
  61 |  0.1587 | 0.8854 | 0.7841 | 0.7272 | 0.4543 | 0.7219 |
  62 |  0.1524 | 0.8865 | 0.7821 | 0.7259 | 0.4519 | 0.7208 | best
  --> [  7.9%] ep 63/800 | elapsed 6s | ETA 70s | best loss 0.1524 @ ep62 | wait 0/150
  63 |  0.2090 | 0.8035 | 0.7760 | 0.7222 | 0.4445 | 0.7175 |
  64 |  0.1668 | 0.8590 | 0.7576 | 0.6608 | 0.3215 | 0.6437 |
  65 |  0.1536 | 0.8798 | 0.7576 | 0.6608 | 0.3215 | 0.6437 |
  66 |  0.1697 | 0.8544 | 0.6965 | 0.5779 | 0.1558 | 0.5483 |
  67 |  0.1878 | 0.8259 | 0.7393 | 0.6267 | 0.2535 | 0.6023 |
  68 |  0.1742 | 0.8437 | 0.5051 | 0.5626 | 0.1252 | 0.5556 |
  69 |  0.1683 | 0.8574 | 0.7475 | 0.6592 | 0.3183 | 0.6450 |
  --> [  8.8%] ep 70/800 | elapsed 7s | ETA 68s | best loss 0.1524 @ ep62 | wait 7/150
  70 |  0.1612 | 0.8691 | 0.7576 | 0.6699 | 0.3398 | 0.6562 |
  71 |  0.1531 | 0.8834 | 0.7556 | 0.6824 | 0.3648 | 0.6731 |
  72 |  0.1513 | 0.8849 | 0.7637 | 0.6782 | 0.3564 | 0.6653 | best
  --> [  9.1%] ep 73/800 | elapsed 7s | ETA 67s | best loss 0.1513 @ ep72 | wait 0/150
  73 |  0.1547 | 0.8758 | 0.7617 | 0.6815 | 0.3631 | 0.6703 |
  74 |  0.1542 | 0.8747 | 0.5947 | 0.6169 | 0.2339 | 0.6160 |
  75 |  0.1634 | 0.8630 | 0.7515 | 0.6799 | 0.3599 | 0.6710 |
  76 |  0.1694 | 0.8569 | 0.7617 | 0.6999 | 0.3997 | 0.6934 |
  77 |  0.1492 | 0.8844 | 0.7658 | 0.7161 | 0.4321 | 0.7120 | best
  --> [  9.8%] ep 78/800 | elapsed 7s | ETA 66s | best loss 0.1492 @ ep77 | wait 0/150
  78 |  0.1445 | 0.8895 | 0.7739 | 0.7210 | 0.4420 | 0.7164 | best
  --> [  9.9%] ep 79/800 | elapsed 7s | ETA 66s | best loss 0.1445 @ ep78 | wait 0/150
  79 |  0.1475 | 0.8854 | 0.7719 | 0.7152 | 0.4304 | 0.7098 |
  --> [ 10.0%] ep 80/800 | elapsed 7s | ETA 66s | best loss 0.1445 @ ep78 | wait 1/150
  80 |  0.1940 | 0.8304 | 0.7678 | 0.7127 | 0.4254 | 0.7077 |
  81 |  0.1408 | 0.9038 | 0.7739 | 0.7164 | 0.4328 | 0.7109 | best
  --> [ 10.2%] ep 82/800 | elapsed 7s | ETA 65s | best loss 0.1408 @ ep81 | wait 0/150
  82 |  0.1464 | 0.8926 | 0.7637 | 0.7102 | 0.4205 | 0.7055 |
  83 |  0.1415 | 0.9007 | 0.7658 | 0.7115 | 0.4230 | 0.7066 |
  84 |  0.1439 | 0.8966 | 0.7678 | 0.7127 | 0.4254 | 0.7077 |
  85 |  0.1384 | 0.9053 | 0.7678 | 0.7127 | 0.4254 | 0.7077 | best
  --> [ 10.8%] ep 86/800 | elapsed 8s | ETA 65s | best loss 0.1384 @ ep85 | wait 0/150
  86 |  0.1350 | 0.9099 | 0.7678 | 0.7081 | 0.4163 | 0.7022 | best
  --> [ 10.9%] ep 87/800 | elapsed 8s | ETA 65s | best loss 0.1350 @ ep86 | wait 0/150
  87 |  0.2464 | 0.7821 | 0.7699 | 0.7094 | 0.4187 | 0.7032 |
  88 |  0.1282 | 0.9236 | 0.7760 | 0.7131 | 0.4262 | 0.7065 | best
  --> [ 11.1%] ep 89/800 | elapsed 8s | ETA 65s | best loss 0.1282 @ ep88 | wait 0/150
  89 |  0.1253 | 0.9328 | 0.7719 | 0.7106 | 0.4212 | 0.7043 | best
  --> [ 11.2%] ep 90/800 | elapsed 8s | ETA 64s | best loss 0.1253 @ ep89 | wait 0/150
  90 |  0.1215 | 0.9374 | 0.7678 | 0.7081 | 0.4163 | 0.7022 | best
  --> [ 11.4%] ep 91/800 | elapsed 8s | ETA 64s | best loss 0.1215 @ ep90 | wait 0/150
  91 |  0.1224 | 0.9364 | 0.7699 | 0.7094 | 0.4187 | 0.7032 |
  92 |  0.1236 | 0.9338 | 0.7719 | 0.7106 | 0.4212 | 0.7043 |
  93 |  0.1184 | 0.9455 | 0.7699 | 0.7094 | 0.4187 | 0.7032 | best
  --> [ 11.8%] ep 94/800 | elapsed 8s | ETA 64s | best loss 0.1184 @ ep93 | wait 0/150
  94 |  0.1197 | 0.9374 | 0.7617 | 0.7044 | 0.4089 | 0.6989 |
  95 |  0.1650 | 0.8732 | 0.7617 | 0.7044 | 0.4089 | 0.6989 |
  96 |  0.1191 | 0.9297 | 0.7597 | 0.7032 | 0.4064 | 0.6978 |
  97 |  0.1146 | 0.9420 | 0.7556 | 0.6962 | 0.3923 | 0.6901 | best
  --> [ 12.2%] ep 98/800 | elapsed 9s | ETA 63s | best loss 0.1146 @ ep97 | wait 0/150
  98 |  0.1123 | 0.9481 | 0.7536 | 0.6949 | 0.3898 | 0.6890 | best
  --> [ 12.4%] ep 99/800 | elapsed 9s | ETA 63s | best loss 0.1123 @ ep98 | wait 0/150
  99 |  0.1101 | 0.9445 | 0.7556 | 0.6962 | 0.3923 | 0.6901 | best
  --> [ 12.5%] ep 100/800 | elapsed 9s | ETA 63s | best loss 0.1101 @ ep99 | wait 0/150
 100 |  0.1154 | 0.9374 | 0.7556 | 0.6962 | 0.3923 | 0.6901 |
 101 |  0.1133 | 0.9394 | 0.7576 | 0.6974 | 0.3948 | 0.6912 |
 102 |  0.1128 | 0.9445 | 0.7536 | 0.6949 | 0.3898 | 0.6890 |
 103 |  0.1098 | 0.9532 | 0.7597 | 0.6986 | 0.3972 | 0.6923 | best
  --> [ 13.0%] ep 104/800 | elapsed 9s | ETA 62s | best loss 0.1098 @ ep103 | wait 0/150
 104 |  0.1070 | 0.9562 | 0.7597 | 0.6986 | 0.3972 | 0.6923 | best
  --> [ 13.1%] ep 105/800 | elapsed 9s | ETA 62s | best loss 0.1070 @ ep104 | wait 0/150
 105 |  0.1076 | 0.9511 | 0.7617 | 0.6999 | 0.3997 | 0.6934 |
 106 |  0.1063 | 0.9593 | 0.7597 | 0.6986 | 0.3972 | 0.6923 | best
  --> [ 13.4%] ep 107/800 | elapsed 10s | ETA 62s | best loss 0.1063 @ ep106 | wait 0/150
 107 |  0.1106 | 0.9404 | 0.7617 | 0.6999 | 0.3997 | 0.6934 |
 108 |  0.1051 | 0.9613 | 0.7576 | 0.6974 | 0.3948 | 0.6912 | best
  --> [ 13.6%] ep 109/800 | elapsed 10s | ETA 61s | best loss 0.1051 @ ep108 | wait 0/150
 109 |  0.1050 | 0.9603 | 0.7556 | 0.6962 | 0.3923 | 0.6901 | best
  --> [ 13.8%] ep 110/800 | elapsed 10s | ETA 61s | best loss 0.1050 @ ep109 | wait 0/150
 110 |  0.1048 | 0.9577 | 0.7597 | 0.6986 | 0.3972 | 0.6923 | best
  --> [ 13.9%] ep 111/800 | elapsed 10s | ETA 61s | best loss 0.1048 @ ep110 | wait 0/150
 111 |  0.1088 | 0.9516 | 0.7597 | 0.6986 | 0.3972 | 0.6923 |
 112 |  0.1185 | 0.9420 | 0.7617 | 0.6999 | 0.3997 | 0.6934 |
 113 |  0.1047 | 0.9603 | 0.7617 | 0.6999 | 0.3997 | 0.6934 | best
  --> [ 14.2%] ep 114/800 | elapsed 10s | ETA 61s | best loss 0.1047 @ ep113 | wait 0/150
 114 |  0.1046 | 0.9598 | 0.7617 | 0.6999 | 0.3997 | 0.6934 | best
  --> [ 14.4%] ep 115/800 | elapsed 10s | ETA 61s | best loss 0.1046 @ ep114 | wait 0/150
 115 |  0.1037 | 0.9638 | 0.7617 | 0.6999 | 0.3997 | 0.6934 | best
  --> [ 14.5%] ep 116/800 | elapsed 10s | ETA 60s | best loss 0.1037 @ ep115 | wait 0/150
 116 |  0.1036 | 0.9669 | 0.7617 | 0.6999 | 0.3997 | 0.6934 | best
  --> [ 14.6%] ep 117/800 | elapsed 10s | ETA 60s | best loss 0.1036 @ ep116 | wait 0/150
 117 |  0.1066 | 0.9654 | 0.7637 | 0.7011 | 0.4022 | 0.6944 |
 118 |  0.1031 | 0.9669 | 0.7637 | 0.7011 | 0.4022 | 0.6944 | best
  --> [ 14.9%] ep 119/800 | elapsed 10s | ETA 60s | best loss 0.1031 @ ep118 | wait 0/150
 119 |  0.1031 | 0.9644 | 0.7637 | 0.7011 | 0.4022 | 0.6944 | best
  --> [ 15.0%] ep 120/800 | elapsed 11s | ETA 60s | best loss 0.1031 @ ep119 | wait 0/150
 120 |  0.1438 | 0.8997 | 0.7658 | 0.7023 | 0.4047 | 0.6955 |
 121 |  0.1092 | 0.9476 | 0.7637 | 0.7011 | 0.4022 | 0.6944 |
 122 |  0.1018 | 0.9679 | 0.7658 | 0.7023 | 0.4047 | 0.6955 | best
  --> [ 15.4%] ep 123/800 | elapsed 11s | ETA 60s | best loss 0.1018 @ ep122 | wait 0/150
 123 |  0.1009 | 0.9689 | 0.7658 | 0.7023 | 0.4047 | 0.6955 | best
  --> [ 15.5%] ep 124/800 | elapsed 11s | ETA 59s | best loss 0.1009 @ ep123 | wait 0/150
 124 |  0.1032 | 0.9654 | 0.7637 | 0.7011 | 0.4022 | 0.6944 |
 125 |  0.1011 | 0.9684 | 0.7637 | 0.7011 | 0.4022 | 0.6944 |
 126 |  0.0989 | 0.9674 | 0.7780 | 0.7143 | 0.4286 | 0.7076 | best
  --> [ 15.9%] ep 127/800 | elapsed 11s | ETA 59s | best loss 0.0989 @ ep126 | wait 0/150
 127 |  0.1005 | 0.9659 | 0.7658 | 0.7023 | 0.4047 | 0.6955 |
 128 |  0.0999 | 0.9679 | 0.7719 | 0.7060 | 0.4121 | 0.6987 |
 129 |  0.0991 | 0.9705 | 0.7841 | 0.7134 | 0.4269 | 0.7051 |
  --> [ 16.2%] ep 130/800 | elapsed 11s | ETA 59s | best loss 0.0989 @ ep126 | wait 3/150
 130 |  0.0995 | 0.9669 | 0.7862 | 0.7147 | 0.4293 | 0.7062 |
 131 |  0.1012 | 0.9644 | 0.7862 | 0.7147 | 0.4293 | 0.7062 |
 132 |  0.1009 | 0.9659 | 0.7780 | 0.7097 | 0.4195 | 0.7019 |
 133 |  0.0989 | 0.9695 | 0.7739 | 0.7073 | 0.4145 | 0.6998 | best
  --> [ 16.8%] ep 134/800 | elapsed 12s | ETA 59s | best loss 0.0989 @ ep133 | wait 0/150
 134 |  0.0966 | 0.9715 | 0.7658 | 0.7023 | 0.4047 | 0.6955 | best
  --> [ 16.9%] ep 135/800 | elapsed 12s | ETA 59s | best loss 0.0966 @ ep134 | wait 0/150
 135 |  0.0959 | 0.9720 | 0.7617 | 0.6999 | 0.3997 | 0.6934 | best
  --> [ 17.0%] ep 136/800 | elapsed 12s | ETA 59s | best loss 0.0959 @ ep135 | wait 0/150
 136 |  0.0967 | 0.9705 | 0.7637 | 0.7011 | 0.4022 | 0.6944 |
 137 |  0.0975 | 0.9705 | 0.7637 | 0.7011 | 0.4022 | 0.6944 |
 138 |  0.0969 | 0.9720 | 0.7658 | 0.7023 | 0.4047 | 0.6955 |
 139 |  0.0954 | 0.9751 | 0.7678 | 0.7036 | 0.4071 | 0.6966 | best
  --> [ 17.5%] ep 140/800 | elapsed 12s | ETA 59s | best loss 0.0954 @ ep139 | wait 0/150
 140 |  0.0945 | 0.9761 | 0.7699 | 0.7048 | 0.4096 | 0.6976 | best
  --> [ 17.6%] ep 141/800 | elapsed 13s | ETA 59s | best loss 0.0945 @ ep140 | wait 0/150
 141 |  0.0979 | 0.9725 | 0.7699 | 0.7048 | 0.4096 | 0.6976 |
 142 |  0.0960 | 0.9756 | 0.7699 | 0.7048 | 0.4096 | 0.6976 |
 143 |  0.0952 | 0.9761 | 0.7719 | 0.7060 | 0.4121 | 0.6987 |
 144 |  0.0939 | 0.9766 | 0.7699 | 0.7048 | 0.4096 | 0.6976 | best
  --> [ 18.1%] ep 145/800 | elapsed 13s | ETA 59s | best loss 0.0939 @ ep144 | wait 0/150
 145 |  0.1128 | 0.9542 | 0.7699 | 0.7048 | 0.4096 | 0.6976 |
 146 |  0.0935 | 0.9781 | 0.7658 | 0.7023 | 0.4047 | 0.6955 | best
  --> [ 18.4%] ep 147/800 | elapsed 13s | ETA 59s | best loss 0.0935 @ ep146 | wait 0/150
 147 |  0.1363 | 0.9033 | 0.7658 | 0.7023 | 0.4047 | 0.6955 |
 148 |  0.0967 | 0.9745 | 0.7678 | 0.7036 | 0.4071 | 0.6966 |
 149 |  0.0941 | 0.9786 | 0.7699 | 0.7048 | 0.4096 | 0.6976 |
  --> [ 18.8%] ep 150/800 | elapsed 14s | ETA 59s | best loss 0.0935 @ ep146 | wait 3/150
 150 |  0.0924 | 0.9791 | 0.7719 | 0.7060 | 0.4121 | 0.6987 | best
  --> [ 18.9%] ep 151/800 | elapsed 14s | ETA 59s | best loss 0.0924 @ ep150 | wait 0/150
 151 |  0.0923 | 0.9801 | 0.7719 | 0.7060 | 0.4121 | 0.6987 | best
  --> [ 19.0%] ep 152/800 | elapsed 14s | ETA 59s | best loss 0.0923 @ ep151 | wait 0/150
 152 |  0.0931 | 0.9791 | 0.7719 | 0.7060 | 0.4121 | 0.6987 |
 153 |  0.0944 | 0.9781 | 0.7719 | 0.7060 | 0.4121 | 0.6987 |
 154 |  0.0929 | 0.9796 | 0.7719 | 0.7060 | 0.4121 | 0.6987 |
 155 |  0.0919 | 0.9801 | 0.7719 | 0.7060 | 0.4121 | 0.6987 | best
  --> [ 19.5%] ep 156/800 | elapsed 14s | ETA 58s | best loss 0.0919 @ ep155 | wait 0/150
 156 |  0.0912 | 0.9807 | 0.7678 | 0.7036 | 0.4071 | 0.6966 | best
  --> [ 19.6%] ep 157/800 | elapsed 14s | ETA 58s | best loss 0.0912 @ ep156 | wait 0/150
 157 |  0.0914 | 0.9812 | 0.7678 | 0.7036 | 0.4071 | 0.6966 |
 158 |  0.0915 | 0.9807 | 0.7699 | 0.7048 | 0.4096 | 0.6976 |
 159 |  0.0948 | 0.9766 | 0.7699 | 0.7048 | 0.4096 | 0.6976 |
  --> [ 20.0%] ep 160/800 | elapsed 15s | ETA 58s | best loss 0.0912 @ ep156 | wait 3/150
 160 |  0.0926 | 0.9791 | 0.7719 | 0.7060 | 0.4121 | 0.6987 |
 161 |  0.0918 | 0.9812 | 0.7739 | 0.7073 | 0.4145 | 0.6998 |
 162 |  0.0907 | 0.9822 | 0.7739 | 0.7073 | 0.4145 | 0.6998 | best
  --> [ 20.4%] ep 163/800 | elapsed 15s | ETA 58s | best loss 0.0907 @ ep162 | wait 0/150
 163 |  0.0905 | 0.9857 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 20.5%] ep 164/800 | elapsed 15s | ETA 58s | best loss 0.0905 @ ep163 | wait 0/150
 164 |  0.0906 | 0.9873 | 0.7923 | 0.7184 | 0.4367 | 0.7093 |
 165 |  0.0908 | 0.9883 | 0.7923 | 0.7184 | 0.4367 | 0.7093 |
 166 |  0.1996 | 0.8340 | 0.7923 | 0.7184 | 0.4367 | 0.7093 |
 167 |  0.0909 | 0.9893 | 0.7862 | 0.7147 | 0.4293 | 0.7062 |
 168 |  0.0906 | 0.9893 | 0.7882 | 0.7159 | 0.4318 | 0.7072 |
 169 |  0.0903 | 0.9888 | 0.7841 | 0.7134 | 0.4269 | 0.7051 | best
  --> [ 21.2%] ep 170/800 | elapsed 16s | ETA 59s | best loss 0.0903 @ ep169 | wait 0/150
 170 |  0.0901 | 0.9893 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 21.4%] ep 171/800 | elapsed 16s | ETA 59s | best loss 0.0901 @ ep170 | wait 0/150
 171 |  0.1361 | 0.9201 | 0.7862 | 0.7147 | 0.4293 | 0.7062 |
 172 |  0.0897 | 0.9888 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 21.6%] ep 173/800 | elapsed 16s | ETA 58s | best loss 0.0897 @ ep172 | wait 0/150
 173 |  0.0896 | 0.9883 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 21.8%] ep 174/800 | elapsed 16s | ETA 58s | best loss 0.0896 @ ep173 | wait 0/150
 174 |  0.0895 | 0.9878 | 0.7841 | 0.7134 | 0.4269 | 0.7051 | best
  --> [ 21.9%] ep 175/800 | elapsed 16s | ETA 58s | best loss 0.0895 @ ep174 | wait 0/150
 175 |  0.0894 | 0.9878 | 0.7841 | 0.7134 | 0.4269 | 0.7051 | best
  --> [ 22.0%] ep 176/800 | elapsed 16s | ETA 58s | best loss 0.0894 @ ep175 | wait 0/150
 176 |  0.0893 | 0.9888 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 22.1%] ep 177/800 | elapsed 16s | ETA 58s | best loss 0.0893 @ ep176 | wait 0/150
 177 |  0.0891 | 0.9893 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 22.2%] ep 178/800 | elapsed 17s | ETA 58s | best loss 0.0891 @ ep177 | wait 0/150
 178 |  0.0890 | 0.9898 | 0.7862 | 0.7147 | 0.4293 | 0.7062 | best
  --> [ 22.4%] ep 179/800 | elapsed 17s | ETA 58s | best loss 0.0890 @ ep178 | wait 0/150
 179 |  0.0894 | 0.9903 | 0.7902 | 0.7171 | 0.4343 | 0.7083 |
  --> [ 22.5%] ep 180/800 | elapsed 17s | ETA 58s | best loss 0.0890 @ ep178 | wait 1/150
 180 |  0.0890 | 0.9908 | 0.7902 | 0.7171 | 0.4343 | 0.7083 | best
  --> [ 22.6%] ep 181/800 | elapsed 17s | ETA 57s | best loss 0.0890 @ ep180 | wait 0/150
 181 |  0.0888 | 0.9919 | 0.7943 | 0.7196 | 0.4392 | 0.7104 | best
  --> [ 22.8%] ep 182/800 | elapsed 17s | ETA 57s | best loss 0.0888 @ ep181 | wait 0/150
 182 |  0.0888 | 0.9919 | 0.7923 | 0.7184 | 0.4367 | 0.7093 | best
  --> [ 22.9%] ep 183/800 | elapsed 17s | ETA 57s | best loss 0.0888 @ ep182 | wait 0/150
 183 |  0.0887 | 0.9913 | 0.7963 | 0.7208 | 0.4417 | 0.7114 | best
  --> [ 23.0%] ep 184/800 | elapsed 17s | ETA 57s | best loss 0.0887 @ ep183 | wait 0/150

### 6.5–6.7 VerB — Paper-faithful

Chạy `main.py` với early stopping theo **eval KS**.

#### 6.5 VerB — Test year 2018

In [103]:
%cd /content/ACRF-RNN/Code
!python main.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2018 --max-epoch 800 --wait-epoch 150 --device 0 \
    2>&1 | tee /content/project_outputs/run_2018.log

/content/ACRF-RNN/Code

ACRF-RNN | test_year=2018 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208) | y=(10, 491, 1)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017]  (7 years)
Eval  : [2012, 2013, 2014, 2015, 2017, 2018]
Train labels: fraud=860, benign=2577
Model params: 972,937

  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
test_year=2018:  16%|█▌        | 128/800 ep [00:07<00:31]   0 |  0.4153 | 0.5580 | 0.4725 | 0.4469 | 0.1063 | 0.4437 | best
   1 |  0.4404 | 0.5204 | 0.5214 | 0.4926 | 0.0147 | 0.4890 |
   2 |  0.4085 | 0.4939 | 0.5356 | 0.5048 | 0.0096 | 0.5008 |
   3 |  0.3919 | 0.5458 | 0.5743 | 0.5335 | 0.0670 | 0.5267 |
   4 |  0.2982 | 0.6527 | 0.5927 | 0.5458 | 0.0917 | 0.5371 |
   5 |  0.2488 | 0.7251 | 0.6395 | 0.5902 | 0.1805 | 0.5814 | best
   6 |  0.2280 | 0.7648 | 0.6864 | 0.6449 | 0.2898 | 0.6392 | best
   7 |  0.4240 | 0.5081 | 0.6904 | 0.6605 | 0.3210 | 0.6576 | best
   8 |  0.1798 | 0.8513 | 0.3442 | 0.3603 | 0.2794 | 0.3588 |
   9 |  0.1651 | 0.8554 | 0.6660 | 0.6542 | 0.3085 | 0.6538 |
  10 |  0.1581 | 0.8564 | 0.6782 | 0.6574 | 0.3147 | 0.6559 |
  11 |  0.1521 | 0.8686 | 0.6802 | 0.6510 | 0.3021 | 0.6482 |
  12 |  0.1458 | 0.8778 | 0.7026 | 0.6662 | 0.3323 | 0.6619 | best
  13 |  0.1410 | 0.8900 | 0.7291 | 0.6840 | 0.3680 | 0.6776 | best
  14 |  0.1367 | 0.9063 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
  15 |  0.1313 | 0.9104 | 0.7352 | 0.6856 | 0.3711 | 0.6778 | best
  16 |  0.1273 | 0.9287 | 0.7393 | 0.6858 | 0.3715 | 0.6767 | best
  17 |  0.1221 | 0.9348 | 0.7413 | 0.6871 | 0.3743 | 0.6779 | best
  18 |  0.1168 | 0.9409 | 0.7413 | 0.6871 | 0.3743 | 0.6779 |
  19 |  0.1084 | 0.9511 | 0.7413 | 0.6871 | 0.3743 | 0.6779 |
  20 |  0.1020 | 0.9542 | 0.7454 | 0.6899 | 0.3797 | 0.6802 | best
  21 |  0.3562 | 0.6415 | 0.7495 | 0.6926 | 0.3852 | 0.6825 | best
  22 |  0.0980 | 0.9684 | 0.7536 | 0.6954 | 0.3907 | 0.6848 | best
  23 |  0.1016 | 0.9603 | 0.7597 | 0.6969 | 0.3939 | 0.6847 | best
  24 |  0.4615 | 0.5295 | 0.7576 | 0.6981 | 0.3962 | 0.6871 | best
  25 |  0.3598 | 0.6273 | 0.7719 | 0.7052 | 0.4103 | 0.6915 | best
  26 |  0.4181 | 0.5672 | 0.7760 | 0.7079 | 0.4158 | 0.6937 | best
  27 |  0.1793 | 0.8666 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  28 |  0.1804 | 0.8595 | 0.7800 | 0.7107 | 0.4213 | 0.6960 | best
  29 |  0.1804 | 0.8585 | 0.7821 | 0.7120 | 0.4241 | 0.6971 | best
  30 |  0.1800 | 0.8605 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  31 |  0.1794 | 0.8595 | 0.7841 | 0.7134 | 0.4268 | 0.6982 | best
  32 |  0.1792 | 0.8574 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  33 |  0.1788 | 0.8585 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  34 |  0.1788 | 0.8585 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  35 |  0.1786 | 0.8574 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  36 |  0.1785 | 0.8574 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
  37 |  0.1781 | 0.8595 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  38 |  0.1785 | 0.8595 | 0.2933 | 0.3362 | 0.3276 | 0.3242 |
  39 |  0.1782 | 0.8625 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  40 |  0.1784 | 0.8625 | 0.7719 | 0.7052 | 0.4103 | 0.6915 |
  41 |  0.1782 | 0.8605 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  42 |  0.1785 | 0.8585 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  43 |  0.1781 | 0.8595 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  44 |  0.1779 | 0.8625 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  45 |  0.1834 | 0.8554 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  46 |  0.1781 | 0.8595 | 0.7862 | 0.7148 | 0.4296 | 0.6993 | best
  47 |  0.1839 | 0.8523 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  48 |  0.1775 | 0.8635 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  49 |  0.1781 | 0.8605 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  50 |  0.1799 | 0.8574 | 0.7821 | 0.7120 | 0.4241 | 0.6971 |
  51 |  0.1782 | 0.8635 | 0.2933 | 0.3516 | 0.2968 | 0.3302 |
  52 |  0.1773 | 0.8625 | 0.7699 | 0.7038 | 0.4076 | 0.6904 |
  53 |  0.1769 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  54 |  0.1833 | 0.8523 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  55 |  0.1798 | 0.8595 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  56 |  0.1770 | 0.8625 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  57 |  0.1767 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  58 |  0.1902 | 0.8462 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  59 |  0.1763 | 0.8656 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  60 |  0.1758 | 0.8666 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  61 |  0.1753 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  62 |  0.1762 | 0.8697 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  63 |  0.1732 | 0.8758 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  64 |  0.1760 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  65 |  0.1754 | 0.8707 | 0.7862 | 0.7148 | 0.4296 | 0.6993 |
  66 |  0.1751 | 0.8727 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  67 |  0.1749 | 0.8676 | 0.7841 | 0.7134 | 0.4268 | 0.6982 |
  68 |  0.1742 | 0.8585 | 0.7699 | 0.7038 | 0.4076 | 0.6904 |
  69 |  0.3350 | 0.6670 | 0.7637 | 0.6971 | 0.3942 | 0.6833 |
  70 |  0.3149 | 0.6955 | 0.7515 | 0.6889 | 0.3777 | 0.6765 |
  71 |  0.4204 | 0.5367 | 0.7760 | 0.7130 | 0.4261 | 0.7010 |
  72 |  0.1769 | 0.8666 | 0.7739 | 0.7065 | 0.4131 | 0.6926 |
  73 |  0.1824 | 0.8534 | 0.7739 | 0.7065 | 0.4131 | 0.6926 |
  74 |  0.1730 | 0.8727 | 0.7800 | 0.7132 | 0.4265 | 0.6997 |
  75 |  0.1719 | 0.8717 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  76 |  0.1714 | 0.8697 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  77 |  0.1722 | 0.8717 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  78 |  0.1735 | 0.8686 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  79 |  0.2454 | 0.7811 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  80 |  0.2966 | 0.7138 | 0.7821 | 0.7146 | 0.4292 | 0.7008 |
  81 |  0.2083 | 0.8177 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  82 |  0.2160 | 0.8096 | 0.6334 | 0.6169 | 0.2338 | 0.6159 |
  83 |  0.2712 | 0.7434 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  84 |  0.3204 | 0.6823 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  85 |  0.3424 | 0.6589 | 0.7800 | 0.7132 | 0.4265 | 0.6997 |
  86 |  0.1935 | 0.8279 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  87 |  0.3677 | 0.6334 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  88 |  0.3827 | 0.6161 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  89 |  0.3852 | 0.6161 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
  90 |  0.1887 | 0.8483 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
  91 |  0.1809 | 0.8595 | 0.7780 | 0.7119 | 0.4237 | 0.6985 |
  92 |  0.1807 | 0.8605 | 0.2729 | 0.3276 | 0.3448 | 0.3074 |
  93 |  0.1687 | 0.8737 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  94 |  0.1771 | 0.8615 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  95 |  0.1750 | 0.8635 | 0.7760 | 0.7105 | 0.4210 | 0.6974 |
  96 |  0.1716 | 0.8646 | 0.7719 | 0.7077 | 0.4155 | 0.6951 |
  97 |  0.1689 | 0.8666 | 0.7658 | 0.7036 | 0.4072 | 0.6917 |
  98 |  0.1672 | 0.8646 | 0.7658 | 0.7010 | 0.4021 | 0.6881 |
  99 |  0.1657 | 0.8666 | 0.7637 | 0.7022 | 0.4045 | 0.6906 |
 100 |  0.1630 | 0.8717 | 0.7556 | 0.6942 | 0.3884 | 0.6824 |
 101 |  0.1616 | 0.8717 | 0.7515 | 0.6914 | 0.3829 | 0.6801 |
 102 |  0.1608 | 0.8768 | 0.7495 | 0.6926 | 0.3852 | 0.6825 |
 103 |  0.1577 | 0.8798 | 0.7475 | 0.6912 | 0.3825 | 0.6814 |
 104 |  0.1567 | 0.8788 | 0.7454 | 0.6950 | 0.3900 | 0.6871 |
 105 |  0.1541 | 0.8768 | 0.7434 | 0.6936 | 0.3873 | 0.6859 |
 106 |  0.1517 | 0.8839 | 0.7413 | 0.6923 | 0.3845 | 0.6847 |
 107 |  0.1484 | 0.8890 | 0.7373 | 0.6869 | 0.3739 | 0.6790 |
 108 |  0.1477 | 0.8880 | 0.7393 | 0.6909 | 0.3818 | 0.6836 |
 109 |  0.1449 | 0.8971 | 0.7454 | 0.7027 | 0.4054 | 0.6971 |
 110 |  0.1427 | 0.8992 | 0.7454 | 0.7027 | 0.4054 | 0.6971 |
 111 |  0.1389 | 0.9053 | 0.7413 | 0.6974 | 0.3948 | 0.6914 |
 112 |  0.1351 | 0.9084 | 0.7454 | 0.7053 | 0.4105 | 0.7003 |
 113 |  0.1333 | 0.9063 | 0.7495 | 0.7106 | 0.4211 | 0.7060 |
 114 |  0.1291 | 0.9124 | 0.7475 | 0.7092 | 0.4184 | 0.7047 |
 115 |  0.1358 | 0.9033 | 0.7475 | 0.7092 | 0.4184 | 0.7047 |
 116 |  0.1276 | 0.9134 | 0.7454 | 0.7053 | 0.4105 | 0.7003 |
 117 |  0.1260 | 0.9206 | 0.7393 | 0.7011 | 0.4023 | 0.6967 |
 118 |  0.1245 | 0.9196 | 0.7352 | 0.6984 | 0.3968 | 0.6942 |
 119 |  0.1212 | 0.9206 | 0.7312 | 0.6931 | 0.3862 | 0.6886 |
 120 |  0.1195 | 0.9246 | 0.7312 | 0.6931 | 0.3862 | 0.6886 |
 121 |  0.1170 | 0.9267 | 0.7291 | 0.6891 | 0.3783 | 0.6841 |
 122 |  0.1132 | 0.9348 | 0.7475 | 0.6861 | 0.3722 | 0.6743 |
 123 |  0.1094 | 0.9409 | 0.7312 | 0.6905 | 0.3810 | 0.6854 |
 124 |  0.1115 | 0.9379 | 0.7332 | 0.6893 | 0.3786 | 0.6833 |
 125 |  0.1060 | 0.9491 | 0.7291 | 0.6866 | 0.3732 | 0.6809 |
 126 |  0.1081 | 0.9460 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
 127 |  0.1081 | 0.9470 | 0.7271 | 0.6826 | 0.3653 | 0.6764 |
Early stop ep196 | best ep46:  25%|██▍       | 197/800 ep [00:11<00:33]

 129 |  0.1068 | 0.9521 | 0.7475 | 0.6938 | 0.3876 | 0.6849 |
 130 |  0.1052 | 0.9582 | 0.7495 | 0.6952 | 0.3904 | 0.6860 |
 131 |  0.1174 | 0.9379 | 0.7576 | 0.7007 | 0.4014 | 0.6907 |
 132 |  0.1019 | 0.9684 | 0.7454 | 0.6924 | 0.3849 | 0.6837 |
 133 |  0.1002 | 0.9715 | 0.7637 | 0.7022 | 0.4045 | 0.6906 |
 134 |  0.0995 | 0.9735 | 0.7556 | 0.6942 | 0.3884 | 0.6824 |
 135 |  0.0988 | 0.9745 | 0.7576 | 0.6981 | 0.3962 | 0.6871 |
 136 |  0.1001 | 0.9745 | 0.2566 | 0.3115 | 0.3770 | 0.2900 |
 137 |  0.3926 | 0.6029 | 0.7699 | 0.7064 | 0.4127 | 0.6940 |
 138 |  0.1029 | 0.9857 | 0.7760 | 0.7079 | 0.4158 | 0.6937 |
 139 |  0.1115 | 0.9745 | 0.7780 | 0.7093 | 0.4186 | 0.6949 |
 140 |  0.1133 | 0.9817 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
 141 |  0.2673 | 0.6670 | 0.7800 | 0.7107 | 0.4213 | 0.6960 |
 142 |  0.3024 | 0.7057 | 0.7047 | 0.6752 | 0.3504 | 0.6725 |
 143 |  0.1335 | 0.9532 | 0.7556 | 0.6891 | 0.3781 | 0.6751 |
 144 |  0.1671 | 0.8870 | 0.7332 | 0.6816 | 0.3633 | 0.6732 |
 145 |  0.2240 | 0.7780 | 0.6395 | 0.6287 | 0.2574 | 0.6283 |
 146 |  0.2808 | 0.6436 | 0.4990 | 0.5057 | 0.0114 | 0.5055 |
 147 |  0.4426 | 0.3910 | 0.7088 | 0.6651 | 0.3303 | 0.6590 |
 148 |  0.4054 | 0.4430 | 0.4501 | 0.4369 | 0.1263 | 0.4360 |
 149 |  0.3934 | 0.4766 | 0.4644 | 0.4439 | 0.1122 | 0.4419 |
 150 |  0.3628 | 0.5377 | 0.4766 | 0.4599 | 0.0803 | 0.4585 |
 151 |  0.3525 | 0.5560 | 0.7393 | 0.6858 | 0.3715 | 0.6767 |
 152 |  0.1806 | 0.8585 | 0.7800 | 0.7081 | 0.4162 | 0.6922 |
 153 |  0.4816 | 0.4674 | 0.5234 | 0.5094 | 0.0188 | 0.5086 |
 154 |  0.7534 | 0.1609 | 0.2831 | 0.3319 | 0.3362 | 0.3161 |
 155 |  0.4613 | 0.3666 | 0.4297 | 0.4231 | 0.1537 | 0.4229 |
 156 |  0.3840 | 0.4980 | 0.4684 | 0.4569 | 0.0862 | 0.4563 |
 157 |  0.3233 | 0.5550 | 0.4868 | 0.4693 | 0.0614 | 0.4679 |
 158 |  0.2861 | 0.6100 | 0.5255 | 0.4954 | 0.0092 | 0.4914 |
 159 |  0.2654 | 0.6609 | 0.5540 | 0.5069 | 0.0138 | 0.4975 |
 160 |  0.2503 | 0.7077 | 0.5784 | 0.5337 | 0.0673 | 0.5255 |
 161 |  0.2386 | 0.7485 | 0.6069 | 0.5555 | 0.1109 | 0.5451 |
 162 |  0.2274 | 0.7841 | 0.6273 | 0.5743 | 0.1486 | 0.5637 |
 163 |  0.2176 | 0.8147 | 0.6477 | 0.5932 | 0.1864 | 0.5823 |
 164 |  0.2089 | 0.8371 | 0.6538 | 0.5973 | 0.1946 | 0.5857 |
 165 |  0.2022 | 0.8503 | 0.6680 | 0.6044 | 0.2087 | 0.5898 |
 166 |  0.1954 | 0.8554 | 0.6802 | 0.6152 | 0.2303 | 0.6002 |
 167 |  0.1883 | 0.8717 | 0.6904 | 0.6246 | 0.2492 | 0.6095 |
 168 |  0.1817 | 0.8809 | 0.6986 | 0.6352 | 0.2704 | 0.6215 |
 169 |  0.1779 | 0.8890 | 0.6965 | 0.6313 | 0.2625 | 0.6166 |
 170 |  0.1747 | 0.8900 | 0.6986 | 0.6301 | 0.2602 | 0.6139 |
 171 |  0.1704 | 0.8961 | 0.7067 | 0.6381 | 0.2763 | 0.6221 |
 172 |  0.1657 | 0.9094 | 0.7149 | 0.6462 | 0.2924 | 0.6303 |
 173 |  0.1620 | 0.9155 | 0.7108 | 0.6383 | 0.2767 | 0.6204 |
 174 |  0.1587 | 0.9196 | 0.7149 | 0.6385 | 0.2770 | 0.6186 |
 175 |  0.1555 | 0.9226 | 0.7189 | 0.6438 | 0.2876 | 0.6247 |
 176 |  0.1522 | 0.9267 | 0.7189 | 0.6413 | 0.2825 | 0.6207 |
 177 |  0.1492 | 0.9297 | 0.7210 | 0.6426 | 0.2853 | 0.6218 |
 178 |  0.1467 | 0.9348 | 0.7271 | 0.6519 | 0.3038 | 0.6330 |
 179 |  0.1440 | 0.9409 | 0.7312 | 0.6546 | 0.3092 | 0.6351 |
 180 |  0.1416 | 0.9440 | 0.7352 | 0.6574 | 0.3147 | 0.6373 |
 181 |  0.1394 | 0.9460 | 0.7352 | 0.6574 | 0.3147 | 0.6373 |
 182 |  0.1372 | 0.9481 | 0.7373 | 0.6587 | 0.3175 | 0.6383 |
 183 |  0.1352 | 0.9521 | 0.7454 | 0.6668 | 0.3336 | 0.6466 |
 184 |  0.1334 | 0.9552 | 0.7454 | 0.6642 | 0.3285 | 0.6426 |
 185 |  0.1315 | 0.9562 | 0.7454 | 0.6642 | 0.3285 | 0.6426 |
 186 |  0.1298 | 0.9582 | 0.7434 | 0.6603 | 0.3206 | 0.6375 |
 187 |  0.1286 | 0.9603 | 0.7475 | 0.6656 | 0.3312 | 0.6437 |
 188 |  0.1273 | 0.9613 | 0.7495 | 0.6644 | 0.3288 | 0.6406 |
 189 |  0.1257 | 0.9623 | 0.7495 | 0.6644 | 0.3288 | 0.6406 |
 190 |  0.1242 | 0.9654 | 0.7495 | 0.6670 | 0.3340 | 0.6447 |
 191 |  0.1228 | 0.9654 | 0.7515 | 0.6684 | 0.3367 | 0.6458 |
 192 |  0.1213 | 0.9674 | 0.7576 | 0.6776 | 0.3552 | 0.6570 |
 193 |  0.1198 | 0.9684 | 0.7556 | 0.6788 | 0.3576 | 0.6599 |
 194 |  0.1184 | 0.9684 | 0.7576 | 0.6827 | 0.3655 | 0.6649 |
 195 |  0.1169 | 0.9684 | 0.7556 | 0.6788 | 0.3576 | 0.6599 |
 196 |  0.1158 | 0.9684 | 0.7536 | 0.6774 | 0.3548 | 0.6588 |

Early stop @ epoch 196  (best_epoch=46)

============================================================
KET QUA -- test_year=2018
============================================================
Best epoch : 46
Metric         Paper    VerB    Diff
----------------------------------------
Accuracy       77.60   78.62 +  1.02
Recall_m       70.79   71.48 +  0.69
KS             41.58   42.96 +  1.38
G-mean         69.37   69.93 +  0.56

#### 6.6 VerB — Test year 2019

In [104]:
%cd /content/ACRF-RNN/Code
!python main.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2019 --max-epoch 800 --wait-epoch 150 --device 0 \
    2>&1 | tee /content/project_outputs/run_2019.log

/content/ACRF-RNN/Code

ACRF-RNN | test_year=2019 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208) | y=(10, 491, 1)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018]  (8 years)
Eval  : [2013, 2014, 2015, 2017, 2018, 2019]
Train labels: fraud=987, benign=2941
Model params: 972,937

  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
test_year=2019:  16%|█▌        | 129/800 ep [00:09<00:43]   0 |  0.4150 | 0.5553 | 0.5621 | 0.5400 | 0.0801 | 0.5385 | best
   1 |  0.3941 | 0.4956 | 0.5153 | 0.5034 | 0.0068 | 0.5029 |
   2 |  0.3786 | 0.5485 | 0.6191 | 0.5929 | 0.1859 | 0.5910 | best
   3 |  0.3260 | 0.6144 | 0.5682 | 0.5860 | 0.1720 | 0.5851 |
   4 |  0.2711 | 0.6979 | 0.7128 | 0.6792 | 0.3583 | 0.6764 | best
   5 |  0.2395 | 0.7502 | 0.7413 | 0.6975 | 0.3951 | 0.6930 | best
   6 |  0.2115 | 0.8018 | 0.7597 | 0.6964 | 0.3928 | 0.6869 |
   7 |  0.1921 | 0.8371 | 0.7475 | 0.6821 | 0.3642 | 0.6717 |
   8 |  0.1820 | 0.8500 | 0.7454 | 0.6808 | 0.3615 | 0.6706 |
   9 |  0.3537 | 0.6402 | 0.7454 | 0.6872 | 0.3745 | 0.6791 |
  10 |  0.1972 | 0.8215 | 0.7230 | 0.6599 | 0.3197 | 0.6499 |
  11 |  0.1700 | 0.8527 | 0.6538 | 0.5635 | 0.1270 | 0.5393 |
  12 |  0.1681 | 0.8574 | 0.7189 | 0.6508 | 0.3016 | 0.6389 |
  13 |  0.1648 | 0.8642 | 0.7454 | 0.6808 | 0.3615 | 0.6706 |
  14 |  0.1548 | 0.8866 | 0.7536 | 0.6893 | 0.3785 | 0.6793 |
  15 |  0.1513 | 0.8968 | 0.7658 | 0.7068 | 0.4136 | 0.6987 | best
  16 |  0.1462 | 0.9104 | 0.7780 | 0.7212 | 0.4423 | 0.7138 | best
  17 |  0.1406 | 0.9280 | 0.7800 | 0.7257 | 0.4514 | 0.7190 | best
  18 |  0.1351 | 0.9314 | 0.7780 | 0.7373 | 0.4747 | 0.7336 | best
  19 |  0.1389 | 0.9185 | 0.7719 | 0.7205 | 0.4409 | 0.7144 |
  20 |  0.3471 | 0.6395 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  21 |  0.1930 | 0.8371 | 0.7760 | 0.7393 | 0.4785 | 0.7363 | best
  22 |  0.1694 | 0.8697 | 0.7719 | 0.7399 | 0.4797 | 0.7376 | best
  23 |  0.1334 | 0.9179 | 0.7719 | 0.7399 | 0.4797 | 0.7376 |
  24 |  0.2991 | 0.7108 | 0.7678 | 0.7308 | 0.4615 | 0.7277 |
  25 |  0.1500 | 0.8798 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
  26 |  0.1599 | 0.8649 | 0.7678 | 0.7340 | 0.4680 | 0.7314 |
  27 |  0.1744 | 0.8418 | 0.7210 | 0.6489 | 0.2977 | 0.6356 |
  28 |  0.1835 | 0.8242 | 0.7067 | 0.6203 | 0.2405 | 0.6002 |
  29 |  0.1968 | 0.8038 | 0.7026 | 0.6176 | 0.2353 | 0.5981 |
  30 |  0.1983 | 0.8038 | 0.7067 | 0.6235 | 0.2470 | 0.6050 |
  31 |  0.1968 | 0.8072 | 0.7108 | 0.6294 | 0.2587 | 0.6118 |
  32 |  0.1851 | 0.8282 | 0.7128 | 0.6307 | 0.2613 | 0.6129 |
  33 |  0.1806 | 0.8405 | 0.7210 | 0.6392 | 0.2783 | 0.6217 |
  34 |  0.1721 | 0.8527 | 0.7434 | 0.6730 | 0.3460 | 0.6608 |
  35 |  0.1715 | 0.8500 | 0.3890 | 0.4770 | 0.0461 | 0.4496 |
  36 |  0.1745 | 0.8391 | 0.4033 | 0.4926 | 0.0147 | 0.4653 |
  37 |  0.2383 | 0.7502 | 0.7515 | 0.6847 | 0.3694 | 0.6739 |
  38 |  0.1804 | 0.8316 | 0.7230 | 0.6599 | 0.3197 | 0.6499 |
  39 |  0.1755 | 0.8350 | 0.7515 | 0.6912 | 0.3823 | 0.6825 |
  40 |  0.1711 | 0.8445 | 0.7637 | 0.7055 | 0.4110 | 0.6976 |
  41 |  0.1669 | 0.8561 | 0.7597 | 0.6997 | 0.3993 | 0.6912 |
  42 |  0.1648 | 0.8669 | 0.7576 | 0.6822 | 0.3644 | 0.6683 |
  43 |  0.1627 | 0.8703 | 0.7556 | 0.6776 | 0.3553 | 0.6627 |
  44 |  0.1646 | 0.8547 | 0.7556 | 0.6776 | 0.3553 | 0.6627 |
  45 |  0.1616 | 0.8663 | 0.7637 | 0.6893 | 0.3787 | 0.6760 |
  46 |  0.1579 | 0.8778 | 0.7739 | 0.7121 | 0.4241 | 0.7032 |
  47 |  0.1540 | 0.8880 | 0.7800 | 0.7257 | 0.4514 | 0.7190 |
  48 |  0.1507 | 0.8934 | 0.7800 | 0.7289 | 0.4579 | 0.7230 |
  49 |  0.1480 | 0.8975 | 0.7800 | 0.7289 | 0.4579 | 0.7230 |
  50 |  0.1445 | 0.9029 | 0.7739 | 0.7218 | 0.4435 | 0.7156 |
  51 |  0.1414 | 0.9022 | 0.7699 | 0.7191 | 0.4383 | 0.7133 |
  52 |  0.1494 | 0.8846 | 0.7699 | 0.7159 | 0.4318 | 0.7092 |
  53 |  0.1417 | 0.8955 | 0.7699 | 0.7159 | 0.4318 | 0.7092 |
  54 |  0.1452 | 0.8893 | 0.7719 | 0.7140 | 0.4280 | 0.7062 |
  55 |  0.1438 | 0.8934 | 0.7658 | 0.7004 | 0.4007 | 0.6903 |
  56 |  0.1425 | 0.8914 | 0.7658 | 0.7036 | 0.4072 | 0.6945 |
  57 |  0.1418 | 0.8961 | 0.7678 | 0.7146 | 0.4292 | 0.7081 |
  58 |  0.1358 | 0.9151 | 0.7699 | 0.7159 | 0.4318 | 0.7092 |
  59 |  0.1332 | 0.9131 | 0.7719 | 0.7172 | 0.4345 | 0.7104 |
  60 |  0.1355 | 0.9050 | 0.7739 | 0.7218 | 0.4435 | 0.7156 |
  61 |  0.1403 | 0.8961 | 0.7821 | 0.7367 | 0.4734 | 0.7321 |
  62 |  0.1276 | 0.9151 | 0.7841 | 0.7380 | 0.4761 | 0.7333 |
  63 |  0.1472 | 0.8839 | 0.7862 | 0.7393 | 0.4787 | 0.7345 |
  64 |  0.1392 | 0.9022 | 0.7800 | 0.7354 | 0.4708 | 0.7309 |
  65 |  0.1302 | 0.9131 | 0.7760 | 0.7263 | 0.4526 | 0.7207 |
  66 |  0.1284 | 0.9185 | 0.7760 | 0.7328 | 0.4656 | 0.7286 |
  67 |  0.1260 | 0.9246 | 0.7699 | 0.7288 | 0.4577 | 0.7251 |
  68 |  0.1236 | 0.9348 | 0.7719 | 0.7302 | 0.4603 | 0.7262 |
  69 |  0.1208 | 0.9375 | 0.7760 | 0.7328 | 0.4656 | 0.7286 |
  70 |  0.1194 | 0.9341 | 0.7800 | 0.7354 | 0.4708 | 0.7309 |
  71 |  0.1189 | 0.9328 | 0.7800 | 0.7354 | 0.4708 | 0.7309 |
  72 |  0.1194 | 0.9321 | 0.7780 | 0.7341 | 0.4682 | 0.7298 |
  73 |  0.1187 | 0.9341 | 0.7760 | 0.7296 | 0.4591 | 0.7247 |
  74 |  0.1168 | 0.9382 | 0.7800 | 0.7354 | 0.4708 | 0.7309 |
  75 |  0.1148 | 0.9423 | 0.7780 | 0.7341 | 0.4682 | 0.7298 |
  76 |  0.1136 | 0.9437 | 0.7760 | 0.7328 | 0.4656 | 0.7286 |
  77 |  0.1126 | 0.9464 | 0.7821 | 0.7400 | 0.4799 | 0.7360 | best
  78 |  0.1117 | 0.9457 | 0.7780 | 0.7341 | 0.4682 | 0.7298 |
  79 |  0.1111 | 0.9464 | 0.7821 | 0.7400 | 0.4799 | 0.7360 |
  80 |  0.1106 | 0.9491 | 0.7821 | 0.7400 | 0.4799 | 0.7360 |
  81 |  0.1098 | 0.9504 | 0.7800 | 0.7386 | 0.4773 | 0.7348 |
  82 |  0.1087 | 0.9525 | 0.7800 | 0.7386 | 0.4773 | 0.7348 |
  83 |  0.1081 | 0.9532 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  84 |  0.1080 | 0.9532 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  85 |  0.1077 | 0.9532 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  86 |  0.1069 | 0.9532 | 0.7780 | 0.7373 | 0.4747 | 0.7336 |
  87 |  0.1059 | 0.9538 | 0.7760 | 0.7360 | 0.4720 | 0.7324 |
  88 |  0.1045 | 0.9538 | 0.7719 | 0.7334 | 0.4668 | 0.7301 |
  89 |  0.1056 | 0.9525 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  90 |  0.1049 | 0.9545 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  91 |  0.1041 | 0.9552 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  92 |  0.1037 | 0.9566 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
  93 |  0.1038 | 0.9538 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
  94 |  0.1037 | 0.9538 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  95 |  0.1034 | 0.9559 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  96 |  0.1032 | 0.9572 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  97 |  0.1027 | 0.9579 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  98 |  0.1030 | 0.9566 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
  99 |  0.1023 | 0.9579 | 0.7719 | 0.7334 | 0.4668 | 0.7301 |
 100 |  0.1020 | 0.9579 | 0.7719 | 0.7334 | 0.4668 | 0.7301 |
 101 |  0.1017 | 0.9579 | 0.7699 | 0.7321 | 0.4642 | 0.7289 |
 102 |  0.1014 | 0.9579 | 0.7719 | 0.7334 | 0.4668 | 0.7301 |
 103 |  0.1012 | 0.9599 | 0.7739 | 0.7412 | 0.4823 | 0.7388 | best
 104 |  0.2471 | 0.7475 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
 105 |  0.1011 | 0.9599 | 0.7719 | 0.7366 | 0.4733 | 0.7338 |
 106 |  0.1007 | 0.9599 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 107 |  0.1002 | 0.9606 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 108 |  0.1002 | 0.9613 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 109 |  0.0999 | 0.9627 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 110 |  0.0999 | 0.9627 | 0.7739 | 0.7412 | 0.4823 | 0.7388 |
 111 |  0.1023 | 0.9599 | 0.7739 | 0.7412 | 0.4823 | 0.7388 |
 112 |  0.1004 | 0.9627 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 113 |  0.1008 | 0.9633 | 0.7760 | 0.7425 | 0.4850 | 0.7400 | best
 114 |  0.1013 | 0.9633 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 115 |  0.1016 | 0.9640 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 116 |  0.1019 | 0.9654 | 0.7739 | 0.7379 | 0.4759 | 0.7351 |
 117 |  0.1103 | 0.9620 | 0.7760 | 0.7393 | 0.4785 | 0.7363 |
 118 |  0.1125 | 0.9627 | 0.7800 | 0.7419 | 0.4838 | 0.7386 |
 119 |  0.1496 | 0.8988 | 0.7800 | 0.7419 | 0.4838 | 0.7386 |
 120 |  0.1601 | 0.8812 | 0.7536 | 0.6569 | 0.3138 | 0.6332 |
 121 |  0.1221 | 0.9226 | 0.7678 | 0.7308 | 0.4615 | 0.7277 |
 122 |  0.2842 | 0.7312 | 0.7800 | 0.7451 | 0.4902 | 0.7424 | best
 123 |  0.3665 | 0.6592 | 0.7780 | 0.7438 | 0.4876 | 0.7412 |
 124 |  0.3649 | 0.6463 | 0.7780 | 0.7438 | 0.4876 | 0.7412 |
 125 |  0.3848 | 0.5961 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 126 |  0.3638 | 0.6137 | 0.7760 | 0.7425 | 0.4850 | 0.7400 |
 127 |  0.3420 | 0.6361 | 0.7739 | 0.7412 | 0.4823 | 0.7388 |
 128 |  0.3591 | 0.6395 | 0.7719 | 0.7399 | 0.4797 | 0.7376 |
test_year=2019:  32%|███▏      | 259/800 ep [00:19<00:34]
 130 |  0.2750 | 0.7060 | 0.7699 | 0.7385 | 0.4771 | 0.7364 |
 131 |  0.2650 | 0.7088 | 0.7699 | 0.7418 | 0.4836 | 0.7400 |
 132 |  0.2356 | 0.7413 | 0.7678 | 0.7405 | 0.4809 | 0.7388 |
 133 |  0.2593 | 0.7189 | 0.7699 | 0.7418 | 0.4836 | 0.7400 |
 134 |  0.2679 | 0.7346 | 0.6802 | 0.5935 | 0.1870 | 0.5723 |
 135 |  0.3051 | 0.6959 | 0.5316 | 0.4266 | 0.1468 | 0.3818 |
 136 |  0.2849 | 0.7183 | 0.7393 | 0.6704 | 0.3407 | 0.6586 |
 137 |  0.2846 | 0.6993 | 0.7658 | 0.7359 | 0.4718 | 0.7339 |
 138 |  0.2244 | 0.7733 | 0.7576 | 0.7307 | 0.4613 | 0.7290 |
 139 |  0.2307 | 0.7828 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 140 |  0.2353 | 0.7834 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 141 |  0.2310 | 0.7868 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 142 |  0.2134 | 0.8018 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 143 |  0.2121 | 0.8024 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 144 |  0.2119 | 0.8024 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 145 |  0.2114 | 0.8038 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 146 |  0.2112 | 0.8038 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 147 |  0.2108 | 0.8045 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 148 |  0.2104 | 0.8052 | 0.7719 | 0.7463 | 0.4927 | 0.7449 | best
 149 |  0.2104 | 0.8045 | 0.7699 | 0.7450 | 0.4900 | 0.7437 |
 150 |  0.2102 | 0.8038 | 0.7678 | 0.7437 | 0.4874 | 0.7424 |
 151 |  0.2102 | 0.8024 | 0.7678 | 0.7437 | 0.4874 | 0.7424 |
 152 |  0.2098 | 0.8031 | 0.7678 | 0.7437 | 0.4874 | 0.7424 |
 153 |  0.2090 | 0.8038 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 154 |  0.2080 | 0.8072 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 155 |  0.2075 | 0.8065 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 156 |  0.2077 | 0.8058 | 0.7617 | 0.7398 | 0.4795 | 0.7387 |
 157 |  0.2077 | 0.8052 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 158 |  0.2079 | 0.8052 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 159 |  0.2077 | 0.8045 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 160 |  0.2075 | 0.8052 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 161 |  0.2072 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 162 |  0.2072 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 163 |  0.2071 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 164 |  0.2071 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 165 |  0.2069 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 166 |  0.2068 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 167 |  0.2068 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 168 |  0.2067 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 169 |  0.2067 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 170 |  0.2067 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 171 |  0.2066 | 0.8079 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 172 |  0.2065 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 173 |  0.2064 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 174 |  0.2064 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 175 |  0.2062 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 176 |  0.2060 | 0.8072 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 177 |  0.2059 | 0.8086 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 178 |  0.2063 | 0.8065 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 179 |  0.2057 | 0.8086 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 180 |  0.2055 | 0.8072 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 181 |  0.2054 | 0.8086 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 182 |  0.2051 | 0.8092 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 183 |  0.2049 | 0.8092 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 184 |  0.2047 | 0.8099 | 0.7637 | 0.7411 | 0.4822 | 0.7399 |
 185 |  0.2046 | 0.8099 | 0.7658 | 0.7424 | 0.4848 | 0.7412 |
 186 |  0.2047 | 0.8086 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 187 |  0.2046 | 0.8086 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 188 |  0.2045 | 0.8086 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 189 |  0.2046 | 0.8092 | 0.7617 | 0.7365 | 0.4731 | 0.7351 |
 190 |  0.2041 | 0.8092 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 191 |  0.2040 | 0.8099 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 192 |  0.2039 | 0.8099 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 193 |  0.2036 | 0.8119 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 194 |  0.2034 | 0.8106 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 195 |  0.2032 | 0.8119 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 196 |  0.2028 | 0.8119 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 197 |  0.2027 | 0.8119 | 0.7678 | 0.7405 | 0.4809 | 0.7388 |
 198 |  0.2024 | 0.8126 | 0.7637 | 0.7378 | 0.4757 | 0.7363 |
 199 |  0.2017 | 0.8133 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 200 |  0.2017 | 0.8133 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 201 |  0.2015 | 0.8153 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 202 |  0.2025 | 0.8126 | 0.7719 | 0.7431 | 0.4862 | 0.7413 |
 203 |  0.2012 | 0.8153 | 0.7658 | 0.7392 | 0.4783 | 0.7376 |
 204 |  0.2022 | 0.8126 | 0.7617 | 0.7365 | 0.4731 | 0.7351 |
 205 |  0.2072 | 0.8106 | 0.7556 | 0.7294 | 0.4587 | 0.7278 |
 206 |  0.2048 | 0.8086 | 0.7556 | 0.7261 | 0.4523 | 0.7242 |
 207 |  0.2040 | 0.8106 | 0.7576 | 0.7307 | 0.4613 | 0.7290 |
 208 |  0.2037 | 0.8079 | 0.7678 | 0.7405 | 0.4809 | 0.7388 |
 209 |  0.2023 | 0.8092 | 0.7699 | 0.7418 | 0.4836 | 0.7400 |
 210 |  0.2053 | 0.8167 | 0.5499 | 0.5580 | 0.1160 | 0.5578 |
 211 |  0.3161 | 0.6504 | 0.3442 | 0.4061 | 0.1879 | 0.3903 |
 212 |  0.4103 | 0.4929 | 0.3788 | 0.4575 | 0.0850 | 0.4347 |
 213 |  0.3683 | 0.5587 | 0.4379 | 0.5246 | 0.0493 | 0.5005 |
 214 |  0.3568 | 0.5655 | 0.7352 | 0.7195 | 0.4389 | 0.7189 |
 215 |  0.3962 | 0.5818 | 0.6273 | 0.6144 | 0.2287 | 0.6139 |
 216 |  0.3351 | 0.6300 | 0.7617 | 0.7268 | 0.4537 | 0.7241 |
 217 |  0.4199 | 0.5404 | 0.5336 | 0.5184 | 0.0368 | 0.5177 |
 218 |  0.2746 | 0.7135 | 0.6314 | 0.5976 | 0.1952 | 0.5944 |
 219 |  0.3910 | 0.6062 | 0.5886 | 0.5571 | 0.1142 | 0.5542 |
 220 |  0.3392 | 0.6314 | 0.6538 | 0.6314 | 0.2628 | 0.6301 |
 221 |  0.3453 | 0.6409 | 0.5540 | 0.5315 | 0.0631 | 0.5300 |
 222 |  0.3617 | 0.5648 | 0.5947 | 0.5578 | 0.1156 | 0.5538 |
 223 |  0.3842 | 0.5526 | 0.4114 | 0.4882 | 0.0236 | 0.4679 |
 224 |  0.5053 | 0.4148 | 0.4073 | 0.4920 | 0.0160 | 0.4675 |
 225 |  0.4693 | 0.3428 | 0.3788 | 0.4316 | 0.1368 | 0.4209 |
 226 |  0.4827 | 0.3714 | 0.3890 | 0.4479 | 0.1042 | 0.4350 |
 227 |  0.4812 | 0.4392 | 0.3157 | 0.3618 | 0.2763 | 0.3520 |
 228 |  0.5406 | 0.2424 | 0.3136 | 0.3799 | 0.2402 | 0.3604 |
 229 |  0.5298 | 0.2770 | 0.3279 | 0.3891 | 0.2218 | 0.3730 |
 230 |  0.4933 | 0.3354 | 0.2892 | 0.3254 | 0.3492 | 0.3187 |
 231 |  0.5016 | 0.3551 | 0.2770 | 0.3304 | 0.3391 | 0.3159 |
 232 |  0.5338 | 0.2403 | 0.2851 | 0.3421 | 0.3157 | 0.3262 |
 233 |  0.5088 | 0.3082 | 0.3014 | 0.3526 | 0.2947 | 0.3402 |
 234 |  0.5356 | 0.2505 | 0.3238 | 0.3703 | 0.2594 | 0.3606 |
 235 |  0.4789 | 0.2858 | 0.3340 | 0.3801 | 0.2398 | 0.3708 |
 236 |  0.4696 | 0.2933 | 0.3218 | 0.3722 | 0.2555 | 0.3608 |
 237 |  0.4927 | 0.2960 | 0.3442 | 0.3964 | 0.2073 | 0.3849 |
 238 |  0.4515 | 0.3007 | 0.3564 | 0.4042 | 0.1915 | 0.3948 |
 239 |  0.4469 | 0.3041 | 0.3564 | 0.4075 | 0.1850 | 0.3968 |
 240 |  0.4635 | 0.3734 | 0.3890 | 0.4543 | 0.0913 | 0.4386 |
 241 |  0.4490 | 0.3544 | 0.3788 | 0.4251 | 0.1497 | 0.4168 |
 242 |  0.4198 | 0.3530 | 0.3890 | 0.4349 | 0.1301 | 0.4269 |
 243 |  0.4250 | 0.3374 | 0.3849 | 0.4291 | 0.1418 | 0.4216 |
 244 |  0.3890 | 0.4168 | 0.7556 | 0.7197 | 0.4393 | 0.7167 |
 245 |  0.4265 | 0.3299 | 0.3666 | 0.4108 | 0.1784 | 0.4029 |
 246 |  0.4778 | 0.4107 | 0.3910 | 0.4363 | 0.1275 | 0.4285 |
 247 |  0.4134 | 0.3530 | 0.7434 | 0.7118 | 0.4236 | 0.7095 |
 248 |  0.4041 | 0.3754 | 0.3055 | 0.3294 | 0.3412 | 0.3265 |
 249 |  0.3077 | 0.5811 | 0.7536 | 0.7280 | 0.4561 | 0.7266 |
 250 |  0.4021 | 0.4318 | 0.4073 | 0.4241 | 0.1518 | 0.4230 |
 251 |  0.3981 | 0.4229 | 0.4358 | 0.4587 | 0.0827 | 0.4568 |
 252 |  0.3966 | 0.4487 | 0.4908 | 0.5361 | 0.0723 | 0.5298 |
 253 |  0.3824 | 0.4671 | 0.4501 | 0.4678 | 0.0643 | 0.4667 |
 254 |  0.3781 | 0.5017 | 0.4868 | 0.5141 | 0.0282 | 0.5117 |
 255 |  0.3750 | 0.4596 | 0.4481 | 0.4795 | 0.0411 | 0.4761 |
 256 |  0.3253 | 0.5825 | 0.5825 | 0.5661 | 0.1322 | 0.5653 |
 257 |  0.3222 | 0.6185 | 0.5234 | 0.5345 | 0.0690 | 0.5341 |
 258 |  0.3375 | 0.5574 | 0.6151 | 0.5547 | 0.1095 | 0.5439 |
Early stop ep298 | best ep148:  37%|███▋      | 299/800 ep [00:21<00:36]

 260 |  0.3588 | 0.5601 | 0.6436 | 0.5505 | 0.1010 | 0.5240 |
 261 |  0.3456 | 0.5655 | 0.6293 | 0.5478 | 0.0955 | 0.5275 |
 262 |  0.2981 | 0.6707 | 0.6293 | 0.5413 | 0.0826 | 0.5173 |
 263 |  0.2787 | 0.7081 | 0.6069 | 0.5172 | 0.0343 | 0.4909 |
 264 |  0.3487 | 0.5689 | 0.7149 | 0.6514 | 0.3028 | 0.6411 |
 265 |  0.3174 | 0.6578 | 0.6110 | 0.5198 | 0.0396 | 0.4928 |
 266 |  0.3272 | 0.6354 | 0.7230 | 0.6631 | 0.3262 | 0.6542 |
 267 |  0.3172 | 0.6144 | 0.6151 | 0.5063 | 0.0125 | 0.4663 |
 268 |  0.3351 | 0.6069 | 0.5601 | 0.4902 | 0.0196 | 0.4736 |
 269 |  0.3454 | 0.6130 | 0.5967 | 0.5009 | 0.0018 | 0.4698 |
 270 |  0.3314 | 0.6422 | 0.6049 | 0.5094 | 0.0188 | 0.4791 |
 271 |  0.3824 | 0.5458 | 0.4114 | 0.3589 | 0.2823 | 0.3460 |
 272 |  0.3107 | 0.6626 | 0.6090 | 0.5282 | 0.0564 | 0.5075 |
 273 |  0.3035 | 0.6728 | 0.6110 | 0.5295 | 0.0590 | 0.5085 |
 274 |  0.2919 | 0.6925 | 0.6151 | 0.5224 | 0.0448 | 0.4947 |
 275 |  0.2973 | 0.6707 | 0.6110 | 0.5360 | 0.0719 | 0.5184 |
 276 |  0.2997 | 0.6694 | 0.6069 | 0.5301 | 0.0602 | 0.5115 |
 277 |  0.3036 | 0.6701 | 0.6008 | 0.5359 | 0.0717 | 0.5228 |
 278 |  0.3521 | 0.6151 | 0.5743 | 0.5285 | 0.0570 | 0.5219 |
 279 |  0.3013 | 0.6721 | 0.5967 | 0.5235 | 0.0471 | 0.5065 |
 280 |  0.3254 | 0.6320 | 0.6212 | 0.5393 | 0.0786 | 0.5185 |
 281 |  0.2936 | 0.6714 | 0.6273 | 0.5432 | 0.0864 | 0.5214 |
 282 |  0.3005 | 0.6843 | 0.4521 | 0.3689 | 0.2621 | 0.3367 |
 283 |  0.2986 | 0.7067 | 0.6110 | 0.5554 | 0.1107 | 0.5461 |
 284 |  0.3336 | 0.6667 | 0.6558 | 0.5778 | 0.1555 | 0.5602 |
 285 |  0.2829 | 0.7230 | 0.6599 | 0.5772 | 0.1543 | 0.5574 |
 286 |  0.2906 | 0.6972 | 0.6558 | 0.5842 | 0.1685 | 0.5697 |
 287 |  0.2762 | 0.7040 | 0.6538 | 0.5958 | 0.1917 | 0.5865 |
 288 |  0.3340 | 0.6008 | 0.6415 | 0.5912 | 0.1824 | 0.5841 |
 289 |  0.2803 | 0.6965 | 0.5031 | 0.5020 | 0.0039 | 0.5020 |
 290 |  0.2814 | 0.7026 | 0.4603 | 0.4776 | 0.0447 | 0.4766 |
 291 |  0.3297 | 0.6354 | 0.6782 | 0.6116 | 0.2232 | 0.5996 |
 292 |  0.3456 | 0.6029 | 0.6558 | 0.6586 | 0.3172 | 0.6586 |
 293 |  0.3519 | 0.5750 | 0.6354 | 0.6067 | 0.2133 | 0.6044 |
 294 |  0.3359 | 0.6246 | 0.6008 | 0.5908 | 0.1817 | 0.5905 |
 295 |  0.3455 | 0.6626 | 0.6191 | 0.6026 | 0.2053 | 0.6019 |
 296 |  0.3413 | 0.5933 | 0.4969 | 0.5110 | 0.0219 | 0.5103 |
 297 |  0.3260 | 0.6124 | 0.5642 | 0.5607 | 0.1215 | 0.5607 |
 298 |  0.3866 | 0.5675 | 0.5255 | 0.5293 | 0.0587 | 0.5293 |

Early stop @ epoch 298  (best_epoch=148)

============================================================
KET QUA -- test_year=2019
============================================================
Best epoch : 148
Metric         Paper    VerB    Diff
----------------------------------------
Accuracy       80.45   77.19  -3.26
Recall_m       75.44   74.63  -0.81
KS             50.88   49.27  -1.61
G-mean         74.89   74.49  -0.40

#### 6.7 VerB — Test year 2020

In [105]:
%cd /content/ACRF-RNN/Code
!python main.py \
    --data-path /content/project_data/processed_flat.json \
    --test-year 2020 --max-epoch 800 --wait-epoch 150 --device 0 \
    2>&1 | tee /content/project_outputs/run_2020.log

/content/ACRF-RNN/Code

ACRF-RNN | test_year=2020 | device=cuda:0
============================================================
Loaded: 10 years | x=(10, 491, 208) | y=(10, 491, 1)
Years : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020]
Train : [2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019]  (9 years)
Eval  : [2014, 2015, 2017, 2018, 2019, 2020]
Train labels: fraud=1097, benign=3322
Model params: 972,937

  Ep |    Loss |  TrAcc |  EvAcc |  Rcl_m |     KS |     GM |
-------------------------------------------------------------
test_year=2020:  16%|█▌        | 129/800 ep [00:11<00:55]   0 |  0.4190 | 0.5570 | 0.5886 | 0.5537 | 0.1074 | 0.5511 | best
   1 |  0.3874 | 0.4893 | 0.5519 | 0.5315 | 0.0630 | 0.5305 |
   2 |  0.3752 | 0.5703 | 0.6069 | 0.5557 | 0.1113 | 0.5500 | best
   3 |  0.3077 | 0.6436 | 0.7556 | 0.6824 | 0.3648 | 0.6731 | best
   4 |  0.2626 | 0.7449 | 0.7128 | 0.6199 | 0.2397 | 0.6031 |
   5 |  0.2900 | 0.7179 | 0.7902 | 0.6897 | 0.3793 | 0.6721 | best
   6 |  0.3055 | 0.6650 | 0.7617 | 0.6815 | 0.3631 | 0.6703 |
   7 |  0.2346 | 0.7811 | 0.7026 | 0.6320 | 0.2640 | 0.6226 |
   8 |  0.2474 | 0.7424 | 0.7108 | 0.6369 | 0.2739 | 0.6267 |
   9 |  0.2437 | 0.7469 | 0.2872 | 0.3481 | 0.3038 | 0.3352 |
  10 |  0.3612 | 0.5698 | 0.3503 | 0.4230 | 0.1540 | 0.4079 |
  11 |  0.4915 | 0.4134 | 0.4155 | 0.4396 | 0.1208 | 0.4380 |
  12 |  0.4698 | 0.4562 | 0.4521 | 0.4893 | 0.0214 | 0.4859 |
  13 |  0.4536 | 0.3997 | 0.4644 | 0.4876 | 0.0249 | 0.4862 |
  14 |  0.3936 | 0.4735 | 0.4440 | 0.4660 | 0.0679 | 0.4648 |
  15 |  0.3517 | 0.5453 | 0.4033 | 0.4551 | 0.0898 | 0.4480 |
  16 |  0.3635 | 0.5331 | 0.3849 | 0.4486 | 0.1029 | 0.4377 |
  17 |  0.3308 | 0.6013 | 0.5540 | 0.4915 | 0.0170 | 0.4820 |
  18 |  0.3246 | 0.6202 | 0.5723 | 0.5118 | 0.0235 | 0.5032 |
  19 |  0.3088 | 0.6492 | 0.6354 | 0.5226 | 0.0451 | 0.4928 |
  20 |  0.2862 | 0.6935 | 0.6395 | 0.5296 | 0.0592 | 0.5019 |
  21 |  0.3291 | 0.6314 | 0.5438 | 0.4945 | 0.0110 | 0.4886 |
  22 |  0.2818 | 0.7179 | 0.6578 | 0.5407 | 0.0815 | 0.5098 |
  23 |  0.3913 | 0.5580 | 0.5764 | 0.4913 | 0.0173 | 0.4736 |
  24 |  0.2934 | 0.7057 | 0.5601 | 0.4952 | 0.0096 | 0.4850 |
  25 |  0.3203 | 0.6471 | 0.5743 | 0.5084 | 0.0169 | 0.4982 |
  26 |  0.3086 | 0.6594 | 0.5804 | 0.5121 | 0.0243 | 0.5012 |
  27 |  0.2869 | 0.6736 | 0.5988 | 0.5324 | 0.0648 | 0.5225 |
  28 |  0.2669 | 0.6914 | 0.6456 | 0.5700 | 0.1399 | 0.5579 |
  29 |  0.2491 | 0.7271 | 0.6640 | 0.5902 | 0.1804 | 0.5792 |
  30 |  0.2368 | 0.7637 | 0.6823 | 0.6013 | 0.2027 | 0.5883 |
  31 |  0.2288 | 0.7785 | 0.6925 | 0.6075 | 0.2150 | 0.5933 |
  32 |  0.2243 | 0.7887 | 0.6945 | 0.5996 | 0.1992 | 0.5815 |
  33 |  0.2177 | 0.7974 | 0.7026 | 0.6045 | 0.2090 | 0.5854 |
  34 |  0.2126 | 0.8050 | 0.7088 | 0.6082 | 0.2165 | 0.5882 |
  35 |  0.2133 | 0.8086 | 0.7047 | 0.5966 | 0.1932 | 0.5729 |
  36 |  0.2074 | 0.8187 | 0.7067 | 0.5978 | 0.1957 | 0.5739 |
  37 |  0.2048 | 0.8218 | 0.7067 | 0.5978 | 0.1957 | 0.5739 |
  38 |  0.2030 | 0.8243 | 0.7108 | 0.6003 | 0.2006 | 0.5757 |
  39 |  0.2015 | 0.8243 | 0.7312 | 0.6081 | 0.2161 | 0.5778 |
  40 |  0.2022 | 0.8248 | 0.7352 | 0.6060 | 0.2119 | 0.5724 |
  41 |  0.2030 | 0.8254 | 0.7373 | 0.6072 | 0.2144 | 0.5732 |
  42 |  0.2016 | 0.8279 | 0.7617 | 0.6220 | 0.2440 | 0.5837 |
  43 |  0.2014 | 0.8213 | 0.7536 | 0.6171 | 0.2341 | 0.5802 |
  44 |  0.2021 | 0.8223 | 0.3238 | 0.4115 | 0.1769 | 0.3888 |
  45 |  0.2025 | 0.8228 | 0.7108 | 0.5728 | 0.1457 | 0.5320 |
  46 |  0.2021 | 0.8208 | 0.3870 | 0.4361 | 0.1279 | 0.4295 |
  47 |  0.2027 | 0.8223 | 0.6212 | 0.5277 | 0.0553 | 0.5077 |
  48 |  0.2027 | 0.8228 | 0.6232 | 0.5197 | 0.0395 | 0.4947 |
  49 |  0.2025 | 0.8223 | 0.5764 | 0.5142 | 0.0285 | 0.5053 |
  50 |  0.3357 | 0.6680 | 0.5743 | 0.4947 | 0.0106 | 0.4793 |
  51 |  0.2042 | 0.8203 | 0.5825 | 0.5088 | 0.0176 | 0.4960 |
  52 |  0.2061 | 0.8167 | 0.5804 | 0.5030 | 0.0059 | 0.4886 |
  53 |  0.3259 | 0.6787 | 0.5804 | 0.4984 | 0.0032 | 0.4821 |
  54 |  0.2131 | 0.8080 | 0.5804 | 0.4984 | 0.0032 | 0.4821 |
  55 |  0.2221 | 0.7994 | 0.5723 | 0.4889 | 0.0223 | 0.4717 |
  56 |  0.3079 | 0.6940 | 0.5825 | 0.4996 | 0.0007 | 0.4831 |
  57 |  0.4484 | 0.5311 | 0.4501 | 0.4789 | 0.0422 | 0.4769 |
  58 |  0.2835 | 0.7205 | 0.5906 | 0.5091 | 0.0183 | 0.4935 |
  59 |  0.2686 | 0.7368 | 0.6008 | 0.5153 | 0.0306 | 0.4982 |
  60 |  0.2587 | 0.7475 | 0.6110 | 0.5123 | 0.0247 | 0.4893 |
  61 |  0.2551 | 0.7531 | 0.4277 | 0.4745 | 0.0510 | 0.4690 |
  62 |  0.2541 | 0.7551 | 0.4277 | 0.4745 | 0.0510 | 0.4690 |
  63 |  0.2516 | 0.7587 | 0.4257 | 0.4733 | 0.0535 | 0.4676 |
  64 |  0.4251 | 0.5596 | 0.6151 | 0.5148 | 0.0296 | 0.4911 |
  65 |  0.2435 | 0.7673 | 0.6171 | 0.5160 | 0.0321 | 0.4920 |
  66 |  0.2429 | 0.7678 | 0.4257 | 0.4733 | 0.0535 | 0.4676 |
  67 |  0.3820 | 0.6049 | 0.6171 | 0.5160 | 0.0321 | 0.4920 |
  68 |  0.2405 | 0.7709 | 0.4277 | 0.4745 | 0.0510 | 0.4690 |
  69 |  0.2395 | 0.7724 | 0.6151 | 0.5148 | 0.0296 | 0.4911 |
  70 |  0.3784 | 0.6100 | 0.6151 | 0.5148 | 0.0296 | 0.4911 |
  71 |  0.3905 | 0.5973 | 0.6151 | 0.5148 | 0.0296 | 0.4911 |
  72 |  0.3760 | 0.6008 | 0.3320 | 0.4073 | 0.1854 | 0.3905 |
  73 |  0.3170 | 0.6614 | 0.2953 | 0.3851 | 0.2298 | 0.3594 |
  74 |  0.4695 | 0.4929 | 0.2933 | 0.3839 | 0.2323 | 0.3576 |
  75 |  0.3955 | 0.5754 | 0.7515 | 0.6067 | 0.2134 | 0.5642 |
  76 |  0.2950 | 0.6909 | 0.7515 | 0.6067 | 0.2134 | 0.5642 |
  77 |  0.3960 | 0.5748 | 0.2933 | 0.3839 | 0.2323 | 0.3576 |
  78 |  0.2988 | 0.6858 | 0.2933 | 0.3839 | 0.2323 | 0.3576 |
  79 |  0.3006 | 0.6828 | 0.2953 | 0.3897 | 0.2207 | 0.3616 |
  80 |  0.3936 | 0.5774 | 0.7475 | 0.5996 | 0.1993 | 0.5548 |
  81 |  0.3908 | 0.5804 | 0.2994 | 0.3876 | 0.2249 | 0.3630 |
  82 |  0.3126 | 0.6675 | 0.3035 | 0.3900 | 0.2200 | 0.3666 |
  83 |  0.3144 | 0.6650 | 0.3014 | 0.3888 | 0.2224 | 0.3648 |
  84 |  0.4051 | 0.5652 | 0.2912 | 0.3780 | 0.2439 | 0.3536 |
  85 |  0.3801 | 0.5998 | 0.2974 | 0.3863 | 0.2274 | 0.3612 |
  86 |  0.6238 | 0.3259 | 0.2912 | 0.3780 | 0.2439 | 0.3536 |
  87 |  0.6373 | 0.3136 | 0.2872 | 0.3710 | 0.2580 | 0.3478 |
  88 |  0.7366 | 0.1986 | 0.3014 | 0.3842 | 0.2316 | 0.3625 |
  89 |  0.7163 | 0.2077 | 0.3096 | 0.3891 | 0.2217 | 0.3694 |
  90 |  0.6780 | 0.2235 | 0.3910 | 0.4431 | 0.1138 | 0.4358 |
  91 |  0.5141 | 0.3503 | 0.5031 | 0.5064 | 0.0129 | 0.5064 |
  92 |  0.3724 | 0.5514 | 0.6090 | 0.5615 | 0.1229 | 0.5567 |
  93 |  0.2710 | 0.7128 | 0.6843 | 0.6026 | 0.2051 | 0.5893 |
  94 |  0.2103 | 0.8131 | 0.7067 | 0.6070 | 0.2140 | 0.5873 |
  95 |  0.1959 | 0.8289 | 0.6599 | 0.5603 | 0.1206 | 0.5389 |
  96 |  0.2040 | 0.8040 | 0.6619 | 0.5524 | 0.1047 | 0.5260 |
  97 |  0.2029 | 0.8070 | 0.6680 | 0.5561 | 0.1121 | 0.5287 |
  98 |  0.1966 | 0.8080 | 0.6782 | 0.5622 | 0.1245 | 0.5331 |
  99 |  0.1948 | 0.8116 | 0.6782 | 0.5668 | 0.1336 | 0.5403 |
 100 |  0.1940 | 0.8111 | 0.6864 | 0.5809 | 0.1618 | 0.5578 |
 101 |  0.1941 | 0.8131 | 0.6945 | 0.5858 | 0.1717 | 0.5615 |
 102 |  0.1932 | 0.8136 | 0.6986 | 0.5975 | 0.1949 | 0.5769 |
 103 |  0.1931 | 0.8162 | 0.7047 | 0.6058 | 0.2115 | 0.5863 |
 104 |  0.1931 | 0.8162 | 0.7047 | 0.6012 | 0.2024 | 0.5797 |
 105 |  0.1926 | 0.8177 | 0.7047 | 0.6012 | 0.2024 | 0.5797 |
 106 |  0.1921 | 0.8172 | 0.7067 | 0.6070 | 0.2140 | 0.5873 |
 107 |  0.1910 | 0.8177 | 0.7088 | 0.6082 | 0.2165 | 0.5882 |
 108 |  0.1909 | 0.8187 | 0.7067 | 0.6070 | 0.2140 | 0.5873 |
 109 |  0.1899 | 0.8198 | 0.7067 | 0.6070 | 0.2140 | 0.5873 |
 110 |  0.1889 | 0.8203 | 0.7067 | 0.6070 | 0.2140 | 0.5873 |
 111 |  0.1888 | 0.8218 | 0.7047 | 0.6012 | 0.2024 | 0.5797 |
 112 |  0.1884 | 0.8213 | 0.7088 | 0.6082 | 0.2165 | 0.5882 |
 113 |  0.1882 | 0.8213 | 0.7088 | 0.6128 | 0.2256 | 0.5947 |
 114 |  0.1858 | 0.8223 | 0.7088 | 0.6128 | 0.2256 | 0.5947 |
 115 |  0.1846 | 0.8238 | 0.7108 | 0.6140 | 0.2281 | 0.5957 |
 116 |  0.1832 | 0.8274 | 0.7088 | 0.6082 | 0.2165 | 0.5882 |
 117 |  0.1820 | 0.8289 | 0.7067 | 0.6070 | 0.2140 | 0.5873 |
 118 |  0.1811 | 0.8289 | 0.7128 | 0.6153 | 0.2305 | 0.5967 |
 119 |  0.1802 | 0.8340 | 0.7128 | 0.6153 | 0.2305 | 0.5967 |
 120 |  0.1790 | 0.8350 | 0.7189 | 0.6190 | 0.2380 | 0.5996 |
 121 |  0.1775 | 0.8391 | 0.7251 | 0.6273 | 0.2545 | 0.6089 |
 122 |  0.1775 | 0.8437 | 0.7251 | 0.6273 | 0.2545 | 0.6089 |
 123 |  0.1766 | 0.8442 | 0.7271 | 0.6285 | 0.2570 | 0.6099 |
 124 |  0.1767 | 0.8452 | 0.7312 | 0.6310 | 0.2619 | 0.6118 |
 125 |  0.1752 | 0.8462 | 0.7413 | 0.6509 | 0.3018 | 0.6358 |
 126 |  0.1735 | 0.8473 | 0.7312 | 0.6264 | 0.2528 | 0.6053 |
 127 |  0.1715 | 0.8483 | 0.7312 | 0.6264 | 0.2528 | 0.6053 |
 128 |  0.1714 | 0.8478 | 0.7312 | 0.6264 | 0.2528 | 0.6053 |
Early stop ep155 | best ep5:  20%|█▉        | 156/800 ep [00:14<00:59]

 130 |  0.1675 | 0.8518 | 0.7291 | 0.6252 | 0.2503 | 0.6043 |
 131 |  0.1657 | 0.8529 | 0.7251 | 0.6227 | 0.2454 | 0.6024 |
 132 |  0.1636 | 0.8600 | 0.7271 | 0.6239 | 0.2478 | 0.6034 |
 133 |  0.1689 | 0.8529 | 0.7332 | 0.6276 | 0.2552 | 0.6062 |
 134 |  0.1607 | 0.8574 | 0.7332 | 0.6368 | 0.2736 | 0.6192 |
 135 |  0.1662 | 0.8549 | 0.7291 | 0.6297 | 0.2595 | 0.6109 |
 136 |  0.1624 | 0.8590 | 0.7251 | 0.6181 | 0.2362 | 0.5958 |
 137 |  0.1592 | 0.8605 | 0.7251 | 0.6181 | 0.2362 | 0.5958 |
 138 |  0.1586 | 0.8656 | 0.7291 | 0.6252 | 0.2503 | 0.6043 |
 139 |  0.1566 | 0.8676 | 0.7332 | 0.6368 | 0.2736 | 0.6192 |
 140 |  0.1557 | 0.8773 | 0.7373 | 0.6392 | 0.2785 | 0.6212 |
 141 |  0.1525 | 0.8798 | 0.7413 | 0.6417 | 0.2834 | 0.6231 |
 142 |  0.1510 | 0.8798 | 0.7475 | 0.6454 | 0.2908 | 0.6260 |
 143 |  0.1561 | 0.8763 | 0.7434 | 0.6475 | 0.2951 | 0.6305 |
 144 |  0.1530 | 0.8824 | 0.7434 | 0.6475 | 0.2951 | 0.6305 |
 145 |  0.1500 | 0.8905 | 0.7434 | 0.6475 | 0.2951 | 0.6305 |
 146 |  0.1479 | 0.8900 | 0.7434 | 0.6521 | 0.3042 | 0.6368 |
 147 |  0.1492 | 0.8900 | 0.7454 | 0.6533 | 0.3067 | 0.6378 |
 148 |  0.1549 | 0.8839 | 0.7515 | 0.6479 | 0.2958 | 0.6279 |
 149 |  0.1475 | 0.8905 | 0.7515 | 0.6570 | 0.3141 | 0.6408 |
 150 |  0.1442 | 0.8971 | 0.7475 | 0.6546 | 0.3092 | 0.6388 |
 151 |  0.1477 | 0.8946 | 0.7495 | 0.6604 | 0.3208 | 0.6460 |
 152 |  0.1419 | 0.8977 | 0.7495 | 0.6604 | 0.3208 | 0.6460 |
 153 |  0.3221 | 0.6685 | 0.7495 | 0.6604 | 0.3208 | 0.6460 |
 154 |  0.1404 | 0.8992 | 0.7495 | 0.6604 | 0.3208 | 0.6460 |
 155 |  0.1396 | 0.9012 | 0.4358 | 0.3924 | 0.2152 | 0.3867 |

Early stop @ epoch 155  (best_epoch=5)

============================================================
KET QUA -- test_year=2020
============================================================
Best epoch : 5
Metric         Paper    VerB    Diff
----------------------------------------
Accuracy       79.43   79.02  -0.41
Recall_m       71.96   68.97  -2.99
KS             43.92   37.93  -5.99
G-mean         71.04   67.21  -3.83

## Giai đoạn 7 — Tổng hợp và so sánh kết quả

### 7.1 Bảng VerA — best theo train_loss (tiêu chí tác giả)

In [106]:
import re, pandas as pd, os

pat = re.compile(
    r"\s*(\d+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|"
    r"\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)"
)


def parse_log_vera(log_path, test_year):
    """VerA: best epoch = epoch có train_loss thấp nhất (theo tác giả)."""
    epoch_rows, best_loss_row, best_ks_row, last_ep = [], {"loss": float("inf")}, {"raw": -1}, None
    with open(log_path) as f:
        for line in f:
            m = pat.match(line)
            if m:
                ep, loss, tr_acc, ev_acc, rcl, ks, gm = [float(x) for x in m.groups()]
                epoch_rows.append(dict(
                    test_year=test_year, epoch=int(ep),
                    loss=round(loss,4), train_acc=round(tr_acc*100,2),
                    eval_acc=round(ev_acc*100,2), eval_recall_macro=round(rcl*100,2),
                    eval_ks=round(ks*100,2), eval_gm=round(gm*100,2),
                ))
                if loss < best_loss_row["loss"]:
                    best_loss_row = {"loss": round(loss,4), "epoch": int(ep),
                        "eval_acc": round(ev_acc*100,2), "eval_recall_macro": round(rcl*100,2),
                        "eval_ks":  round(ks*100,2),    "eval_gm": round(gm*100,2)}
                if ks > best_ks_row["raw"]:
                    best_ks_row = {"raw": ks, "epoch": int(ep), "val": round(ks*100,2)}
                last_ep = {"epoch": int(ep), "eval_acc": round(ev_acc*100,2),
                    "eval_recall_macro": round(rcl*100,2),
                    "eval_ks": round(ks*100,2), "eval_gm": round(gm*100,2)}
    return epoch_rows, {
        "test_year": test_year,
        "best_epoch_by_loss":      best_loss_row.get("epoch"),
        "best_train_loss":         best_loss_row.get("loss"),
        "best_eval_acc":           best_loss_row.get("eval_acc"),
        "best_eval_recall_macro":  best_loss_row.get("eval_recall_macro"),
        "best_eval_ks":            best_loss_row.get("eval_ks"),
        "best_eval_gm":            best_loss_row.get("eval_gm"),
        "best_epoch_by_ks":        best_ks_row.get("epoch"),
        "ref_best_ks":             best_ks_row.get("val"),
        "final_eval_acc":          last_ep["eval_acc"]          if last_ep else None,
        "final_eval_recall_macro": last_ep["eval_recall_macro"] if last_ep else None,
        "final_eval_ks":           last_ep["eval_ks"]           if last_ep else None,
        "final_eval_gm":           last_ep["eval_gm"]           if last_ep else None,
    }


vera_logs = {2018: "/content/project_outputs/run_vera_2018.log",
             2019: "/content/project_outputs/run_vera_2019.log",
             2020: "/content/project_outputs/run_vera_2020.log"}

vera_epochs, vera_rows = [], []
for yr, path in vera_logs.items():
    if not os.path.exists(path):
        print(f"Chưa có {path}"); continue
    rows, summary = parse_log_vera(path, yr)
    vera_epochs.extend(rows); vera_rows.append(summary)

df_vera_epochs  = pd.DataFrame(vera_epochs)
df_vera_summary = pd.DataFrame(vera_rows)
print(f"VerA epoch rows: {len(df_vera_epochs)}")
df_vera_summary

VerA epoch rows: 812

,test_year,best_epoch_by_loss,best_train_loss,best_eval_acc,best_eval_recall_macro,best_eval_ks,best_eval_gm,best_epoch_by_ks,ref_best_ks,final_eval_acc,final_eval_recall_macro,final_eval_ks,final_eval_gm
0,2018,22,0.0980,75.36,69.54,39.07,68.48,46,42.96,71.49,64.62,29.24,63.03
1,2019,109,0.0999,77.39,73.79,47.59,73.51,148,49.27,55.80,55.68,11.36,55.68
2,2020,227,0.0863,81.47,73.20,46.39,72.08,210,47.98,80.24,72.45,44.91,71.46

### Nhận xét 7.1 — Kết quả VerA

Kết quả VerA cho thấy mô hình đạt mức tái hiện khá tốt so với bài báo gốc ở cả ba năm kiểm thử. Ở năm 2018, VerA đạt KS = 39.07%, Recallm = 69.54% và G-mean = 68.48%, chỉ thấp hơn bài báo một khoảng nhỏ, cho thấy chất lượng mô hình đã khá sát với kết quả công bố. Ở năm 2019, VerA tiếp tục duy trì mức kết quả tốt với KS = 47.59%, Recallm = 73.79% và G-mean = 73.51%, vẫn nằm rất gần bài báo. Đặc biệt, ở năm 2020, VerA đạt KS = 46.39%, Recallm = 73.20% và G-mean = 72.08%, đều cao hơn bài báo gốc, cho thấy thiết lập này hoạt động rất tốt ở năm kiểm thử cuối.

Một điểm đáng chú ý là chỉ số `final_eval_*` của VerA ở một số năm, đặc biệt năm 2019, giảm khá mạnh so với `best_*`. Điều này cho thấy nếu lấy epoch cuối cùng thì kết quả sẽ kém hơn đáng kể, và việc chọn best epoch theo train loss là cần thiết để tránh hiện tượng mô hình suy giảm hiệu quả ở giai đoạn cuối huấn luyện.

Nhìn chung, VerA có ưu điểm là ổn định, bám sát bài báo ở cả ba năm và đặc biệt mạnh ở năm 2020.

### 7.2 Bảng VerB — best theo eval KS (tiêu chí bài báo)

In [107]:
def parse_log_verb(log_path, test_year):
    """VerB: best epoch = epoch có eval KS cao nhất (theo bài báo Section 5.3)."""
    epoch_rows  = []
    best_ks_row = {"raw": -1}
    last_ep     = None
    with open(log_path) as f:
        for line in f:
            m = pat.match(line)
            if m:
                ep, loss, tr_acc, ev_acc, rcl, ks, gm = [float(x) for x in m.groups()]
                epoch_rows.append(dict(
                    test_year=test_year, epoch=int(ep),
                    loss=round(loss,4), train_acc=round(tr_acc*100,2),
                    eval_acc=round(ev_acc*100,2), eval_recall_macro=round(rcl*100,2),
                    eval_ks=round(ks*100,2), eval_gm=round(gm*100,2),
                ))
                if ks > best_ks_row["raw"]:
                    best_ks_row = {"raw": ks, "epoch": int(ep),
                        "eval_acc": round(ev_acc*100,2), "eval_recall_macro": round(rcl*100,2),
                        "eval_ks":  round(ks*100,2),    "eval_gm": round(gm*100,2)}
                last_ep = {"epoch": int(ep), "eval_acc": round(ev_acc*100,2),
                    "eval_recall_macro": round(rcl*100,2),
                    "eval_ks": round(ks*100,2), "eval_gm": round(gm*100,2)}
    return epoch_rows, {
        "test_year":               test_year,
        "best_epoch_by_ks":        best_ks_row.get("epoch"),
        "best_eval_acc":           best_ks_row.get("eval_acc"),
        "best_eval_recall_macro":  best_ks_row.get("eval_recall_macro"),
        "best_eval_ks":            best_ks_row.get("eval_ks"),
        "best_eval_gm":            best_ks_row.get("eval_gm"),
        "final_eval_acc":          last_ep["eval_acc"]          if last_ep else None,
        "final_eval_recall_macro": last_ep["eval_recall_macro"] if last_ep else None,
        "final_eval_ks":           last_ep["eval_ks"]           if last_ep else None,
        "final_eval_gm":           last_ep["eval_gm"]           if last_ep else None,
    }


verb_logs = {2018: "/content/project_outputs/run_2018.log",
             2019: "/content/project_outputs/run_2019.log",
             2020: "/content/project_outputs/run_2020.log"}

verb_epochs, verb_rows = [], []
for yr, path in verb_logs.items():
    if not os.path.exists(path):
        print(f"Chưa có {path}"); continue
    rows, summary = parse_log_verb(path, yr)
    verb_epochs.extend(rows); verb_rows.append(summary)

df_verb_epochs  = pd.DataFrame(verb_epochs)
df_verb_summary = pd.DataFrame(verb_rows)
print(f"VerB epoch rows: {len(df_verb_epochs)}")
df_verb_summary

VerB epoch rows: 649

,test_year,best_epoch_by_ks,best_eval_acc,best_eval_recall_macro,best_eval_ks,best_eval_gm,final_eval_acc,final_eval_recall_macro,final_eval_ks,final_eval_gm
0,2018,46,78.62,71.48,42.96,69.93,75.36,67.74,35.48,65.88
1,2019,148,77.19,74.63,49.27,74.49,52.55,52.93,5.87,52.93
2,2020,5,79.02,68.97,37.93,67.21,43.58,39.24,21.52,38.67

### Nhận xét 7.2 — Kết quả VerB

Kết quả VerB cho thấy khi chọn best epoch theo eval KS, mô hình đạt chất lượng rất tốt ở các năm 2018 và 2019. Cụ thể, ở năm 2018, VerB đạt KS = 42.96%, Recallm = 71.48% và G-mean = 69.93%, đều ngang bằng hoặc nhỉnh hơn bài báo gốc. Ở năm 2019, VerB tiếp tục cho kết quả rất sát bài báo với KS = 49.27%, Recallm = 74.63% và G-mean = 74.49%, sai lệch rất nhỏ trên cả ba chỉ số chính. Điều này cho thấy thiết lập chọn best theo KS giúp mô hình bám sát mục tiêu đánh giá của bài báo hơn ở hai năm đầu.

Tuy nhiên, ở năm 2020, VerB suy giảm rõ hơn so với VerA, với KS = 37.93%, Recallm = 68.97% và G-mean = 67.21%. Dù vẫn đạt tiêu chí đề cương, kết quả này thấp hơn đáng kể so với bài báo và cũng thấp hơn VerA ở cùng năm. Ngoài ra, các chỉ số `final_eval_*` của VerB sau epoch tốt nhất giảm mạnh, đặc biệt ở năm 2019 và 2020, cho thấy mô hình rất nhạy với việc chọn epoch và không nên sử dụng kết quả ở epoch cuối cùng.

Nhìn chung, VerB có ưu thế rõ rệt ở các năm 2018 và 2019, nhưng độ ổn định giữa các năm không cao bằng VerA.

### 7.3 Bảng so sánh 3 chiều: Paper | VerA | VerB

Cột `diff_A` = VerA − Paper, `diff_B` = VerB − Paper, `diff_B_A` = VerB − VerA.

`diff_B_A` định lượng tác động của việc đổi early stopping và gradient accumulation.

In [108]:
paper = pd.DataFrame([
    {"test_year": 2018, "paper_acc": 77.60, "paper_rcl": 70.79, "paper_ks": 41.58, "paper_gm": 69.37},
    {"test_year": 2019, "paper_acc": 80.45, "paper_rcl": 75.44, "paper_ks": 50.88, "paper_gm": 74.89},
    {"test_year": 2020, "paper_acc": 79.43, "paper_rcl": 71.96, "paper_ks": 43.92, "paper_gm": 71.04},
])

# Lấy VerA metrics tại best_by_loss
vera_best = df_vera_summary[["test_year","best_eval_acc","best_eval_recall_macro",
                              "best_eval_ks","best_eval_gm"]].rename(columns={
    "best_eval_acc":           "vera_acc",
    "best_eval_recall_macro":  "vera_rcl",
    "best_eval_ks":            "vera_ks",
    "best_eval_gm":            "vera_gm",
})

# Lấy VerB metrics tại best_by_ks
verb_best = df_verb_summary[["test_year","best_eval_acc","best_eval_recall_macro",
                              "best_eval_ks","best_eval_gm"]].rename(columns={
    "best_eval_acc":           "verb_acc",
    "best_eval_recall_macro":  "verb_rcl",
    "best_eval_ks":            "verb_ks",
    "best_eval_gm":            "verb_gm",
})

cmp3 = paper.merge(vera_best, on="test_year").merge(verb_best, on="test_year")

for m in ["acc", "rcl", "ks", "gm"]:
    cmp3[f"diff_A_{m}"] = (cmp3[f"vera_{m}"] - cmp3[f"paper_{m}"]).round(2)
    cmp3[f"diff_B_{m}"] = (cmp3[f"verb_{m}"] - cmp3[f"paper_{m}"]).round(2)
    cmp3[f"diff_BA_{m}"] = (cmp3[f"verb_{m}"] - cmp3[f"vera_{m}"]).round(2)

# Hiển thị bảng chính
display(cmp3[["test_year",
    "paper_ks", "vera_ks", "diff_A_ks", "verb_ks", "diff_B_ks", "diff_BA_ks",
    "paper_rcl","vera_rcl","diff_A_rcl","verb_rcl","diff_B_rcl","diff_BA_rcl",
    "paper_gm", "vera_gm", "diff_A_gm", "verb_gm", "diff_B_gm", "diff_BA_gm",
]])

,test_year,paper_ks,vera_ks,diff_A_ks,verb_ks,diff_B_ks,diff_BA_ks,paper_rcl,vera_rcl,diff_A_rcl,verb_rcl,diff_B_rcl,diff_BA_rcl,paper_gm,vera_gm,diff_A_gm,verb_gm,diff_B_gm,diff_BA_gm
0,2018,41.58,39.07,-2.51,42.96,1.38,3.89,70.79,69.54,-1.25,71.48,0.69,1.94,69.37,68.48,-0.89,69.93,0.56,1.45
1,2019,50.88,47.59,-3.29,49.27,-1.61,1.68,75.44,73.79,-1.65,74.63,-0.81,0.84,74.89,73.51,-1.38,74.49,-0.40,0.98
2,2020,43.92,46.39,2.47,37.93,-5.99,-8.46,71.96,73.20,1.24,68.97,-2.99,-4.23,71.04,72.08,1.04,67.21,-3.83,-4.87

### Nhận xét 7.3 — So sánh Paper, VerA và VerB

Bảng so sánh ba chiều cho thấy cả VerA và VerB đều tiệm cận khá tốt với bài báo gốc, tuy nhiên mỗi phiên bản có ưu thế khác nhau theo từng năm kiểm thử. Ở năm 2018, VerB vượt VerA rõ rệt trên cả KS, Recallm và G-mean; đồng thời kết quả của VerB cũng nhỉnh hơn bài báo gốc. Ở năm 2019, VerB tiếp tục tốt hơn VerA, với mức sai lệch so với bài báo nhỏ hơn trên cả ba chỉ số chính. Điều này cho thấy việc chọn best epoch theo eval KS giúp mô hình phù hợp hơn với mục tiêu đánh giá ở hai năm này.

Ngược lại, ở năm 2020, VerA lại vượt trội hơn VerB khá rõ. VerA không chỉ tốt hơn VerB ở cả KS, Recallm và G-mean, mà còn đạt kết quả cao hơn bài báo gốc ở cả ba chỉ số. Trong khi đó, VerB giảm mạnh ở năm này, cho thấy tiêu chí chọn best theo KS không phải lúc nào cũng cho kết quả tốt nhất trên mọi tập kiểm thử.

Từ bảng này có thể rút ra rằng khác biệt giữa VerA và VerB phản ánh ảnh hưởng của chiến lược chọn best epoch. VerB phù hợp hơn ở các năm 2018 và 2019, còn VerA ổn định và hiệu quả hơn ở năm 2020. Như vậy, không có một tiêu chí chọn epoch tối ưu tuyệt đối cho mọi năm, và việc lựa chọn tiêu chí cần được xem xét cùng với đặc điểm của từng tập dữ liệu kiểm thử.

### 7.4 Kiểm tra tiêu chí đề cương

In [109]:
print("=" * 55)
print(f"  TIÊU CHÍ ĐỀ CƯƠNG: KS>=35%, Rcl+-5%, GM+-5%")
print("=" * 55)
for ver, ks_col, diff_col in [("VerA","vera_ks","A"), ("VerB","verb_ks","B")]:
    ks_ok  = (cmp3[ks_col] >= 35).any()
    rcl_ok = (cmp3[f"diff_{diff_col}_rcl"].abs() <= 5).all()
    gm_ok  = (cmp3[f"diff_{diff_col}_gm"].abs() <= 5).all()
    print(f"\n{ver}:")
    print(f"  KS >= 35% (ít nhất 1 năm) : {'OK' if ks_ok else 'FAIL'}")
    print(f"  Recallm trong +-5%        : {'OK' if rcl_ok else 'FAIL'}")
    print(f"  G-mean  trong +-5%        : {'OK' if gm_ok else 'FAIL'}")
    if ks_ok and rcl_ok and gm_ok:
        print(f"  => Đạt tiêu chí đề cương")
    else:
        print(f"  => Chưa đạt tiêu chí đề cương")

=======================================================
  TIÊU CHÍ ĐỀ CƯƠNG: KS>=35%, Rcl+-5%, GM+-5%
=======================================================

VerA:
  KS >= 35% (ít nhất 1 năm) : OK
  Recallm trong +-5%        : OK
  G-mean  trong +-5%        : OK
  => Đạt tiêu chí đề cương

VerB:
  KS >= 35% (ít nhất 1 năm) : OK
  Recallm trong +-5%        : OK
  G-mean  trong +-5%        : OK
  => Đạt tiêu chí đề cương

### Nhận xét 7.4 — Đối chiếu với tiêu chí đề cương

Kết quả kiểm tra cho thấy cả VerA và VerB đều đạt đầy đủ các tiêu chí chính đã đặt ra trong đề cương. Cụ thể, cả hai phiên bản đều có KS lớn hơn hoặc bằng 35% ở ít nhất một năm kiểm thử; đồng thời Recallm và G-mean đều nằm trong khoảng sai lệch ±5% so với bài báo gốc. Điều này có ý nghĩa quan trọng vì nó cho thấy thực nghiệm của nhóm không chỉ chạy được về mặt kỹ thuật mà còn đáp ứng được mục tiêu học thuật đã đề ra từ đầu.

Đối với VerA, việc đạt tiêu chí ở cả ba năm cho thấy thiết lập này có độ ổn định tốt. Đối với VerB, dù kết quả năm 2020 yếu hơn VerA, phiên bản này vẫn đạt đầy đủ tiêu chí đề cương và có ưu thế rõ hơn ở các năm 2018 và 2019. Như vậy, xét theo yêu cầu đề cương, cả hai thiết lập đều có thể xem là thành công.

Từ đây có thể khẳng định rằng phần tái hiện thực nghiệm cơ bản của ACRF-RNN đã hoàn thành đạt yêu cầu, và bộ dữ liệu cùng quy trình thực nghiệm hiện tại là đủ tin cậy để sử dụng trong báo cáo chính thức.

### Kết luận Giai đoạn 7 — Tổng hợp và so sánh kết quả

Tổng hợp từ các bảng kết quả cho thấy nhóm đã tái hiện thành công thực nghiệm cơ bản của mô hình ACRF-RNN trên bộ dữ liệu công khai. Cả VerA và VerB đều đạt tiêu chí đề cương, đồng thời cho kết quả khá sát với bài báo gốc trên các chỉ số quan trọng như KS, Recallm và G-mean. Điều này xác nhận rằng quy trình xử lý dữ liệu và thiết lập thực nghiệm của nhóm là hợp lý.

Về chi tiết, VerB cho kết quả tốt hơn ở các năm 2018 và 2019, tức là gần bài báo hơn ở đa số trường hợp; trong khi đó VerA lại ổn định hơn và vượt trội hơn ở năm 2020. Sự khác biệt này cho thấy chiến lược chọn best epoch có ảnh hưởng trực tiếp đến kết quả cuối cùng của mô hình. Nói cách khác, ngoài kiến trúc mô hình và dữ liệu đầu vào, cách lựa chọn epoch tốt nhất cũng là một yếu tố quan trọng cần được xem xét trong quá trình tái hiện thực nghiệm.

Nhìn chung, kết quả thu được là đủ mạnh để kết luận rằng phần thực nghiệm cơ bản của đề tài đã hoàn thành thành công. Đây là cơ sở quan trọng để sử dụng trong báo cáo chính thức, đồng thời cũng là nền tảng để nhóm tiếp tục chuyển sang các bước tiếp theo như hoàn thiện pipeline dữ liệu và triển khai hướng mở rộng trong đề tài.

### 7.5 Lưu kết quả

In [110]:
os.makedirs("/content/project_outputs", exist_ok=True)

if not df_vera_summary.empty:
    df_vera_epochs.to_csv("/content/project_outputs/epoch_vera.csv", index=False)
    df_vera_summary.to_csv("/content/project_outputs/summary_vera.csv", index=False)

if not df_verb_summary.empty:
    df_verb_epochs.to_csv("/content/project_outputs/epoch_verb.csv", index=False)
    df_verb_summary.to_csv("/content/project_outputs/summary_verb.csv", index=False)

if "cmp3" in dir():
    cmp3.to_csv("/content/project_outputs/compare_3way.csv", index=False)

print("Đã lưu kết quả")
!ls -lh /content/project_outputs/

Đã lưu kết quả
total 348K
-rw-r--r-- 1 root root  54K Jun  2 07:38 acrf-rnn.zip
drwxr-xr-x 2 root root 4.0K Jun  2 08:31 attention_graph
drwxr-xr-x 2 root root 4.0K Jun  2 07:57 checkpoints
-rw-r--r-- 1 root root  674 Jun  2 09:07 compare_3way.csv
-rw-r--r-- 1 root root  36K Jun  2 09:07 epoch_vera.csv
-rw-r--r-- 1 root root  29K Jun  2 09:07 epoch_verb.csv
-rw-r--r-- 1 root root  30K Jun  2 09:07 run_2018.log
-rw-r--r-- 1 root root  48K Jun  2 09:07 run_2019.log
-rw-r--r-- 1 root root  26K Jun  2 09:07 run_2020.log
-rw-r--r-- 1 root root  15K Jun  2 09:05 run_vera_2018.log
-rw-r--r-- 1 root root  24K Jun  2 09:06 run_vera_2019.log
-rw-r--r-- 1 root root  37K Jun  2 09:06 run_vera_2020.log
-rw-r--r-- 1 root root  15K Jun  2 07:57 run_vera_ckpt_2018.log
-rw-r--r-- 1 root root  421 Jun  2 09:07 summary_vera.csv
-rw-r--r-- 1 root root  324 Jun  2 09:07 summary_verb.csv

## Giai đoạn 8 — Nén và lưu Drive

In [111]:
!zip -r /content/project_outputs/acrf-rnn.zip /content/project_outputs/
!ls -lh /content/project_outputs/acrf-rnn.zip

import shutil, os
drive_save_path = '/content/drive/MyDrive/ACRF-RNN'
os.makedirs(drive_save_path, exist_ok=True)
shutil.copy('/content/project_outputs/acrf-rnn.zip',
            f'{drive_save_path}/acrf-rnn.zip')
print(f'Đã lưu vào Drive: {drive_save_path}/acrf-rnn.zip')

updating: content/project_outputs/ (stored 0%)
updating: content/project_outputs/summary_vera.csv (deflated 48%)
updating: content/project_outputs/epoch_vera.csv (deflated 73%)
updating: content/project_outputs/run_vera_2018.log (deflated 75%)
updating: content/project_outputs/epoch_verb.csv (deflated 68%)
updating: content/project_outputs/summary_verb.csv (deflated 45%)
updating: content/project_outputs/compare_3way.csv (deflated 52%)
updating: content/project_outputs/run_vera_2020.log (deflated 81%)
updating: content/project_outputs/attention_graph/ (stored 0%)
updating: content/project_outputs/run_vera_2019.log (deflated 77%)
updating: content/project_outputs/run_2018.log (deflated 85%)
updating: content/project_outputs/run_2019.log (deflated 86%)
updating: content/project_outputs/run_2020.log (deflated 84%)
  adding: content/project_outputs/checkpoints/ (stored 0%)
  adding: content/project_outputs/checkpoints/vera_best_test_year_2018.pt (deflated 8%)
  adding: content/project_outputs/attention_graph/attention_weights_2018.csv (deflated 72%)
  adding: content/project_outputs/attention_graph/attention_relation_edge_2018.csv (deflated 76%)
  adding: content/project_outputs/run_vera_ckpt_2018.log (deflated 75%)
-rw-r--r-- 1 root root 18M Jun  2 09:08 /content/project_outputs/acrf-rnn.zip
Đã lưu vào Drive: /content/drive/MyDrive/ACRF-RNN/acrf-rnn.zip